#Input directory where the files produced at the stage1 level are
inputDir = "/eos/experiment/fcc/ee/analyses_storage/Higgs_and_TOP/HiggsTauTau/ecm240/BDT_250502/ktN-tag/stage3/NuNu/LL/"

outputDir = "/eos/experiment/fcc/ee/analyses_storage/Higgs_and_TOP/HiggsTauTau/ecm240/BDT_250502/ktN-tag/final/NuNu/LL/"

#Integrated luminosity for scaling number of events (required only if setting doScale to true)
intLumi = 10.8e6 #pb^-1 #to be checked again for 240 gev

#Scale event yields by intLumi and cross section (optional)
# if scaling, both the number of events in the table and in the histograms will be scaled
doScale = True

#Save event yields in a table (optional)
saveTabular = False

#Number of CPUs to use
#nCPUs = 6

#produces ROOT TTrees, default is False
doTree = False

processList = {
    'p8_ee_WW_ecm240':{},
    'p8_ee_Zqq_ecm240':{},
    'p8_ee_ZZ_ecm240':{},
    
    'wzp6_ee_tautau_ecm240':{},
    'wzp6_ee_mumu_ecm240':{},
    'wzp6_ee_ee_Mee_30_150_ecm240':{},

    'wzp6_ee_tautauH_Htautau_ecm240': {},
    'wzp6_ee_tautauH_Hbb_ecm240': {},
    'wzp6_ee_tautauH_Hcc_ecm240': {},
    'wzp6_ee_tautauH_Hss_ecm240': {},
    'wzp6_ee_tautauH_Hgg_ecm240': {},
    'wzp6_ee_tautauH_HWW_ecm240': {},
    'wzp6_ee_tautauH_HZZ_ecm240': {},

    'wzp6_egamma_eZ_Zmumu_ecm240': {},
    'wzp6_egamma_eZ_Zee_ecm240': {},
    'wzp6_gammae_eZ_Zmumu_ecm240': {},
    'wzp6_gammae_eZ_Zee_ecm240': {},

    'wzp6_gaga_tautau_60_ecm240': {},
    'wzp6_gaga_mumu_60_ecm240': {},
    'wzp6_gaga_ee_60_ecm240': {},

    'wzp6_ee_nuenueZ_ecm240': {},

    'wzp6_ee_nunuH_Htautau_ecm240': {},
    'wzp6_ee_nunuH_Hbb_ecm240': {},
    'wzp6_ee_nunuH_Hcc_ecm240': {},
    'wzp6_ee_nunuH_Hss_ecm240': {},
    'wzp6_ee_nunuH_Hgg_ecm240': {},
    'wzp6_ee_nunuH_HWW_ecm240': {},
    'wzp6_ee_nunuH_HZZ_ecm240': {},

    'wzp6_ee_eeH_Htautau_ecm240': {},
    'wzp6_ee_eeH_Hbb_ecm240': {},
    'wzp6_ee_eeH_Hcc_ecm240': {},
    'wzp6_ee_eeH_Hss_ecm240': {},
    'wzp6_ee_eeH_Hgg_ecm240': {},
    'wzp6_ee_eeH_HWW_ecm240': {},
    'wzp6_ee_eeH_HZZ_ecm240': {},

    'wzp6_ee_mumuH_Htautau_ecm240': {},
    'wzp6_ee_mumuH_Hbb_ecm240': {},
    'wzp6_ee_mumuH_Hcc_ecm240': {},
    'wzp6_ee_mumuH_Hss_ecm240': {},
    'wzp6_ee_mumuH_Hgg_ecm240': {},
    'wzp6_ee_mumuH_HWW_ecm240': {},
    'wzp6_ee_mumuH_HZZ_ecm240': {},

    'wzp6_ee_bbH_Htautau_ecm240': {},
    'wzp6_ee_bbH_Hbb_ecm240': {},
    'wzp6_ee_bbH_Hcc_ecm240': {},
    'wzp6_ee_bbH_Hss_ecm240': {},
    'wzp6_ee_bbH_Hgg_ecm240': {},
    'wzp6_ee_bbH_HWW_ecm240': {},
    'wzp6_ee_bbH_HZZ_ecm240': {},

    'wzp6_ee_ccH_Htautau_ecm240': {},
    'wzp6_ee_ccH_Hbb_ecm240': {},
    'wzp6_ee_ccH_Hcc_ecm240': {},
    'wzp6_ee_ccH_Hss_ecm240': {},
    'wzp6_ee_ccH_Hgg_ecm240': {},
    'wzp6_ee_ccH_HWW_ecm240': {},
    'wzp6_ee_ccH_HZZ_ecm240': {},

    'wzp6_ee_ssH_Htautau_ecm240': {},
    'wzp6_ee_ssH_Hbb_ecm240': {},
    'wzp6_ee_ssH_Hcc_ecm240': {},
    'wzp6_ee_ssH_Hss_ecm240': {},
    'wzp6_ee_ssH_Hgg_ecm240': {},
    'wzp6_ee_ssH_HWW_ecm240': {},
    'wzp6_ee_ssH_HZZ_ecm240': {},

    'wzp6_ee_qqH_Htautau_ecm240': {},
    'wzp6_ee_qqH_Hbb_ecm240': {},
    'wzp6_ee_qqH_Hcc_ecm240': {},
    'wzp6_ee_qqH_Hss_ecm240': {},
    'wzp6_ee_qqH_Hgg_ecm240': {},
    'wzp6_ee_qqH_HWW_ecm240': {},
    'wzp6_ee_qqH_HZZ_ecm240': {},
}

###Dictionary for prettier names of processes (optional)
#change them if you want but they don't do anything
processLabels = {}

#Link to the dictonary that contains all the cross section information etc...
procDict = "FCCee_procDict_winter2023_IDEA.json"

#Add provate samples as it is not an offical process
procDictAdd = {}

###Dictionnay of the list of cuts. The key is the name of the selection that will be added to the output file
cutList = {
    ### no selection, just builds the histograms, it will not be shown in the latex table
    "selReco": "true",
    "selReco_100Me": "RecoEmiss_e>100",
    "selReco_100Me_TauDPhi3": "RecoEmiss_e>100 && abs(Tau_DPhi)<3",
    "selReco_100Me_TauDPhi3_2DR": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2",
    "selReco_100Me_TauDPhi3_2DR_cos0.4": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4",
    "selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4 && RecoEmiss_costheta<0.98",
    "selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98_missy1": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4 && RecoEmiss_costheta<0.98 && abs(RecoEmiss_y)<1",
    
}

# Dictionary for prettier names of cuts (optional)
### needs to be in the same order as cutList or the table won't be organised well, it's only for the table ###
cutLabels = {
    "selReco": "No additional selection",
    "selReco_100Me": "E_{miss}>100 GeV",
    "selReco_100Me_TauDPhi3": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3",
    "selReco_100Me_TauDPhi3_2DR": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2",
    "selReco_100Me_TauDPhi3_2DR_cos0.4": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2, cos#theta_{#tau}<-0.4}",
    "selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2, cos#theta_{#tau}<-0.4}, |cos#theta_{miss}|<0.98}",
    "selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98_missy1": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2, cos#theta_{#tau}<-0.4}, |cos#theta_{miss}|<0.98} && |y_{miss}|<1",
}

###Dictionary for the ouput variable/hitograms. The key is the name of the variable in the output files. "name" is the name of the variable in the input file, "title" is the x-axis label of the histogram, "bin" the number of bins of the histogram, "xmin" the minimum x-axis value and "xmax" the maximum x-axis value.
histoList = {
    ######## Reconstructed particles #######

    "n_RecoElectrons":                  {"name":"n_RecoElectrons",                  "title":"Number of reco electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_e":                   {"name":"RecoElectron_e",                   "title":"Reco electron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_p":                   {"name":"RecoElectron_p",                   "title":"Reco electron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_pt":                  {"name":"RecoElectron_pt",                  "title":"Reco electron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_px":                  {"name":"RecoElectron_px",                  "title":"Reco electron p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_py":                  {"name":"RecoElectron_py",                  "title":"Reco electron p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_pz":                  {"name":"RecoElectron_pz",                  "title":"Reco electron p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_y":                   {"name":"RecoElectron_y",                   "title":"Reco electron rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_eta":                 {"name":"RecoElectron_eta",                 "title":"Reco electron #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_theta":               {"name":"RecoElectron_theta",               "title":"Reco electron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_phi":                 {"name":"RecoElectron_phi",                 "title":"Reco electron #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_charge":              {"name":"RecoElectron_charge",              "title":"Reco electron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_mass":                {"name":"RecoElectron_mass",                "title":"Reco electron mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_absD0":          {"name":"RecoElectronTrack_absD0",          "title":"Reco electron tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absZ0":          {"name":"RecoElectronTrack_absZ0",          "title":"Reco electron tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absD0sig":       {"name":"RecoElectronTrack_absD0sig",       "title":"Reco electron tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_absZ0sig":       {"name":"RecoElectronTrack_absZ0sig",       "title":"Reco electron tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_D0cov":          {"name":"RecoElectronTrack_D0cov",          "title":"Reco electron tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_Z0cov":          {"name":"RecoElectronTrack_Z0cov",          "title":"Reco electron tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoElectrons_sel":                  {"name":"n_RecoElectrons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_sel_e":                   {"name":"RecoElectron_sel_e",                   "title":"Reco electron isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_p":                   {"name":"RecoElectron_sel_p",                   "title":"Reco electron isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_pt":                  {"name":"RecoElectron_sel_pt",                  "title":"Reco electron isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_px":                  {"name":"RecoElectron_sel_px",                  "title":"Reco electron isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_py":                  {"name":"RecoElectron_sel_py",                  "title":"Reco electron isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_pz":                  {"name":"RecoElectron_sel_pz",                  "title":"Reco electron isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_y":                   {"name":"RecoElectron_sel_y",                   "title":"Reco electron isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_sel_eta":                 {"name":"RecoElectron_sel_eta",                 "title":"Reco electron isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_theta":               {"name":"RecoElectron_sel_theta",               "title":"Reco electron isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_sel_phi":                 {"name":"RecoElectron_sel_phi",                 "title":"Reco electron isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_charge":              {"name":"RecoElectron_sel_charge",              "title":"Reco electron isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_sel_mass":                {"name":"RecoElectron_sel_mass",                "title":"Reco electron isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_sel_absD0":          {"name":"RecoElectronTrack_sel_absD0",          "title":"Reco electron isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absZ0":          {"name":"RecoElectronTrack_sel_absZ0",          "title":"Reco electron isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absD0sig":       {"name":"RecoElectronTrack_sel_absD0sig",       "title":"Reco electron isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_absZ0sig":       {"name":"RecoElectronTrack_sel_absZ0sig",       "title":"Reco electron isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_D0cov":          {"name":"RecoElectronTrack_sel_D0cov",          "title":"Reco electron isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_sel_Z0cov":          {"name":"RecoElectronTrack_sel_Z0cov",          "title":"Reco electron isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons":                  {"name":"n_RecoMuons",                  "title":"Number of reco muons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_e":                   {"name":"RecoMuon_e",                   "title":"Reco muon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_p":                   {"name":"RecoMuon_p",                   "title":"Reco muon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_pt":                  {"name":"RecoMuon_pt",                  "title":"Reco muon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_px":                  {"name":"RecoMuon_px",                  "title":"Reco muon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_py":                  {"name":"RecoMuon_py",                  "title":"Reco muon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_pz":                  {"name":"RecoMuon_pz",                  "title":"Reco muon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_y":                   {"name":"RecoMuon_y",                   "title":"Reco muon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_eta":                 {"name":"RecoMuon_eta",                 "title":"Reco muon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_theta":               {"name":"RecoMuon_theta",               "title":"Reco muon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_phi":                 {"name":"RecoMuon_phi",                 "title":"Reco muon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_charge":              {"name":"RecoMuon_charge",              "title":"Reco muon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_mass":                {"name":"RecoMuon_mass",                "title":"Reco muon mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_absD0":          {"name":"RecoMuonTrack_absD0",          "title":"Reco muon tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absZ0":          {"name":"RecoMuonTrack_absZ0",          "title":"Reco muon tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absD0sig":       {"name":"RecoMuonTrack_absD0sig",       "title":"Reco muon tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_absZ0sig":       {"name":"RecoMuonTrack_absZ0sig",       "title":"Reco muon tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_D0cov":          {"name":"RecoMuonTrack_D0cov",          "title":"Reco muon tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_Z0cov":          {"name":"RecoMuonTrack_Z0cov",          "title":"Reco muon tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons_sel":                  {"name":"n_RecoMuons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_sel_e":                   {"name":"RecoMuon_sel_e",                   "title":"Reco muon isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_p":                   {"name":"RecoMuon_sel_p",                   "title":"Reco muon isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_pt":                  {"name":"RecoMuon_sel_pt",                  "title":"Reco muon isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_px":                  {"name":"RecoMuon_sel_px",                  "title":"Reco muon isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_py":                  {"name":"RecoMuon_sel_py",                  "title":"Reco muon isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_pz":                  {"name":"RecoMuon_sel_pz",                  "title":"Reco muon isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_y":                   {"name":"RecoMuon_sel_y",                   "title":"Reco muon isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_sel_eta":                 {"name":"RecoMuon_sel_eta",                 "title":"Reco muon isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_theta":               {"name":"RecoMuon_sel_theta",               "title":"Reco muon isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_sel_phi":                 {"name":"RecoMuon_sel_phi",                 "title":"Reco muon isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_charge":              {"name":"RecoMuon_sel_charge",              "title":"Reco muon isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_sel_mass":                {"name":"RecoMuon_sel_mass",                "title":"Reco muon isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_sel_absD0":          {"name":"RecoMuonTrack_sel_absD0",          "title":"Reco muon isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absZ0":          {"name":"RecoMuonTrack_sel_absZ0",          "title":"Reco muon isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absD0sig":       {"name":"RecoMuonTrack_sel_absD0sig",       "title":"Reco muon isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_absZ0sig":       {"name":"RecoMuonTrack_sel_absZ0sig",       "title":"Reco muon isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_D0cov":          {"name":"RecoMuonTrack_sel_D0cov",          "title":"Reco muon isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_sel_Z0cov":          {"name":"RecoMuonTrack_sel_Z0cov",          "title":"Reco muon isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons":                {"name":"n_RecoLeptons",                  "title":"Number of reco leptons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoLepton_e":                 {"name":"RecoLepton_e",                   "title":"Reco lepton energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_p":                 {"name":"RecoLepton_p",                   "title":"Reco lepton p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_pt":                {"name":"RecoLepton_pt",                  "title":"Reco lepton p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_px":                {"name":"RecoLepton_px",                  "title":"Reco lepton p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_py":                {"name":"RecoLepton_py",                  "title":"Reco lepton p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_pz":                {"name":"RecoLepton_pz",                  "title":"Reco lepton p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_y":                 {"name":"RecoLepton_y",                   "title":"Reco lepton rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_eta":               {"name":"RecoLepton_eta",                 "title":"Reco lepton #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_theta":             {"name":"RecoLepton_theta",               "title":"Reco lepton #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_phi":               {"name":"RecoLepton_phi",                 "title":"Reco lepton #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_charge":            {"name":"RecoLepton_charge",              "title":"Reco lepton charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_mass":              {"name":"RecoLepton_mass",                "title":"Reco lepton mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_absD0":        {"name":"RecoLeptonTrack_absD0",          "title":"Reco lepton tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absZ0":        {"name":"RecoLeptonTrack_absZ0",          "title":"Reco lepton tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absD0sig":     {"name":"RecoLeptonTrack_absD0sig",       "title":"Reco lepton tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_absZ0sig":     {"name":"RecoLeptonTrack_absZ0sig",       "title":"Reco lepton tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_D0cov":        {"name":"RecoLeptonTrack_D0cov",          "title":"Reco lepton tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_Z0cov":        {"name":"RecoLeptonTrack_Z0cov",          "title":"Reco lepton tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons_sel":                {"name":"n_RecoLeptons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.},
    "RecoLepton_sel_e":                 {"name":"RecoLepton_sel_e",                   "title":"Reco lepton isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_p":                 {"name":"RecoLepton_sel_p",                   "title":"Reco lepton isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_pt":                {"name":"RecoLepton_sel_pt",                  "title":"Reco lepton isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_px":                {"name":"RecoLepton_sel_px",                  "title":"Reco lepton isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_py":                {"name":"RecoLepton_sel_py",                  "title":"Reco lepton isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_pz":                {"name":"RecoLepton_sel_pz",                  "title":"Reco lepton isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_y":                 {"name":"RecoLepton_sel_y",                   "title":"Reco lepton isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_sel_eta":               {"name":"RecoLepton_sel_eta",                 "title":"Reco lepton isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_theta":             {"name":"RecoLepton_sel_theta",               "title":"Reco lepton isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_sel_phi":               {"name":"RecoLepton_sel_phi",                 "title":"Reco lepton isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_charge":            {"name":"RecoLepton_sel_charge",              "title":"Reco lepton isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_sel_mass":              {"name":"RecoLepton_sel_mass",                "title":"Reco lepton isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_sel_absD0":        {"name":"RecoLeptonTrack_sel_absD0",          "title":"Reco lepton isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absZ0":        {"name":"RecoLeptonTrack_sel_absZ0",          "title":"Reco lepton isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absD0sig":     {"name":"RecoLeptonTrack_sel_absD0sig",       "title":"Reco lepton isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_absZ0sig":     {"name":"RecoLeptonTrack_sel_absZ0sig",       "title":"Reco lepton isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_D0cov":        {"name":"RecoLeptonTrack_sel_D0cov",          "title":"Reco lepton isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_sel_Z0cov":        {"name":"RecoLeptonTrack_sel_Z0cov",          "title":"Reco lepton isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoPhotons":            {"name":"n_RecoPhotons",                  "title":"Number of reco photons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoPhoton_e":             {"name":"RecoPhoton_e",                   "title":"Reco photon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_p":             {"name":"RecoPhoton_p",                   "title":"Reco photon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_pt":            {"name":"RecoPhoton_pt",                  "title":"Reco photon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_px":            {"name":"RecoPhoton_px",                  "title":"Reco photon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_py":            {"name":"RecoPhoton_py",                  "title":"Reco photon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_pz":            {"name":"RecoPhoton_pz",                  "title":"Reco photon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_y":             {"name":"RecoPhoton_y",                   "title":"Reco photon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoPhoton_eta":           {"name":"RecoPhoton_eta",                 "title":"Reco photon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_theta":         {"name":"RecoPhoton_theta",               "title":"Reco photon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoPhoton_phi":           {"name":"RecoPhoton_phi",                 "title":"Reco photon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_charge":        {"name":"RecoPhoton_charge",              "title":"Reco photon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoPhoton_mass":          {"name":"RecoPhoton_mass",                 "title":"Reco photon mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "RecoEmiss_px":             {"name":"RecoEmiss_px",                  "title":"Reco missing energy p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_py":             {"name":"RecoEmiss_py",                  "title":"Reco missing energy p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pz":             {"name":"RecoEmiss_pz",                  "title":"Reco missing energy p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pt":             {"name":"RecoEmiss_pt",                  "title":"Reco missing energy p_{T} [GeV]",                    "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_p":              {"name":"RecoEmiss_p",                   "title":"Reco missing energy p [GeV]",                        "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_e":              {"name":"RecoEmiss_e",                   "title":"Reco missing energy energy [GeV]",                   "bin":60,"xmin":0 ,"xmax":240},
    "RecoEmiss_eta":            {"name":"RecoEmiss_eta",                 "title":"Reco missing energy #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_phi":            {"name":"RecoEmiss_phi",                 "title":"Reco missing energy #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_theta":          {"name":"RecoEmiss_theta",               "title":"Reco missing energy #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoEmiss_y":              {"name":"RecoEmiss_y",                   "title":"Reco missing energy rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoEmiss_costheta":       {"name":"RecoEmiss_costheta",               "title":"Reco missing energy |cos(#theta)|",                 "bin":50, "xmin":0,"xmax":1.},

    "TagJet_R5_e":                {"name":"TagJet_R5_e",                   "title":"R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "TagJet_R5_p":                {"name":"TagJet_R5_p",                   "title":"R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_pt":               {"name":"TagJet_R5_pt",                  "title":"R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_px":               {"name":"TagJet_R5_px",                  "title":"R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_py":               {"name":"TagJet_R5_py",                  "title":"R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_pz":               {"name":"TagJet_R5_pz",                  "title":"R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_eta":              {"name":"TagJet_R5_eta",                 "title":"R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_theta":            {"name":"TagJet_R5_theta",               "title":"R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_R5_phi":              {"name":"TagJet_R5_phi",                 "title":"R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_mass":             {"name":"TagJet_R5_mass",                "title":"R5 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_R5_charge":             {"name":"TagJet_R5_charge",                "title":"R5 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_R5":                {"name":"n_TagJet_R5",                   "title":"Number of R5 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_R5_constituents":             {"name":"n_TagJet_R5_constituents",               "title":"R5 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_R5_charged_constituents":             {"name":"n_TagJet_R5_charged_constituents",               "title":"R5 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_R5_neutral_constituents":             {"name":"n_TagJet_R5_neutral_constituents",               "title":"R5 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_R5_isG":             {"name":"TagJet_R5_isG",                "title":"R5 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isU":             {"name":"TagJet_R5_isU",                "title":"R5 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isD":             {"name":"TagJet_R5_isD",                "title":"R5 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isS":             {"name":"TagJet_R5_isS",                "title":"R5 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isC":             {"name":"TagJet_R5_isC",                "title":"R5 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isB":             {"name":"TagJet_R5_isB",                "title":"R5 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isTAU":             {"name":"TagJet_R5_isTAU",                "title":"R5 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_R5_p":          {"name":"TauFromJet_R5_p",                   "title":"#tau from R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_pt":         {"name":"TauFromJet_R5_pt",                  "title":"#tau from R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_px":         {"name":"TauFromJet_R5_px",                  "title":"#tau from R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_py":         {"name":"TauFromJet_R5_py",                  "title":"#tau from R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_pz":         {"name":"TauFromJet_R5_pz",                  "title":"#tau from R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_theta":      {"name":"TauFromJet_R5_theta",               "title":"#tau from R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_R5_phi":        {"name":"TauFromJet_R5_phi",                 "title":"#tau from R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_e":          {"name":"TauFromJet_R5_e",                   "title":"#tau from R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_eta":        {"name":"TauFromJet_R5_eta",                 "title":"#tau from R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_y":          {"name":"TauFromJet_R5_y",                   "title":"#tau from R5 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_R5_charge":     {"name":"TauFromJet_R5_charge",              "title":"#tau from R5 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_R5_type":       {"name":"TauFromJet_R5_type",                "title":"#tau from R5 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_R5_mass":       {"name":"TauFromJet_R5_mass",                "title":"#tau from R5 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_R5":          {"name":"n_TauFromJet_R5",                   "title":"Number of #tau from R5 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_R5_sel_e":            {"name":"TagJet_R5_sel_e",                   "title":"Quark/gluon R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},    
    "TagJet_R5_sel_p":            {"name":"TagJet_R5_sel_p",                   "title":"Quark/gluon R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_sel_pt":           {"name":"TagJet_R5_sel_pt",                  "title":"Quark/gluon R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_sel_px":           {"name":"TagJet_R5_sel_px",                  "title":"Quark/gluon R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_sel_py":           {"name":"TagJet_R5_sel_py",                  "title":"Quark/gluon R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_sel_pz":           {"name":"TagJet_R5_sel_pz",                  "title":"Quark/gluon R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_sel_eta":          {"name":"TagJet_R5_sel_eta",                 "title":"Quark/gluon R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_sel_theta":        {"name":"TagJet_R5_sel_theta",               "title":"Quark/gluon R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_R5_sel_phi":          {"name":"TagJet_R5_sel_phi",                 "title":"Quark/gluon R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_sel_mass":         {"name":"TagJet_R5_sel_mass",                "title":"Quark/gluon R5 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_R5_sel":            {"name":"n_TagJet_R5_sel",                   "title":"Number of Quark/gluon R5 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    ####################

    "TauTag_e":                {"name":"TauTag_e",                   "title":"#tau from tagged jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "TauTag_p":                {"name":"TauTag_p",                   "title":"#tau from tagged jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauTag_pt":               {"name":"TauTag_pt",                  "title":"#tau from tagged jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauTag_px":               {"name":"TauTag_px",                  "title":"#tau from tagged jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauTag_py":               {"name":"TauTag_py",                  "title":"#tau from tagged jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauTag_pz":               {"name":"TauTag_pz",                  "title":"#tau from tagged jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauTag_eta":              {"name":"TauTag_eta",                 "title":"#tau from tagged jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauTag_theta":            {"name":"TauTag_theta",               "title":"#tau from tagged jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauTag_phi":              {"name":"TauTag_phi",                 "title":"#tau from tagged jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauTag_mass":             {"name":"TauTag_mass",                "title":"#tau from tagged jet mass [GeV]",                     "bin":60, "xmin":0., "xmax":30.},
    "n_TauTag":                {"name":"n_TauTag",                   "title":"Number of #tau from tagged jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TauTag_isG":             {"name":"TauTag_isG",                "title":"#tau from tagged jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isU":             {"name":"TauTag_isU",                "title":"#tau from tagged jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isD":             {"name":"TauTag_isD",                "title":"#tau from tagged jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isC":             {"name":"TauTag_isC",                "title":"#tau from tagged jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isS":             {"name":"TauTag_isS",                "title":"#tau from tagged jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isB":             {"name":"TauTag_isB",                "title":"#tau from tagged jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isTAU":             {"name":"TauTag_isTAU",                "title":"#tau from tagged jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "QuarkTag_e":                {"name":"QuarkTag_e",                   "title":"Quark jet from tagged jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "QuarkTag_p":                {"name":"QuarkTag_p",                   "title":"Quark jet from tagged jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "QuarkTag_pt":               {"name":"QuarkTag_pt",                  "title":"Quark jet from tagged jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "QuarkTag_px":               {"name":"QuarkTag_px",                  "title":"Quark jet from tagged jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "QuarkTag_py":               {"name":"QuarkTag_py",                  "title":"Quark jet from tagged jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "QuarkTag_pz":               {"name":"QuarkTag_pz",                  "title":"Quark jet from tagged jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "QuarkTag_eta":              {"name":"QuarkTag_eta",                 "title":"Quark jet from tagged jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "QuarkTag_theta":            {"name":"QuarkTag_theta",               "title":"Quark jet from tagged jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "QuarkTag_phi":              {"name":"QuarkTag_phi",                 "title":"Quark jet from tagged jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "QuarkTag_mass":             {"name":"QuarkTag_mass",                "title":"Quark jet from tagged jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_QuarkTag":                {"name":"n_QuarkTag",                   "title":"Number of Quark jet from tagged jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "QuarkTag_isG":             {"name":"QuarkTag_isG",                "title":"Quark jet from tagged jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isU":             {"name":"QuarkTag_isU",                "title":"Quark jet from tagged jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isD":             {"name":"QuarkTag_isD",                "title":"Quark jet from tagged jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isC":             {"name":"QuarkTag_isC",                "title":"Quark jet from tagged jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isS":             {"name":"QuarkTag_isS",                "title":"Quark jet from tagged jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isB":             {"name":"QuarkTag_isB",                "title":"Quark jet from tagged jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isTAU":             {"name":"QuarkTag_isTAU",                "title":"Quark jet from tagged jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},
                            
    "RecoH_px":                 {"name":"RecoH_px",                 "title":"Reco H p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_py":                 {"name":"RecoH_py",                 "title":"Reco H p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_pz":                 {"name":"RecoH_pz",                 "title":"Reco H p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_p":                  {"name":"RecoH_p",                  "title":"Reco H p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_pt":                 {"name":"RecoH_pt",                 "title":"Reco H p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_e":                  {"name":"RecoH_e",                  "title":"Reco H energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_eta":                {"name":"RecoH_eta",                "title":"Reco H #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_phi":                {"name":"RecoH_phi",                "title":"Reco H #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_theta":              {"name":"RecoH_theta",              "title":"Reco H #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoH_y":                  {"name":"RecoH_y",                  "title":"Reco H rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoH_mass":               {"name":"RecoH_mass",               "title":"Reco H mass",                   "bin":75, "xmin":0 ,"xmax":150},

    "TauLead_px":               {"name":"TauLead_px",                 "title":"#tau_{leading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_py":               {"name":"TauLead_py",                 "title":"#tau_{leading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_pz":               {"name":"TauLead_pz",                 "title":"#tau_{leading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_p":                {"name":"TauLead_p",                  "title":"#tau_{leading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_pt":               {"name":"TauLead_pt",                 "title":"#tau_{leading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_e":                {"name":"TauLead_e",                  "title":"#tau_{leading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauLead_eta":              {"name":"TauLead_eta",                "title":"#tau_{leading} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_phi":              {"name":"TauLead_phi",                "title":"#tau_{leading} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_theta":            {"name":"TauLead_theta",              "title":"#tau_{leading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauLead_y":                {"name":"TauLead_y",                  "title":"#tau_{leading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauLead_mass":             {"name":"TauLead_mass",               "title":"#tau_{leading} mass",                   "bin":30, "xmin":0., "xmax":3.},
    "TauLead_type":             {"name":"TauLead_type",               "title":"#tau_{leading} type",                   "bin":113, "xmin":-0.13, "xmax":1.},
    "n_TauLead_constituents":             {"name":"n_TauLead_constituents",               "title":"#tau_{leading} constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TauLead_charged_constituents":             {"name":"n_TauLead_charged_constituents",               "title":"#tau_{leading} charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TauLead_neutral_constituents":             {"name":"n_TauLead_neutral_constituents",               "title":"#tau_{leading} neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TauSub_px":                {"name":"TauSub_px",                 "title":"#tau_{subleading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_py":                {"name":"TauSub_py",                 "title":"#tau_{subleading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_pz":                {"name":"TauSub_pz",                 "title":"#tau_{subleading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_p":                 {"name":"TauSub_p",                  "title":"#tau_{subleading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_pt":                {"name":"TauSub_pt",                 "title":"#tau_{subleading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_e":                 {"name":"TauSub_e",                  "title":"#tau_{subleading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauSub_eta":               {"name":"TauSub_eta",                "title":"#tau_{subleading} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_phi":               {"name":"TauSub_phi",                "title":"#tau_{subleading} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_theta":             {"name":"TauSub_theta",              "title":"#tau_{subleading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauSub_y":                 {"name":"TauSub_y",                  "title":"#tau_{subleading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauSub_mass":              {"name":"TauSub_mass",               "title":"#tau_{subleading} mass",                   "bin":30, "xmin":0., "xmax":3.},
    "TauSub_type":              {"name":"TauSub_type",               "title":"#tau_{subleading} type",                   "bin":113, "xmin":-0.13, "xmax":1.},
    "n_TauSub_constituents":             {"name":"n_TauSub_constituents",               "title":"#tau_{subleading} constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TauSub_charged_constituents":             {"name":"n_TauSub_charged_constituents",               "title":"#tau_{subleading} charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TauSub_neutral_constituents":             {"name":"n_TauSub_neutral_constituents",               "title":"#tau_{subleading} neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "Tau_DPhi":         {"name":"Tau_DPhi",           "title":"#Delta#phi(#tau#tau)",                "bin":32, "xmin":-3.2,"xmax":3.2},
    "Tau_DR":                   {"name":"Tau_DR",                     "title":"#Delta R(#tau#tau)",                  "bin":70, "xmin":0,"xmax":7},
    "Tau_cos":                  {"name":"Tau_cos",                    "title":"cos#theta(#tau#tau)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "Tau_DEta":                             {"name":"Tau_DEta",           "title":"Reco di-#tau #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "Visible_mass":               {"name":"Visible_mass",               "title":"Visible mass",                   "bin":75, "xmin":0 ,"xmax":150},
}