#Input directory where the files produced at the stage1 level are
inputDir = "/ceph/sgiappic/HiggsCP/CP/stage2_alltau"

#Optional: output directory, default is local running directory
outputDir = "/ceph/sgiappic/HiggsCP/CP/final_alltau"

#Integrated luminosity for scaling number of events (required only if setting doScale to true)
intLumi = 10.8e6 #pb^-1 #to be checked again for 240 gev

#Scale event yields by intLumi and cross section (optional)
# if scaling, both the number of events in the table and in the histograms will be scaled
doScale = True

#Save event yields in a table (optional)
saveTabular = True

#Number of CPUs to use
nCPUS = 4

#produces ROOT TTrees, default is False
doTree = False

#Mandatory: List of processes
processList = {
    'noISR_e+e-_noCuts_EWonly':{},
    'noISR_e+e-_noCuts_cehim_m1':{},
    'noISR_e+e-_noCuts_cehim_p1':{},
    'noISR_e+e-_noCuts_cehre_m1':{},
    'noISR_e+e-_noCuts_cehre_p1':{},
}
###Dictionary for prettier names of processes (optional)
#change them if you want but they don't do anything
processLabels = {}

#Link to the dictonary that contains all the cross section information etc...
procDict = "FCCee_procDict_winter2023_IDEA.json"

#Add provate samples as it is not an offical process
procDictAdd = {
    'noISR_e+e-_noCuts_EWonly':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051559935862, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehim_m1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051749741618, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehim_p1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051749741618, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehre_m1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00058001482393, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehre_p1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00045498699833000005, "kfactor": 1.0, "matchingEfficiency": 1.0},

}

###Dictionnay of the list of cuts. The key is the name of the selection that will be added to the output file
cutList = {
    ### no selection, just builds the histograms, it will not be shown in the latex table
    "selReco": "true",
    #"selReco_Maria": " (Recoil>120 && Recoil<140) && (TauFromJet_type[0]>=0 && TauFromJet_type[1]>=0)",
}

# Dictionary for prettier names of cuts (optional)
### needs to be in the same order as cutList or the table won't be organised well, it's only for the table ###
cutLabels = {}

###Dictionary for the ouput variable/hitograms. The key is the name of the variable in the output files. "name" is the name of the variable in the input file, "title" is the x-axis label of the histogram, "bin" the number of bins of the histogram, "xmin" the minimum x-axis value and "xmax" the maximum x-axis value.
histoList = {
    ######## Reconstructed particles #######

    "n_RecoElectrons":                  {"name":"n_RecoElectrons",                  "title":"Number of reco electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_e":                   {"name":"RecoElectron_e",                   "title":"Reco electron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_p":                   {"name":"RecoElectron_p",                   "title":"Reco electron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_pt":                  {"name":"RecoElectron_pt",                  "title":"Reco electron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_px":                  {"name":"RecoElectron_px",                  "title":"Reco electron p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_py":                  {"name":"RecoElectron_py",                  "title":"Reco electron p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_pz":                  {"name":"RecoElectron_pz",                  "title":"Reco electron p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_y":                   {"name":"RecoElectron_y",                   "title":"Reco electron rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_eta":                 {"name":"RecoElectron_eta",                 "title":"Reco electron #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_theta":               {"name":"RecoElectron_theta",               "title":"Reco electron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_phi":                 {"name":"RecoElectron_phi",                 "title":"Reco electron #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_charge":              {"name":"RecoElectron_charge",              "title":"Reco electron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_mass":                {"name":"RecoElectron_mass",                "title":"Reco electron mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_absD0":          {"name":"RecoElectronTrack_absD0",          "title":"Reco electron tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absZ0":          {"name":"RecoElectronTrack_absZ0",          "title":"Reco electron tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absD0sig":       {"name":"RecoElectronTrack_absD0sig",       "title":"Reco electron tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_absZ0sig":       {"name":"RecoElectronTrack_absZ0sig",       "title":"Reco electron tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_D0cov":          {"name":"RecoElectronTrack_D0cov",          "title":"Reco electron tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_Z0cov":          {"name":"RecoElectronTrack_Z0cov",          "title":"Reco electron tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoElectrons_sel":                  {"name":"n_RecoElectrons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_sel_e":                   {"name":"RecoElectron_sel_e",                   "title":"Reco electron isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_p":                   {"name":"RecoElectron_sel_p",                   "title":"Reco electron isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_pt":                  {"name":"RecoElectron_sel_pt",                  "title":"Reco electron isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_px":                  {"name":"RecoElectron_sel_px",                  "title":"Reco electron isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_py":                  {"name":"RecoElectron_sel_py",                  "title":"Reco electron isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_pz":                  {"name":"RecoElectron_sel_pz",                  "title":"Reco electron isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_y":                   {"name":"RecoElectron_sel_y",                   "title":"Reco electron isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_sel_eta":                 {"name":"RecoElectron_sel_eta",                 "title":"Reco electron isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_theta":               {"name":"RecoElectron_sel_theta",               "title":"Reco electron isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_sel_phi":                 {"name":"RecoElectron_sel_phi",                 "title":"Reco electron isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_charge":              {"name":"RecoElectron_sel_charge",              "title":"Reco electron isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_sel_mass":                {"name":"RecoElectron_sel_mass",                "title":"Reco electron isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_sel_absD0":          {"name":"RecoElectronTrack_sel_absD0",          "title":"Reco electron isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absZ0":          {"name":"RecoElectronTrack_sel_absZ0",          "title":"Reco electron isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absD0sig":       {"name":"RecoElectronTrack_sel_absD0sig",       "title":"Reco electron isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_absZ0sig":       {"name":"RecoElectronTrack_sel_absZ0sig",       "title":"Reco electron isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_D0cov":          {"name":"RecoElectronTrack_sel_D0cov",          "title":"Reco electron isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_sel_Z0cov":          {"name":"RecoElectronTrack_sel_Z0cov",          "title":"Reco electron isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons":                  {"name":"n_RecoMuons",                  "title":"Number of reco muons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_e":                   {"name":"RecoMuon_e",                   "title":"Reco muon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_p":                   {"name":"RecoMuon_p",                   "title":"Reco muon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_pt":                  {"name":"RecoMuon_pt",                  "title":"Reco muon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_px":                  {"name":"RecoMuon_px",                  "title":"Reco muon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_py":                  {"name":"RecoMuon_py",                  "title":"Reco muon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_pz":                  {"name":"RecoMuon_pz",                  "title":"Reco muon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_y":                   {"name":"RecoMuon_y",                   "title":"Reco muon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_eta":                 {"name":"RecoMuon_eta",                 "title":"Reco muon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_theta":               {"name":"RecoMuon_theta",               "title":"Reco muon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_phi":                 {"name":"RecoMuon_phi",                 "title":"Reco muon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_charge":              {"name":"RecoMuon_charge",              "title":"Reco muon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_mass":                {"name":"RecoMuon_mass",                "title":"Reco muon mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_absD0":          {"name":"RecoMuonTrack_absD0",          "title":"Reco muon tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absZ0":          {"name":"RecoMuonTrack_absZ0",          "title":"Reco muon tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absD0sig":       {"name":"RecoMuonTrack_absD0sig",       "title":"Reco muon tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_absZ0sig":       {"name":"RecoMuonTrack_absZ0sig",       "title":"Reco muon tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_D0cov":          {"name":"RecoMuonTrack_D0cov",          "title":"Reco muon tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_Z0cov":          {"name":"RecoMuonTrack_Z0cov",          "title":"Reco muon tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons_sel":                  {"name":"n_RecoMuons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_sel_e":                   {"name":"RecoMuon_sel_e",                   "title":"Reco muon isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_p":                   {"name":"RecoMuon_sel_p",                   "title":"Reco muon isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_pt":                  {"name":"RecoMuon_sel_pt",                  "title":"Reco muon isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_px":                  {"name":"RecoMuon_sel_px",                  "title":"Reco muon isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_py":                  {"name":"RecoMuon_sel_py",                  "title":"Reco muon isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_pz":                  {"name":"RecoMuon_sel_pz",                  "title":"Reco muon isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_y":                   {"name":"RecoMuon_sel_y",                   "title":"Reco muon isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_sel_eta":                 {"name":"RecoMuon_sel_eta",                 "title":"Reco muon isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_theta":               {"name":"RecoMuon_sel_theta",               "title":"Reco muon isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_sel_phi":                 {"name":"RecoMuon_sel_phi",                 "title":"Reco muon isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_charge":              {"name":"RecoMuon_sel_charge",              "title":"Reco muon isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_sel_mass":                {"name":"RecoMuon_sel_mass",                "title":"Reco muon isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_sel_absD0":          {"name":"RecoMuonTrack_sel_absD0",          "title":"Reco muon isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absZ0":          {"name":"RecoMuonTrack_sel_absZ0",          "title":"Reco muon isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absD0sig":       {"name":"RecoMuonTrack_sel_absD0sig",       "title":"Reco muon isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_absZ0sig":       {"name":"RecoMuonTrack_sel_absZ0sig",       "title":"Reco muon isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_D0cov":          {"name":"RecoMuonTrack_sel_D0cov",          "title":"Reco muon isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_sel_Z0cov":          {"name":"RecoMuonTrack_sel_Z0cov",          "title":"Reco muon isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons":                {"name":"n_RecoLeptons",                  "title":"Number of reco leptons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoLepton_e":                 {"name":"RecoLepton_e",                   "title":"Reco lepton energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_p":                 {"name":"RecoLepton_p",                   "title":"Reco lepton p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_pt":                {"name":"RecoLepton_pt",                  "title":"Reco lepton p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_px":                {"name":"RecoLepton_px",                  "title":"Reco lepton p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_py":                {"name":"RecoLepton_py",                  "title":"Reco lepton p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_pz":                {"name":"RecoLepton_pz",                  "title":"Reco lepton p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_y":                 {"name":"RecoLepton_y",                   "title":"Reco lepton rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_eta":               {"name":"RecoLepton_eta",                 "title":"Reco lepton #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_theta":             {"name":"RecoLepton_theta",               "title":"Reco lepton #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_phi":               {"name":"RecoLepton_phi",                 "title":"Reco lepton #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_charge":            {"name":"RecoLepton_charge",              "title":"Reco lepton charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_mass":              {"name":"RecoLepton_mass",                "title":"Reco lepton mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_absD0":        {"name":"RecoLeptonTrack_absD0",          "title":"Reco lepton tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absZ0":        {"name":"RecoLeptonTrack_absZ0",          "title":"Reco lepton tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absD0sig":     {"name":"RecoLeptonTrack_absD0sig",       "title":"Reco lepton tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_absZ0sig":     {"name":"RecoLeptonTrack_absZ0sig",       "title":"Reco lepton tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_D0cov":        {"name":"RecoLeptonTrack_D0cov",          "title":"Reco lepton tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_Z0cov":        {"name":"RecoLeptonTrack_Z0cov",          "title":"Reco lepton tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons_sel":                {"name":"n_RecoLeptons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.},
    "RecoLepton_sel_e":                 {"name":"RecoLepton_sel_e",                   "title":"Reco lepton isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_p":                 {"name":"RecoLepton_sel_p",                   "title":"Reco lepton isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_pt":                {"name":"RecoLepton_sel_pt",                  "title":"Reco lepton isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_px":                {"name":"RecoLepton_sel_px",                  "title":"Reco lepton isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_py":                {"name":"RecoLepton_sel_py",                  "title":"Reco lepton isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_pz":                {"name":"RecoLepton_sel_pz",                  "title":"Reco lepton isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_y":                 {"name":"RecoLepton_sel_y",                   "title":"Reco lepton isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_sel_eta":               {"name":"RecoLepton_sel_eta",                 "title":"Reco lepton isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_theta":             {"name":"RecoLepton_sel_theta",               "title":"Reco lepton isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_sel_phi":               {"name":"RecoLepton_sel_phi",                 "title":"Reco lepton isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_charge":            {"name":"RecoLepton_sel_charge",              "title":"Reco lepton isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_sel_mass":              {"name":"RecoLepton_sel_mass",                "title":"Reco lepton isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_sel_absD0":        {"name":"RecoLeptonTrack_sel_absD0",          "title":"Reco lepton isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absZ0":        {"name":"RecoLeptonTrack_sel_absZ0",          "title":"Reco lepton isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absD0sig":     {"name":"RecoLeptonTrack_sel_absD0sig",       "title":"Reco lepton isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_absZ0sig":     {"name":"RecoLeptonTrack_sel_absZ0sig",       "title":"Reco lepton isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_D0cov":        {"name":"RecoLeptonTrack_sel_D0cov",          "title":"Reco lepton isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_sel_Z0cov":        {"name":"RecoLeptonTrack_sel_Z0cov",          "title":"Reco lepton isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoPhotons":            {"name":"n_RecoPhotons",                  "title":"Number of reco photons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoPhoton_e":             {"name":"RecoPhoton_e",                   "title":"Reco photon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_p":             {"name":"RecoPhoton_p",                   "title":"Reco photon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_pt":            {"name":"RecoPhoton_pt",                  "title":"Reco photon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_px":            {"name":"RecoPhoton_px",                  "title":"Reco photon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_py":            {"name":"RecoPhoton_py",                  "title":"Reco photon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_pz":            {"name":"RecoPhoton_pz",                  "title":"Reco photon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_y":             {"name":"RecoPhoton_y",                   "title":"Reco photon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoPhoton_eta":           {"name":"RecoPhoton_eta",                 "title":"Reco photon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_theta":         {"name":"RecoPhoton_theta",               "title":"Reco photon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoPhoton_phi":           {"name":"RecoPhoton_phi",                 "title":"Reco photon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_charge":        {"name":"RecoPhoton_charge",              "title":"Reco photon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},

    "RecoEmiss_px":             {"name":"RecoEmiss_px",                  "title":"Reco missing energy p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_py":             {"name":"RecoEmiss_py",                  "title":"Reco missing energy p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pz":             {"name":"RecoEmiss_pz",                  "title":"Reco missing energy p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pt":             {"name":"RecoEmiss_pt",                  "title":"Reco missing energy p_{T} [GeV]",                    "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_p":              {"name":"RecoEmiss_p",                   "title":"Reco missing energy p [GeV]",                        "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_e":              {"name":"RecoEmiss_e",                   "title":"Reco missing energy energy [GeV]",                   "bin":60,"xmin":0 ,"xmax":240},
    "RecoEmiss_eta":            {"name":"RecoEmiss_eta",                 "title":"Reco missing energy #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_phi":            {"name":"RecoEmiss_phi",                 "title":"Reco missing energy #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_theta":          {"name":"RecoEmiss_theta",               "title":"Reco missing energy #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoEmiss_y":              {"name":"RecoEmiss_y",                   "title":"Reco missing energy rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoEmiss_costheta":       {"name":"RecoEmiss_costheta",               "title":"Reco missing energy |cos(#theta)|",                 "bin":50, "xmin":0,"xmax":1.},

    "Jets_R5_e":                {"name":"Jets_R5_e",                   "title":"Jets_{R5} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "Jets_R5_p":                {"name":"Jets_R5_p",                   "title":"Jets_{R5} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_pt":               {"name":"Jets_R5_pt",                  "title":"Jets_{R5} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_px":               {"name":"Jets_R5_px",                  "title":"Jets_{R5} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_py":               {"name":"Jets_R5_py",                  "title":"Jets_{R5} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_pz":               {"name":"Jets_R5_pz",                  "title":"Jets_{R5} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_eta":              {"name":"Jets_R5_eta",                 "title":"Jets_{R5} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_theta":            {"name":"Jets_R5_theta",               "title":"Jets_{R5} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "Jets_R5_phi":              {"name":"Jets_R5_phi",                 "title":"Jets_{R5} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_mass":             {"name":"Jets_R5_mass",                "title":"Jets_{R5} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_Jets_R5":                {"name":"n_Jets_R5",                   "title":"Number of Jets_{R5}",                     "bin":5, "xmin":-0.5, "xmax":4.5},
                                
    "Jets_R5_sel_e":            {"name":"Jets_R5_sel_e",                   "title":"not hadronic #tau Jets_{R5} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},    
    "Jets_R5_sel_p":            {"name":"Jets_R5_sel_p",                   "title":"not hadronic #tau Jets_{R5} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_sel_pt":           {"name":"Jets_R5_sel_pt",                  "title":"not hadronic #tau Jets_{R5} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_sel_px":           {"name":"Jets_R5_sel_px",                  "title":"not hadronic #tau Jets_{R5} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_sel_py":           {"name":"Jets_R5_sel_py",                  "title":"not hadronic #tau Jets_{R5} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_sel_pz":           {"name":"Jets_R5_sel_pz",                  "title":"not hadronic #tau Jets_{R5} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_sel_eta":          {"name":"Jets_R5_sel_eta",                 "title":"not hadronic #tau Jets_{R5} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_sel_theta":        {"name":"Jets_R5_sel_theta",               "title":"not hadronic #tau Jets_{R5} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "Jets_R5_sel_phi":          {"name":"Jets_R5_sel_phi",                 "title":"not hadronic #tau Jets_{R5} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_sel_mass":         {"name":"Jets_R5_sel_mass",                "title":"not hadronic #tau Jets_{R5} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_Jets_R5_sel":            {"name":"n_Jets_R5_sel",                   "title":"Number of not hadronic #tau Jets_{R5}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "Jets_excl4_e":             {"name":"Jets_excl4_e",                   "title":"Jets_{kt} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},    
    "Jets_excl4_p":             {"name":"Jets_excl4_p",                   "title":"Jets_{kt} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "Jets_excl4_pt":            {"name":"Jets_excl4_pt",                  "title":"Jets_{kt} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "Jets_excl4_px":            {"name":"Jets_excl4_px",                  "title":"Jets_{kt} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_excl4_py":            {"name":"Jets_excl4_py",                  "title":"Jets_{kt} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_excl4_pz":            {"name":"Jets_excl4_pz",                  "title":"Jets_{kt} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_excl4_eta":           {"name":"Jets_excl4_eta",                 "title":"Jets_{kt} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_excl4_theta":         {"name":"Jets_excl4_theta",               "title":"Jets_{kt} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "Jets_excl4_phi":           {"name":"Jets_excl4_phi",                 "title":"Jets_{kt} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_excl4_mass":          {"name":"Jets_excl4_mass",                "title":"Jets_{kt} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_Jets_excl4":             {"name":"n_Jets_excl4",                   "title":"Number of Jets_{kt}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TauFromJet_R5_p":          {"name":"TauFromJet_R5_p",                   "title":"#tau from jet_{R5} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_pt":         {"name":"TauFromJet_R5_pt",                  "title":"#tau from jet_{R5} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_px":         {"name":"TauFromJet_R5_px",                  "title":"#tau from jet_{R5} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_py":         {"name":"TauFromJet_R5_py",                  "title":"#tau from jet_{R5} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_pz":         {"name":"TauFromJet_R5_pz",                  "title":"#tau from jet_{R5} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_theta":      {"name":"TauFromJet_R5_theta",               "title":"#tau from jet_{R5} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_R5_phi":        {"name":"TauFromJet_R5_phi",                 "title":"#tau from jet_{R5} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_e":          {"name":"TauFromJet_R5_e",                   "title":"#tau from jet_{R5} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_eta":        {"name":"TauFromJet_R5_eta",                 "title":"#tau from jet_{R5} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_y":          {"name":"TauFromJet_R5_y",                   "title":"#tau from jet_{R5} rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_R5_charge":     {"name":"TauFromJet_R5_charge",              "title":"#tau from jet_{R5} charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_R5_type":       {"name":"TauFromJet_R5_type",                "title":"#tau from jet_{R5} decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_R5_mass":       {"name":"TauFromJet_R5_mass",                "title":"#tau from jet_{R5} mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_R5":          {"name":"n_TauFromJet_R5",                   "title":"Number of #tau from Jets_{R5}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TauFromJet_p":             {"name":"TauFromJet_p",                   "title":"#tau from jet_{kt} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_pt":            {"name":"TauFromJet_pt",                  "title":"#tau from jet_{kt} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_px":            {"name":"TauFromJet_px",                  "title":"#tau from jet_{kt} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_py":            {"name":"TauFromJet_py",                  "title":"#tau from jet_{kt} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_pz":            {"name":"TauFromJet_pz",                  "title":"#tau from jet_{kt} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_theta":         {"name":"TauFromJet_theta",               "title":"#tau from jet_{kt} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_phi":           {"name":"TauFromJet_phi",                 "title":"#tau from jet_{kt} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_eta":           {"name":"TauFromJet_eta",                 "title":"#tau from jet_{kt} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_y":             {"name":"TauFromJet_y",                   "title":"#tau from jet_{kt} rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_e":             {"name":"TauFromJet_e",                   "title":"#tau from jet_{kt} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_charge":        {"name":"TauFromJet_charge",              "title":"#tau from jet_{kt} charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_type":          {"name":"TauFromJet_type",                "title":"#tau from jet_{kt} decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_mass":          {"name":"TauFromJet_mass",                "title":"#tau from jet_{kt} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TauFromJet":             {"name":"n_TauFromJet",                   "title":"Number of #tau from Jets_{kt}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "RecoZ_px":                 {"name":"RecoZ_px",                 "title":"Reco Z p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_py":                 {"name":"RecoZ_py",                 "title":"Reco Z p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_pz":                 {"name":"RecoZ_pz",                 "title":"Reco Z p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_p":                  {"name":"RecoZ_p",                  "title":"Reco Z p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_pt":                 {"name":"RecoZ_pt",                 "title":"Reco Z p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_e":                  {"name":"RecoZ_e",                  "title":"Reco Z energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_eta":                {"name":"RecoZ_eta",                "title":"Reco Z #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ_phi":                {"name":"RecoZ_phi",                "title":"Reco Z #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ_theta":              {"name":"RecoZ_theta",              "title":"Reco Z #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZ_y":                  {"name":"RecoZ_y",                  "title":"Reco Z rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoZ_mass":               {"name":"RecoZ_mass",               "title":"Reco Z mass",                   "bin":100, "xmin":50., "xmax":150},

    "RecoZLead_px":               {"name":"RecoZLead_px",                 "title":"Reco leading Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZLead_py":               {"name":"RecoZLead_py",                 "title":"Reco leading Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZLead_pz":               {"name":"RecoZLead_pz",                 "title":"Reco leading Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZLead_p":                {"name":"RecoZLead_p",                  "title":"Reco leading Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZLead_pt":               {"name":"RecoZLead_pt",                 "title":"Reco leading Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZLead_e":                {"name":"RecoZLead_e",                  "title":"Reco leading Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZLead_eta":              {"name":"RecoZLead_eta",                "title":"Reco leading Z daughter #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZLead_phi":              {"name":"RecoZLead_phi",                "title":"Reco leading Z daughter #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZLead_theta":            {"name":"RecoZLead_theta",              "title":"Reco leading Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZLead_y":                {"name":"RecoZLead_y",                  "title":"Reco leading Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZLead_mass":             {"name":"RecoZLead_mass",               "title":"Reco leading Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},

    "RecoZSub_px":                {"name":"RecoZSub_px",                 "title":"Reco subleading Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZSub_py":                {"name":"RecoZSub_py",                 "title":"Reco subleading Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZSub_pz":                {"name":"RecoZSub_pz",                 "title":"Reco subleading Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZSub_p":                 {"name":"RecoZSub_p",                  "title":"Reco subleading Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZSub_pt":                {"name":"RecoZSub_pt",                 "title":"Reco subleading Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZSub_e":                 {"name":"RecoZSub_e",                  "title":"Reco subleading Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZSub_eta":               {"name":"RecoZSub_eta",                "title":"Reco subleading Z daughter #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZSub_phi":               {"name":"RecoZSub_phi",                "title":"Reco subleading Z daughter #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZSub_theta":             {"name":"RecoZSub_theta",              "title":"Reco subleading Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZSub_y":                 {"name":"RecoZSub_y",                  "title":"Reco subleading Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZSub_mass":              {"name":"RecoZSub_mass",               "title":"Reco subleading Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},

    "RecoZP_px":               {"name":"RecoZP_px",                 "title":"Reco positive Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZP_py":               {"name":"RecoZP_py",                 "title":"Reco positive Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZP_pz":               {"name":"RecoZP_pz",                 "title":"Reco positive Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZP_p":                {"name":"RecoZP_p",                  "title":"Reco positive Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZP_pt":               {"name":"RecoZP_pt",                 "title":"Reco positive Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZP_e":                {"name":"RecoZP_e",                  "title":"Reco positive Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZP_eta":              {"name":"RecoZP_eta",                "title":"Reco positive Z daughter #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZP_phi":              {"name":"RecoZP_phi",                "title":"Reco positive Z daughter #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZP_theta":            {"name":"RecoZP_theta",              "title":"Reco positive Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZP_y":                {"name":"RecoZP_y",                  "title":"Reco positive Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZP_mass":             {"name":"RecoZP_mass",               "title":"Reco positive Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},

    "RecoZM_px":                {"name":"RecoZM_px",                 "title":"Reco negative Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZM_py":                {"name":"RecoZM_py",                 "title":"Reco negative Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZM_pz":                {"name":"RecoZM_pz",                 "title":"Reco negative Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZM_p":                 {"name":"RecoZM_p",                  "title":"Reco negative Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZM_pt":                {"name":"RecoZM_pt",                 "title":"Reco negative Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZM_e":                 {"name":"RecoZM_e",                  "title":"Reco negative Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZM_eta":               {"name":"RecoZM_eta",                "title":"Reco negative Z daughter #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZM_phi":               {"name":"RecoZM_phi",                "title":"Reco negative Z daughter #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZM_theta":             {"name":"RecoZM_theta",              "title":"Reco negative Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZM_y":                 {"name":"RecoZM_y",                  "title":"Reco negative Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZM_mass":              {"name":"RecoZM_mass",               "title":"Reco negative Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},
                                
    "RecoH_px":                 {"name":"RecoH_px",                 "title":"Reco H p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_py":                 {"name":"RecoH_py",                 "title":"Reco H p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_pz":                 {"name":"RecoH_pz",                 "title":"Reco H p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_p":                  {"name":"RecoH_p",                  "title":"Reco H p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_pt":                 {"name":"RecoH_pt",                 "title":"Reco H p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_e":                  {"name":"RecoH_e",                  "title":"Reco H energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_eta":                {"name":"RecoH_eta",                "title":"Reco H #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_phi":                {"name":"RecoH_phi",                "title":"Reco H #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_theta":              {"name":"RecoH_theta",              "title":"Reco H #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoH_y":                  {"name":"RecoH_y",                  "title":"Reco H rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoH_mass":               {"name":"RecoH_mass",               "title":"Reco H mass",                   "bin":75, "xmin":0 ,"xmax":150},

    "TauLead_px":               {"name":"TauLead_px",                 "title":"#tau_{leading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_py":               {"name":"TauLead_py",                 "title":"#tau_{leading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_pz":               {"name":"TauLead_pz",                 "title":"#tau_{leading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_p":                {"name":"TauLead_p",                  "title":"#tau_{leading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_pt":               {"name":"TauLead_pt",                 "title":"#tau_{leading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_e":                {"name":"TauLead_e",                  "title":"#tau_{leading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauLead_eta":              {"name":"TauLead_eta",                "title":"#tau_{leading} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_phi":              {"name":"TauLead_phi",                "title":"#tau_{leading} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_theta":            {"name":"TauLead_theta",              "title":"#tau_{leading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauLead_y":                {"name":"TauLead_y",                  "title":"#tau_{leading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauLead_mass":             {"name":"TauLead_mass",               "title":"#tau_{leading} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauSub_px":                {"name":"TauSub_px",                 "title":"#tau_{subleading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_py":                {"name":"TauSub_py",                 "title":"#tau_{subleading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_pz":                {"name":"TauSub_pz",                 "title":"#tau_{subleading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_p":                 {"name":"TauSub_p",                  "title":"#tau_{subleading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_pt":                {"name":"TauSub_pt",                 "title":"#tau_{subleading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_e":                 {"name":"TauSub_e",                  "title":"#tau_{subleading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauSub_eta":               {"name":"TauSub_eta",                "title":"#tau_{subleading} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_phi":               {"name":"TauSub_phi",                "title":"#tau_{subleading} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_theta":             {"name":"TauSub_theta",              "title":"#tau_{subleading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauSub_y":                 {"name":"TauSub_y",                  "title":"#tau_{subleading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauSub_mass":              {"name":"TauSub_mass",               "title":"#tau_{subleading} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauP_px":               {"name":"TauP_px",                 "title":"#tau^{+} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauP_py":               {"name":"TauP_py",                 "title":"#tau^{+} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauP_pz":               {"name":"TauP_pz",                 "title":"#tau^{+} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauP_p":                {"name":"TauP_p",                  "title":"#tau^{+} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauP_pt":               {"name":"TauP_pt",                 "title":"#tau^{+} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauP_e":                {"name":"TauP_e",                  "title":"#tau^{+} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauP_eta":              {"name":"TauP_eta",                "title":"#tau^{+} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauP_phi":              {"name":"TauP_phi",                "title":"#tau^{+} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauP_theta":            {"name":"TauP_theta",              "title":"#tau^{+} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauP_y":                {"name":"TauP_y",                  "title":"#tau^{+} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauP_mass":             {"name":"TauP_mass",               "title":"#tau^{+} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauM_px":                {"name":"TauM_px",                 "title":"#tau^{-} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauM_py":                {"name":"TauM_py",                 "title":"#tau^{-} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauM_pz":                {"name":"TauM_pz",                 "title":"#tau^{-} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauM_p":                 {"name":"TauM_p",                  "title":"#tau^{-} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauM_pt":                {"name":"TauM_pt",                 "title":"#tau^{-} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauM_e":                 {"name":"TauM_e",                  "title":"#tau^{-} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauM_eta":               {"name":"TauM_eta",                "title":"#tau^{-} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauM_phi":               {"name":"TauM_phi",                "title":"#tau^{-} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauM_theta":             {"name":"TauM_theta",              "title":"#tau^{-} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauM_y":                 {"name":"TauM_y",                  "title":"#tau^{-} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauM_mass":              {"name":"TauM_mass",               "title":"#tau^{-} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "Tau_DPhi":         {"name":"Tau_DPhi",           "title":"#Delta#phi(#tau#tau)",                "bin":32, "xmin":-3.2,"xmax":3.2},
    "Tau_DR":                   {"name":"Tau_DR",                     "title":"#Delta R(#tau#tau)",                  "bin":70, "xmin":0,"xmax":7},
    "Tau_cos":                  {"name":"Tau_cos",                    "title":"cos#theta(#tau#tau)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "Tau_DEta":                             {"name":"Tau_DEta",           "title":"Reco di-#tau #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "RecoZDaughter_DPhi":         {"name":"RecoZDaughter_DPhi",           "title":"#Delta#phi(ll)",                "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZDaughter_DR":                   {"name":"RecoZDaughter_DR",                     "title":"#Delta R(ll)",                  "bin":70, "xmin":0,"xmax":7},
    "RecoZDaughter_cos":                  {"name":"RecoZDaughter_cos",                    "title":"cos#theta(ll)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "RecoZDaughter_DEta":                   {"name":"RecoZDaughter_DEta",           "title":"Reco Z daughters #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "Recoil":                   {"name":"Recoil",                   "title":"M_{recoil} [GeV]",                     "bin":80, "xmin":80., "xmax":160.},
    "Collinear_mass":           {"name":"Collinear_mass",           "title":"M_{collinear} [GeV]",                  "bin":150, "xmin":50., "xmax":200.},

    #### CP variables

    "Tau_DEta_y":                             {"name":"Tau_DEta_y",           "title":"Reco di-#tau #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "Tau_DPhi_y":                           {"name":"Tau_DPhi_y",           "title":"#Delta#phi(#tau#tau)",                "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZDaughter_DEta_y":                 {"name":"RecoZDaughter_DEta_y",           "title":"Reco Z daughters #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZDaughter_DPhi_y":                 {"name":"RecoZDaughter_DPhi_y",           "title":"Reco Z daughters #Delta#phi",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "HRF_TauLead_px":                 {"name":"HRF_TauLead_px",                 "title":"Reco #tau_{fing} p_{x} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauLead_py":                 {"name":"HRF_TauLead_py",                 "title":"Reco #tau_{leading} p_{y} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauLead_pz":                 {"name":"HRF_TauLead_pz",                 "title":"Reco #tau_{leading} p_{z} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauLead_p":                  {"name":"HRF_TauLead_p",                  "title":"Reco #tau_{leading} p [GeV] in H rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauLead_pt":                 {"name":"HRF_TauLead_pt",                 "title":"Reco #tau_{leading} p_{T} [GeV] in H rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauLead_e":                  {"name":"HRF_TauLead_e",                  "title":"Reco #tau_{leading} energy [GeV] in H rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauLead_eta":                {"name":"HRF_TauLead_eta",                "title":"Reco #tau_{leading} #eta in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauLead_phi":                {"name":"HRF_TauLead_phi",                "title":"Reco #tau_{leading} #phi in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauLead_theta":              {"name":"HRF_TauLead_theta",              "title":"Reco #tau_{leading} #theta in H rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "HRF_TauLead_y":                  {"name":"HRF_TauLead_y",                  "title":"Reco #tau_{leading} rapidity in H rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "HRF_TauSub_px":                 {"name":"HRF_TauSub_px",                 "title":"Reco #tau_{subleading} p_{x} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauSub_py":                 {"name":"HRF_TauSub_py",                 "title":"Reco #tau_{subleading} p_{y} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauSub_pz":                 {"name":"HRF_TauSub_pz",                 "title":"Reco #tau_{subleading} p_{z} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauSub_p":                  {"name":"HRF_TauSub_p",                  "title":"Reco #tau_{subleading} p [GeV] in H rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauSub_pt":                 {"name":"HRF_TauSub_pt",                 "title":"Reco #tau_{subleading} p_{T} [GeV] in H rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauSub_e":                  {"name":"HRF_TauSub_e",                  "title":"Reco #tau_{subleading} energy [GeV] in H rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauSub_eta":                {"name":"HRF_TauSub_eta",                "title":"Reco #tau_{subleading} #eta in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauSub_phi":                {"name":"HRF_TauSub_phi",                "title":"Reco #tau_{subleading} #phi in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauSub_theta":              {"name":"HRF_TauSub_theta",              "title":"Reco #tau_{subleading} #theta in H rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "HRF_TauSub_y":                  {"name":"HRF_TauSub_y",                  "title":"Reco #tau_{subleading} rapidity in H rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "HRF_TauP_px":                 {"name":"HRF_TauP_px",                 "title":"Reco #tau^{+} p_{x} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauP_py":                 {"name":"HRF_TauP_py",                 "title":"Reco #tau^{+} p_{y} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauP_pz":                 {"name":"HRF_TauP_pz",                 "title":"Reco #tau^{+} p_{z} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauP_p":                  {"name":"HRF_TauP_p",                  "title":"Reco #tau^{+} p [GeV] in H rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauP_pt":                 {"name":"HRF_TauP_pt",                 "title":"Reco #tau^{+} p_{T} [GeV] in H rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauP_e":                  {"name":"HRF_TauP_e",                  "title":"Reco #tau^{+} energy [GeV] in H rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauP_eta":                {"name":"HRF_TauP_eta",                "title":"Reco #tau^{+} #eta in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauP_phi":                {"name":"HRF_TauP_phi",                "title":"Reco #tau^{+} #phi in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauP_theta":              {"name":"HRF_TauP_theta",              "title":"Reco #tau^{+} #theta in H rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "HRF_TauP_y":                  {"name":"HRF_TauP_y",                  "title":"Reco #tau^{+} rapidity in H rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "HRF_TauM_px":                 {"name":"HRF_TauM_px",                 "title":"Reco #tau^{-} p_{x} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauM_py":                 {"name":"HRF_TauM_py",                 "title":"Reco #tau^{-} p_{y} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauM_pz":                 {"name":"HRF_TauM_pz",                 "title":"Reco #tau^{-} p_{z} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_TauM_p":                  {"name":"HRF_TauM_p",                  "title":"Reco #tau^{-} p [GeV] in H rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauM_pt":                 {"name":"HRF_TauM_pt",                 "title":"Reco #tau^{-} p_{T} [GeV] in H rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauM_e":                  {"name":"HRF_TauM_e",                  "title":"Reco #tau^{-} energy [GeV] in H rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "HRF_TauM_eta":                {"name":"HRF_TauM_eta",                "title":"Reco #tau^{-} #eta in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauM_phi":                {"name":"HRF_TauM_phi",                "title":"Reco #tau^{-} #phi in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_TauM_theta":              {"name":"HRF_TauM_theta",              "title":"Reco #tau^{-} #theta in H rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "HRF_TauM_y":                  {"name":"HRF_TauM_y",                  "title":"Reco #tau^{-} rapidity in H rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "HRF_Tau_DEta":                   {"name":"HRF_Tau_DEta",           "title":"Reco di-#tau #Delta#eta in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_Tau_DPhi":           {"name":"HRF_Tau_DPhi",           "title":"Reco di-#tau #Delta#phi in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_Tau_DEta_y":                   {"name":"HRF_Tau_DEta_y",           "title":"Reco di-#tau #Delta#eta in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_Tau_DPhi_y":           {"name":"HRF_Tau_DPhi_y",           "title":"Reco di-#tau #Delta#phi in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "ZRF_RecoZLead_px":                 {"name":"ZRF_RecoZLead_px",                 "title":"Reco leading Z daughter p_{x} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZLead_py":                 {"name":"ZRF_RecoZLead_py",                 "title":"Reco leading Z daughter p_{y} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZLead_pz":                 {"name":"ZRF_RecoZLead_pz",                 "title":"Reco leading Z daughter p_{z} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZLead_p":                  {"name":"ZRF_RecoZLead_p",                  "title":"Reco leading Z daughter p [GeV] in Z rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZLead_pt":                 {"name":"ZRF_RecoZLead_pt",                 "title":"Reco leading Z daughter p_{T} [GeV] in Z rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZLead_e":                  {"name":"ZRF_RecoZLead_e",                  "title":"Reco leading Z daughter energy [GeV] in Z rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZLead_eta":                {"name":"ZRF_RecoZLead_eta",                "title":"Reco leading Z daughter #eta in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZLead_phi":                {"name":"ZRF_RecoZLead_phi",                "title":"Reco leading Z daughter #phi in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZLead_theta":              {"name":"ZRF_RecoZLead_theta",              "title":"Reco leading Z daughter #theta in Z rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "ZRF_RecoZLead_y":                  {"name":"ZRF_RecoZLead_y",                  "title":"Reco leading Z daughter rapidity in Z rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "ZRF_RecoZSub_px":                 {"name":"ZRF_RecoZSub_px",                 "title":"Reco subleading Z daughter p_{x} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZSub_py":                 {"name":"ZRF_RecoZSub_py",                 "title":"Reco subleading Z daughter p_{y} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZSub_pz":                 {"name":"ZRF_RecoZSub_pz",                 "title":"Reco subleading Z daughter p_{z} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZSub_p":                  {"name":"ZRF_RecoZSub_p",                  "title":"Reco subleading Z daughter p [GeV] in Z rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZSub_pt":                 {"name":"ZRF_RecoZSub_pt",                 "title":"Reco subleading Z daughter p_{T} [GeV] in Z rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZSub_e":                  {"name":"ZRF_RecoZSub_e",                  "title":"Reco subleading Z daughter energy [GeV] in Z rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZSub_eta":                {"name":"ZRF_RecoZSub_eta",                "title":"Reco subleading Z daughter #eta in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZSub_phi":                {"name":"ZRF_RecoZSub_phi",                "title":"Reco subleading Z daughter #phi in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZSub_theta":              {"name":"ZRF_RecoZSub_theta",              "title":"Reco subleading Z daughter #theta in Z rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "ZRF_RecoZSub_y":                  {"name":"ZRF_RecoZSub_y",                  "title":"Reco subleading Z daughter rapidity in Z rest frame",               "bin":40, "xmin":-4., "xmax":4.},
    
    "ZRF_RecoZP_px":                 {"name":"ZRF_RecoZP_px",                 "title":"Reco positive Z daughter p_{x} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZP_py":                 {"name":"ZRF_RecoZP_py",                 "title":"Reco positive Z daughter p_{y} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZP_pz":                 {"name":"ZRF_RecoZP_pz",                 "title":"Reco positive Z daughter p_{z} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZP_p":                  {"name":"ZRF_RecoZP_p",                  "title":"Reco positive Z daughter p [GeV] in Z rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZP_pt":                 {"name":"ZRF_RecoZP_pt",                 "title":"Reco positive Z daughter p_{T} [GeV] in Z rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZP_e":                  {"name":"ZRF_RecoZP_e",                  "title":"Reco positive Z daughter energy [GeV] in Z rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZP_eta":                {"name":"ZRF_RecoZP_eta",                "title":"Reco positive Z daughter #eta in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZP_phi":                {"name":"ZRF_RecoZP_phi",                "title":"Reco positive Z daughter #phi in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZP_theta":              {"name":"ZRF_RecoZP_theta",              "title":"Reco positive Z daughter #theta in Z rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "ZRF_RecoZP_y":                  {"name":"ZRF_RecoZP_y",                  "title":"Reco positive Z daughter rapidity in Z rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "ZRF_RecoZM_px":                 {"name":"ZRF_RecoZM_px",                 "title":"Reco negative Z daughter p_{x} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZM_py":                 {"name":"ZRF_RecoZM_py",                 "title":"Reco negative Z daughter p_{y} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZM_pz":                 {"name":"ZRF_RecoZM_pz",                 "title":"Reco negative Z daughter p_{z} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZM_p":                  {"name":"ZRF_RecoZM_p",                  "title":"Reco negative Z daughter p [GeV] in Z rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZM_pt":                 {"name":"ZRF_RecoZM_pt",                 "title":"Reco negative Z daughter p_{T} [GeV] in Z rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZM_e":                  {"name":"ZRF_RecoZM_e",                  "title":"Reco negative Z daughter energy [GeV] in Z rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZM_eta":                {"name":"ZRF_RecoZM_eta",                "title":"Reco negative Z daughter #eta in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZM_phi":                {"name":"ZRF_RecoZM_phi",                "title":"Reco negative Z daughter #phi in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZM_theta":              {"name":"ZRF_RecoZM_theta",              "title":"Reco negative Z daughter #theta in Z rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "ZRF_RecoZM_y":                  {"name":"ZRF_RecoZM_y",                  "title":"Reco negative Z daughter rapidity in Z rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "ZRF_RecoZDaughter_DEta":                   {"name":"ZRF_RecoZDaughter_DEta",           "title":"Reco Z daughters #Delta#eta in Z rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZDaughter_DPhi":           {"name":"ZRF_RecoZDaughter_DPhi",           "title":"Reco Z daughters #Delta#phi in Z rest frame",          "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZDaughter_DEta_y":                   {"name":"ZRF_RecoZDaughter_DEta_y",           "title":"Reco Z daughters #Delta#eta in Z rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZDaughter_DPhi_y":           {"name":"ZRF_RecoZDaughter_DPhi_y",           "title":"Reco Z daughters #Delta#phi in Z rest frame",          "bin":32, "xmin":-3.2,"xmax":3.2},

    "RecoThetastar":           {"name":"RecoThetastar",         "title":"Reco #theta^{*}",                  "bin":32, "xmin":0,"xmax":3.2},
    "RecoTheta2":              {"name":"RecoTheta2",            "title":"Reco #theta_{2}",                  "bin":32, "xmin":0,"xmax":3.2},
    "RecoPhi1":                {"name":"RecoPhi1",              "title":"Reco #phi_{1}",                    "bin":32, "xmin":0,"xmax":3.2},
    "RecoPhi":                 {"name":"RecoPhi",               "title":"Reco #phi",                        "bin":32, "xmin":0,"xmax":3.2},
    "RecoTheta1":              {"name":"RecoTheta1",            "title":"Reco #theta_{1}",                  "bin":32, "xmin":0,"xmax":3.2},

    "RecoThetastar_cos":           {"name":"RecoThetastar_cos",         "title":"Reco cos#theta^{*}",                  "bin":50, "xmin":-1.,"xmax":1.},
    "RecoTheta2_cos":              {"name":"RecoTheta2_cos",            "title":"Reco cos#theta_{2}",                  "bin":50, "xmin":-1.,"xmax":1.},
    "RecoPhi1_cos":                {"name":"RecoPhi1_cos",              "title":"Reco cos#phi_{1}",                    "bin":50, "xmin":-1.,"xmax":1.},
    "RecoPhi_cos":                 {"name":"RecoPhi_cos",               "title":"Reco cos#phi",                        "bin":50, "xmin":-1.,"xmax":1.},
    "RecoTheta1_cos":              {"name":"RecoTheta1_cos",            "title":"Reco cos#theta_{1}",                  "bin":50, "xmin":-1.,"xmax":1.},

}
