#Input directory where the files produced at the stage1 level are
inputDir = "/ceph/sgiappic/HiggsCP/CPReco/stage2_explicit_new/"

#Optional: output directory, default is local running directory
outputDir = "/ceph/sgiappic/HiggsCP/CPReco/final_explicit_new/"

#Integrated luminosity for scaling number of events (required only if setting doScale to true)
intLumi = 10.8e6 #pb^-1 #to be checked again for 240 gev

#Scale event yields by intLumi and cross section (optional)
# if scaling, both the number of events in the table and in the histograms will be scaled
doScale = True

#Save event yields in a table (optional)
saveTabular = True

#Number of CPUs to use
nCPUS = 4

#produces ROOT TTrees, default is False
doTree = False

#Mandatory: List of processes
processList = {
    #'noISR_e+e-_noCuts_EWonly':{},
    #'noISR_e+e-_noCuts_cehim_m1':{},
    #'noISR_e+e-_noCuts_cehim_p1':{},
    #'noISR_e+e-_noCuts_cehre_m1':{},
    #'noISR_e+e-_noCuts_cehre_p1':{},
    
    #'EWonly_taudecay_2Pi2Nu':{},
    #'cehim_m1_taudecay_2Pi2Nu':{},
    #'cehim_p1_taudecay_2Pi2Nu':{},
    #'cehre_m1_taudecay_2Pi2Nu':{},
    #'cehre_p1_taudecay_2Pi2Nu':{},

    #'cehim_m5_taudecay_2Pi2Nu':{},
    #'cehim_p5_taudecay_2Pi2Nu':{},
    #'cehre_m5_taudecay_2Pi2Nu':{},
    #'cehre_p5_taudecay_2Pi2Nu':{},

    #'EWonly_taudecay_PiPi0Nu':{},
    #'cehim_m1_taudecay_PiPi0Nu':{},
    #'cehim_p1_taudecay_PiPi0Nu':{},
    #'cehre_m1_taudecay_PiPi0Nu':{},
    #'cehre_p1_taudecay_PiPi0Nu':{},

    "e+e-_qqH_H2Pi2Nu":{},

    #'cehim_p0p1_taudecay_2Pi2Nu':{},
    #'cehim_m0p1_taudecay_2Pi2Nu':{},
    #'cehre_m0p1_taudecay_2Pi2Nu':{},
    #'cehre_p0p1_taudecay_2Pi2Nu':{},
    #'cehim_p10_taudecay_2Pi2Nu':{},
    #'cehim_m10_taudecay_2Pi2Nu':{},

    #'cehim_m2_taudecay_2Pi2Nu':{},
    #'cehim_p2_taudecay_2Pi2Nu':{},
    #'cehre_m2_taudecay_2Pi2Nu':{},
    #'cehre_p2_taudecay_2Pi2Nu':{},

    #'wzp6_ee_eeH_Htautau_ecm240': {},
}
###Dictionary for prettier names of processes (optional)
#change them if you want but they don't do anything
processLabels = {}

#Link to the dictonary that contains all the cross section information etc...
procDict = "FCCee_procDict_winter2023_IDEA.json"

#Add provate samples as it is not an offical process
procDictAdd = {
    'noISR_e+e-_noCuts_EWonly':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051559935862, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehim_m1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051749741618, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehim_p1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051749741618, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehre_m1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00058001482393, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehre_p1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00045498699833000005, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR':{"numberOfEvents": 50000, "sumOfWeights": 50000, "crossSection": 0.00051559935862, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'taudecay':{"numberOfEvents": 10000, "sumOfWeights": 10000, "crossSection": 0.00051559935862, "kfactor": 1.0, "matchingEfficiency": 1.0},
    "wzp6_ee_eeH_Htautau_ecm240": {"numberOfEvents": 400000, "sumOfWeights": 400000.0, "crossSection": 0.0004491, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'EWonly_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.778120325123597e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_m1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.8024289951161206e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_p1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.797985627446233e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_m1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 6.499955724499168e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_p1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.098765393810636e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_m5_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 6.310726805739835e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_p5_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 6.302421755280696e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_m5_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 9.812070492389316e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_p5_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 2.8061186713438668e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_m2_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.8623334845172226e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_p2_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.8639785901564145e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_m2_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 7.264271533677142e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_p2_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 4.461910656050512e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_p0p1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.777551779024773e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_m0p1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.778338822008795e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_m0p1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.8484197952269994e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_p0p1_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.708301892822401e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_p10_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 7.89816811069392e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_m10_taudecay_2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 7.89562565428267e-06, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'EWonly_taudecay_PiPi0Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 2.839033691284505e-05, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_m1_taudecay_PiPi0Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 2.8451232342224154e-05, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehim_p1_taudecay_PiPi0Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 2.846975057236473e-05, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_m1_taudecay_PiPi0Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 3.193361184321185e-05, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'cehre_p1_taudecay_PiPi0Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 2.5052618455527882e-05, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'e+e-_qqH_H2Pi2Nu':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 5.674e-05, "kfactor": 1.0, "matchingEfficiency": 1.0},


}

###Dictionnay of the list of cuts. The key is the name of the selection that will be added to the output file
cutList = {
    ### no selection, just builds the histograms, it will not be shown in the latex table
    "selReco_ILC20chi": "ILC_Filter==1 && KinILC_chi2<20",
    "selReco_CMS":"true",
}

# Dictionary for prettier names of cuts (optional)
### needs to be in the same order as cutList or the table won't be organised well, it's only for the table ###
cutLabels = {}

###Dictionary for the ouput variable/hitograms. The key is the name of the variable in the output files. "name" is the name of the variable in the input file, "title" is the x-axis label of the histogram, "bin" the number of bins of the histogram, "xmin" the minimum x-axis value and "xmax" the maximum x-axis value.
histoList = {
    ######## Reconstructed particles #######

    "n_RecoElectrons":                  {"name":"n_RecoElectrons",                  "title":"Number of reco electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_e":                   {"name":"RecoElectron_e",                   "title":"Reco electron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_p":                   {"name":"RecoElectron_p",                   "title":"Reco electron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_pt":                  {"name":"RecoElectron_pt",                  "title":"Reco electron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_px":                  {"name":"RecoElectron_px",                  "title":"Reco electron p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_py":                  {"name":"RecoElectron_py",                  "title":"Reco electron p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_pz":                  {"name":"RecoElectron_pz",                  "title":"Reco electron p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_y":                   {"name":"RecoElectron_y",                   "title":"Reco electron rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_eta":                 {"name":"RecoElectron_eta",                 "title":"Reco electron #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoElectron_theta":               {"name":"RecoElectron_theta",               "title":"Reco electron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_phi":                 {"name":"RecoElectron_phi",                 "title":"Reco electron #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoElectron_charge":              {"name":"RecoElectron_charge",              "title":"Reco electron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_mass":                {"name":"RecoElectron_mass",                "title":"Reco electron mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_absD0":          {"name":"RecoElectronTrack_absD0",          "title":"Reco electron tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absZ0":          {"name":"RecoElectronTrack_absZ0",          "title":"Reco electron tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absD0sig":       {"name":"RecoElectronTrack_absD0sig",       "title":"Reco electron tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_absZ0sig":       {"name":"RecoElectronTrack_absZ0sig",       "title":"Reco electron tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_D0cov":          {"name":"RecoElectronTrack_D0cov",          "title":"Reco electron tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_Z0cov":          {"name":"RecoElectronTrack_Z0cov",          "title":"Reco electron tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoElectrons_sel":                  {"name":"n_RecoElectrons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_sel_e":                   {"name":"RecoElectron_sel_e",                   "title":"Reco electron isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_p":                   {"name":"RecoElectron_sel_p",                   "title":"Reco electron isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_pt":                  {"name":"RecoElectron_sel_pt",                  "title":"Reco electron isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_px":                  {"name":"RecoElectron_sel_px",                  "title":"Reco electron isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_py":                  {"name":"RecoElectron_sel_py",                  "title":"Reco electron isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_pz":                  {"name":"RecoElectron_sel_pz",                  "title":"Reco electron isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_y":                   {"name":"RecoElectron_sel_y",                   "title":"Reco electron isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_sel_eta":                 {"name":"RecoElectron_sel_eta",                 "title":"Reco electron isolated #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoElectron_sel_theta":               {"name":"RecoElectron_sel_theta",               "title":"Reco electron isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_sel_phi":                 {"name":"RecoElectron_sel_phi",                 "title":"Reco electron isolated #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoElectron_sel_charge":              {"name":"RecoElectron_sel_charge",              "title":"Reco electron isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_sel_mass":                {"name":"RecoElectron_sel_mass",                "title":"Reco electron isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_sel_absD0":          {"name":"RecoElectronTrack_sel_absD0",          "title":"Reco electron isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absZ0":          {"name":"RecoElectronTrack_sel_absZ0",          "title":"Reco electron isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absD0sig":       {"name":"RecoElectronTrack_sel_absD0sig",       "title":"Reco electron isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_absZ0sig":       {"name":"RecoElectronTrack_sel_absZ0sig",       "title":"Reco electron isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_D0cov":          {"name":"RecoElectronTrack_sel_D0cov",          "title":"Reco electron isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_sel_Z0cov":          {"name":"RecoElectronTrack_sel_Z0cov",          "title":"Reco electron isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons":                  {"name":"n_RecoMuons",                  "title":"Number of reco muons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_e":                   {"name":"RecoMuon_e",                   "title":"Reco muon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_p":                   {"name":"RecoMuon_p",                   "title":"Reco muon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_pt":                  {"name":"RecoMuon_pt",                  "title":"Reco muon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_px":                  {"name":"RecoMuon_px",                  "title":"Reco muon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_py":                  {"name":"RecoMuon_py",                  "title":"Reco muon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_pz":                  {"name":"RecoMuon_pz",                  "title":"Reco muon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_y":                   {"name":"RecoMuon_y",                   "title":"Reco muon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_eta":                 {"name":"RecoMuon_eta",                 "title":"Reco muon #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoMuon_theta":               {"name":"RecoMuon_theta",               "title":"Reco muon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_phi":                 {"name":"RecoMuon_phi",                 "title":"Reco muon #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoMuon_charge":              {"name":"RecoMuon_charge",              "title":"Reco muon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_mass":                {"name":"RecoMuon_mass",                "title":"Reco muon mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_absD0":          {"name":"RecoMuonTrack_absD0",          "title":"Reco muon tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absZ0":          {"name":"RecoMuonTrack_absZ0",          "title":"Reco muon tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absD0sig":       {"name":"RecoMuonTrack_absD0sig",       "title":"Reco muon tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_absZ0sig":       {"name":"RecoMuonTrack_absZ0sig",       "title":"Reco muon tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_D0cov":          {"name":"RecoMuonTrack_D0cov",          "title":"Reco muon tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_Z0cov":          {"name":"RecoMuonTrack_Z0cov",          "title":"Reco muon tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons_sel":                  {"name":"n_RecoMuons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_sel_e":                   {"name":"RecoMuon_sel_e",                   "title":"Reco muon isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_p":                   {"name":"RecoMuon_sel_p",                   "title":"Reco muon isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_pt":                  {"name":"RecoMuon_sel_pt",                  "title":"Reco muon isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_px":                  {"name":"RecoMuon_sel_px",                  "title":"Reco muon isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_py":                  {"name":"RecoMuon_sel_py",                  "title":"Reco muon isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_pz":                  {"name":"RecoMuon_sel_pz",                  "title":"Reco muon isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_y":                   {"name":"RecoMuon_sel_y",                   "title":"Reco muon isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_sel_eta":                 {"name":"RecoMuon_sel_eta",                 "title":"Reco muon isolated #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoMuon_sel_theta":               {"name":"RecoMuon_sel_theta",               "title":"Reco muon isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_sel_phi":                 {"name":"RecoMuon_sel_phi",                 "title":"Reco muon isolated #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoMuon_sel_charge":              {"name":"RecoMuon_sel_charge",              "title":"Reco muon isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_sel_mass":                {"name":"RecoMuon_sel_mass",                "title":"Reco muon isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_sel_absD0":          {"name":"RecoMuonTrack_sel_absD0",          "title":"Reco muon isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absZ0":          {"name":"RecoMuonTrack_sel_absZ0",          "title":"Reco muon isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absD0sig":       {"name":"RecoMuonTrack_sel_absD0sig",       "title":"Reco muon isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_absZ0sig":       {"name":"RecoMuonTrack_sel_absZ0sig",       "title":"Reco muon isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_D0cov":          {"name":"RecoMuonTrack_sel_D0cov",          "title":"Reco muon isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_sel_Z0cov":          {"name":"RecoMuonTrack_sel_Z0cov",          "title":"Reco muon isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons":                {"name":"n_RecoLeptons",                  "title":"Number of reco leptons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoLepton_e":                 {"name":"RecoLepton_e",                   "title":"Reco lepton energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_p":                 {"name":"RecoLepton_p",                   "title":"Reco lepton p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_pt":                {"name":"RecoLepton_pt",                  "title":"Reco lepton p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_px":                {"name":"RecoLepton_px",                  "title":"Reco lepton p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_py":                {"name":"RecoLepton_py",                  "title":"Reco lepton p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_pz":                {"name":"RecoLepton_pz",                  "title":"Reco lepton p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_y":                 {"name":"RecoLepton_y",                   "title":"Reco lepton rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_eta":               {"name":"RecoLepton_eta",                 "title":"Reco lepton #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoLepton_theta":             {"name":"RecoLepton_theta",               "title":"Reco lepton #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_phi":               {"name":"RecoLepton_phi",                 "title":"Reco lepton #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoLepton_charge":            {"name":"RecoLepton_charge",              "title":"Reco lepton charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_mass":              {"name":"RecoLepton_mass",                "title":"Reco lepton mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_absD0":        {"name":"RecoLeptonTrack_absD0",          "title":"Reco lepton tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absZ0":        {"name":"RecoLeptonTrack_absZ0",          "title":"Reco lepton tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absD0sig":     {"name":"RecoLeptonTrack_absD0sig",       "title":"Reco lepton tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_absZ0sig":     {"name":"RecoLeptonTrack_absZ0sig",       "title":"Reco lepton tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_D0cov":        {"name":"RecoLeptonTrack_D0cov",          "title":"Reco lepton tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_Z0cov":        {"name":"RecoLeptonTrack_Z0cov",          "title":"Reco lepton tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons_sel":                {"name":"n_RecoLeptons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.},
    "RecoLepton_sel_e":                 {"name":"RecoLepton_sel_e",                   "title":"Reco lepton isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_p":                 {"name":"RecoLepton_sel_p",                   "title":"Reco lepton isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_pt":                {"name":"RecoLepton_sel_pt",                  "title":"Reco lepton isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_px":                {"name":"RecoLepton_sel_px",                  "title":"Reco lepton isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_py":                {"name":"RecoLepton_sel_py",                  "title":"Reco lepton isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_pz":                {"name":"RecoLepton_sel_pz",                  "title":"Reco lepton isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_y":                 {"name":"RecoLepton_sel_y",                   "title":"Reco lepton isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_sel_eta":               {"name":"RecoLepton_sel_eta",                 "title":"Reco lepton isolated #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoLepton_sel_theta":             {"name":"RecoLepton_sel_theta",               "title":"Reco lepton isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_sel_phi":               {"name":"RecoLepton_sel_phi",                 "title":"Reco lepton isolated #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoLepton_sel_charge":            {"name":"RecoLepton_sel_charge",              "title":"Reco lepton isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_sel_mass":              {"name":"RecoLepton_sel_mass",                "title":"Reco lepton isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_sel_absD0":        {"name":"RecoLeptonTrack_sel_absD0",          "title":"Reco lepton isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absZ0":        {"name":"RecoLeptonTrack_sel_absZ0",          "title":"Reco lepton isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absD0sig":     {"name":"RecoLeptonTrack_sel_absD0sig",       "title":"Reco lepton isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_absZ0sig":     {"name":"RecoLeptonTrack_sel_absZ0sig",       "title":"Reco lepton isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_D0cov":        {"name":"RecoLeptonTrack_sel_D0cov",          "title":"Reco lepton isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_sel_Z0cov":        {"name":"RecoLeptonTrack_sel_Z0cov",          "title":"Reco lepton isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoPhotons":            {"name":"n_RecoPhotons",                  "title":"Number of reco photons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoPhoton_e":             {"name":"RecoPhoton_e",                   "title":"Reco photon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_p":             {"name":"RecoPhoton_p",                   "title":"Reco photon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_pt":            {"name":"RecoPhoton_pt",                  "title":"Reco photon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_px":            {"name":"RecoPhoton_px",                  "title":"Reco photon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_py":            {"name":"RecoPhoton_py",                  "title":"Reco photon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_pz":            {"name":"RecoPhoton_pz",                  "title":"Reco photon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_y":             {"name":"RecoPhoton_y",                   "title":"Reco photon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoPhoton_eta":           {"name":"RecoPhoton_eta",                 "title":"Reco photon #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoPhoton_theta":         {"name":"RecoPhoton_theta",               "title":"Reco photon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoPhoton_phi":           {"name":"RecoPhoton_phi",                 "title":"Reco photon #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoPhoton_charge":        {"name":"RecoPhoton_charge",              "title":"Reco photon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoPhoton_mass":          {"name":"RecoPhoton_mass",              "title":"Reco photon mass",                         "bin":50, "xmin":-1.5,"xmax":1.5},

    "RecoEmiss_px":             {"name":"RecoEmiss_px",                  "title":"Reco missing energy p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_py":             {"name":"RecoEmiss_py",                  "title":"Reco missing energy p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pz":             {"name":"RecoEmiss_pz",                  "title":"Reco missing energy p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pt":             {"name":"RecoEmiss_pt",                  "title":"Reco missing energy p_{T} [GeV]",                    "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_p":              {"name":"RecoEmiss_p",                   "title":"Reco missing energy p [GeV]",                        "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_e":              {"name":"RecoEmiss_e",                   "title":"Reco missing energy energy [GeV]",                   "bin":60,"xmin":0 ,"xmax":240},
    "RecoEmiss_eta":            {"name":"RecoEmiss_eta",                 "title":"Reco missing energy #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_phi":            {"name":"RecoEmiss_phi",                 "title":"Reco missing energy #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_theta":          {"name":"RecoEmiss_theta",               "title":"Reco missing energy #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoEmiss_y":              {"name":"RecoEmiss_y",                   "title":"Reco missing energy rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoEmiss_costheta":       {"name":"RecoEmiss_costheta",               "title":"Reco missing energy |cos(#theta)|",                 "bin":50, "xmin":0,"xmax":1.},

    "TagJet_R5_e":                {"name":"TagJet_R5_e",                   "title":"R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "TagJet_R5_p":                {"name":"TagJet_R5_p",                   "title":"R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_pt":               {"name":"TagJet_R5_pt",                  "title":"R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_px":               {"name":"TagJet_R5_px",                  "title":"R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_py":               {"name":"TagJet_R5_py",                  "title":"R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_pz":               {"name":"TagJet_R5_pz",                  "title":"R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_eta":              {"name":"TagJet_R5_eta",                 "title":"R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_theta":            {"name":"TagJet_R5_theta",               "title":"R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_R5_phi":              {"name":"TagJet_R5_phi",                 "title":"R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_mass":             {"name":"TagJet_R5_mass",                "title":"R5 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_R5_charge":             {"name":"TagJet_R5_charge",                "title":"R5 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_R5":                {"name":"n_TagJet_R5",                   "title":"Number of R5 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_R5_constituents":             {"name":"n_TagJet_R5_constituents",               "title":"R5 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_R5_charged_constituents":             {"name":"n_TagJet_R5_charged_constituents",               "title":"R5 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_R5_neutral_constituents":             {"name":"n_TagJet_R5_neutral_constituents",               "title":"R5 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_R5_isG":             {"name":"TagJet_R5_isG",                "title":"R5 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isU":             {"name":"TagJet_R5_isU",                "title":"R5 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isD":             {"name":"TagJet_R5_isD",                "title":"R5 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isS":             {"name":"TagJet_R5_isS",                "title":"R5 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isC":             {"name":"TagJet_R5_isC",                "title":"R5 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isB":             {"name":"TagJet_R5_isB",                "title":"R5 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isTAU":             {"name":"TagJet_R5_isTAU",                "title":"R5 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_R5_p":          {"name":"TauFromJet_R5_p",                   "title":"#tau from R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_pt":         {"name":"TauFromJet_R5_pt",                  "title":"#tau from R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_px":         {"name":"TauFromJet_R5_px",                  "title":"#tau from R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_py":         {"name":"TauFromJet_R5_py",                  "title":"#tau from R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_pz":         {"name":"TauFromJet_R5_pz",                  "title":"#tau from R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_theta":      {"name":"TauFromJet_R5_theta",               "title":"#tau from R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_R5_phi":        {"name":"TauFromJet_R5_phi",                 "title":"#tau from R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_e":          {"name":"TauFromJet_R5_e",                   "title":"#tau from R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_eta":        {"name":"TauFromJet_R5_eta",                 "title":"#tau from R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_y":          {"name":"TauFromJet_R5_y",                   "title":"#tau from R5 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_R5_charge":     {"name":"TauFromJet_R5_charge",              "title":"#tau from R5 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_R5_type":       {"name":"TauFromJet_R5_type",                "title":"#tau from R5 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_R5_mass":       {"name":"TauFromJet_R5_mass",                "title":"#tau from R5 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_R5":          {"name":"n_TauFromJet_R5",                   "title":"Number of #tau from R5 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_R5_sel_e":            {"name":"TagJet_R5_sel_e",                   "title":"Quark/gluon R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},    
    "TagJet_R5_sel_p":            {"name":"TagJet_R5_sel_p",                   "title":"Quark/gluon R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_sel_pt":           {"name":"TagJet_R5_sel_pt",                  "title":"Quark/gluon R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TagJet_R5_sel_px":           {"name":"TagJet_R5_sel_px",                  "title":"Quark/gluon R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_sel_py":           {"name":"TagJet_R5_sel_py",                  "title":"Quark/gluon R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_sel_pz":           {"name":"TagJet_R5_sel_pz",                  "title":"Quark/gluon R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TagJet_R5_sel_eta":          {"name":"TagJet_R5_sel_eta",                 "title":"Quark/gluon R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_sel_theta":        {"name":"TagJet_R5_sel_theta",               "title":"Quark/gluon R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_R5_sel_phi":          {"name":"TagJet_R5_sel_phi",                 "title":"Quark/gluon R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_sel_mass":         {"name":"TagJet_R5_sel_mass",                "title":"Quark/gluon R5 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_R5_sel":            {"name":"n_TagJet_R5_sel",                   "title":"Number of Quark/gluon R5 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    "n_ChargedTau":            {"name":"n_ChargedTau",                  "title":"Number of reco leading charged particle in explicit R5 tau jets",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "ChargedTau_e":             {"name":"ChargedTau_e",                   "title":"Leading charged particle in explicit R5 tau jets energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "ChargedTau_p":             {"name":"ChargedTau_p",                   "title":"Leading charged particle in explicit R5 tau jets p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "ChargedTau_pt":            {"name":"ChargedTau_pt",                  "title":"Leading charged particle in explicit R5 tau jets p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "ChargedTau_px":            {"name":"ChargedTau_px",                  "title":"Leading charged particle in explicit R5 tau jets p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedTau_py":            {"name":"ChargedTau_py",                  "title":"Leading charged particle in explicit R5 tau jets p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedTau_pz":            {"name":"ChargedTau_pz",                  "title":"Leading charged particle in explicit R5 tau jets p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedTau_eta":           {"name":"ChargedTau_eta",                 "title":"Leading charged particle in explicit R5 tau jets #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "ChargedTau_theta":         {"name":"ChargedTau_theta",               "title":"Leading charged particle in explicit R5 tau jets #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "ChargedTau_phi":           {"name":"ChargedTau_phi",                 "title":"Leading charged particle in explicit R5 tau jets #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "ChargedTau_charge":        {"name":"ChargedTau_charge",              "title":"Leading charged particle in explicit R5 tau jets charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "ChargedTau_mass":          {"name":"ChargedTau_mass",                 "title":"Leading charged particle in explicit R5 tau jets mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "n_NeutralTau":            {"name":"n_NeutralTau",                  "title":"Number of reco neutral system in explicit R5 tau jetss",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "NeutralTau_e":             {"name":"NeutralTau_e",                   "title":"Neutral system in explicit R5 tau jets energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "NeutralTau_p":             {"name":"NeutralTau_p",                   "title":"Neutral system in explicit R5 tau jets p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "NeutralTau_pt":            {"name":"NeutralTau_pt",                  "title":"Neutral system in explicit R5 tau jets p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "NeutralTau_px":            {"name":"NeutralTau_px",                  "title":"Neutral system in explicit R5 tau jets p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralTau_py":            {"name":"NeutralTau_py",                  "title":"Neutral system in explicit R5 tau jets p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralTau_pz":            {"name":"NeutralTau_pz",                  "title":"Neutral system in explicit R5 tau jets p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralTau_eta":           {"name":"NeutralTau_eta",                 "title":"Neutral system in explicit R5 tau jets #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "NeutralTau_theta":         {"name":"NeutralTau_theta",               "title":"Neutral system in explicit R5 tau jets #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "NeutralTau_phi":           {"name":"NeutralTau_phi",                 "title":"Neutral system in explicit R5 tau jets #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "NeutralTau_charge":        {"name":"NeutralTau_charge",              "title":"Neutral system in explicit R5 tau jets charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "NeutralTau_mass":          {"name":"NeutralTau_mass",                 "title":"Neutral system in explicit R5 tau jets mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "n_ChargedJet":            {"name":"n_ChargedJet",                  "title":"Number of reco leading charged particle in tagged R5 tau jets",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "ChargedJet_e":             {"name":"ChargedJet_e",                   "title":"Leading charged particle in tagged R5 tau jets energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "ChargedJet_p":             {"name":"ChargedJet_p",                   "title":"Leading charged particle in tagged R5 tau jets p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "ChargedJet_pt":            {"name":"ChargedJet_pt",                  "title":"Leading charged particle in tagged R5 tau jets p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "ChargedJet_px":            {"name":"ChargedJet_px",                  "title":"Leading charged particle in tagged R5 tau jets p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedJet_py":            {"name":"ChargedJet_py",                  "title":"Leading charged particle in tagged R5 tau jets p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedJet_pz":            {"name":"ChargedJet_pz",                  "title":"Leading charged particle in tagged R5 tau jets p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedJet_eta":           {"name":"ChargedJet_eta",                 "title":"Leading charged particle in tagged R5 tau jets #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "ChargedJet_theta":         {"name":"ChargedJet_theta",               "title":"Leading charged particle in tagged R5 tau jets #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "ChargedJet_phi":           {"name":"ChargedJet_phi",                 "title":"Leading charged particle in tagged R5 tau jets #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "ChargedJet_charge":        {"name":"ChargedJet_charge",              "title":"Leading charged particle in tagged R5 tau jets charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "ChargedJet_mass":          {"name":"ChargedJet_mass",                 "title":"Leading charged particle in tagged R5 tau jets mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "n_NeutralJet":            {"name":"n_NeutralJet",                  "title":"Number of reco neutral system in tagged R5 tau jetss",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "NeutralJet_e":             {"name":"NeutralJet_e",                   "title":"Neutral system in tagged R5 tau jets energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "NeutralJet_p":             {"name":"NeutralJet_p",                   "title":"Neutral system in tagged R5 tau jets p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "NeutralJet_pt":            {"name":"NeutralJet_pt",                  "title":"Neutral system in tagged R5 tau jets p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "NeutralJet_px":            {"name":"NeutralJet_px",                  "title":"Neutral system in tagged R5 tau jets p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralJet_py":            {"name":"NeutralJet_py",                  "title":"Neutral system in tagged R5 tau jets p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralJet_pz":            {"name":"NeutralJet_pz",                  "title":"Neutral system in tagged R5 tau jets p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralJet_eta":           {"name":"NeutralJet_eta",                 "title":"Neutral system in tagged R5 tau jets #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "NeutralJet_theta":         {"name":"NeutralJet_theta",               "title":"Neutral system in tagged R5 tau jets #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "NeutralJet_phi":           {"name":"NeutralJet_phi",                 "title":"Neutral system in tagged R5 tau jets #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "NeutralJet_charge":        {"name":"NeutralJet_charge",              "title":"Neutral system in tagged R5 tau jets charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "NeutralJet_mass":          {"name":"NeutralJet_mass",                 "title":"Neutral system in tagged R5 tau jets mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "n_NeutralHadron":            {"name":"n_NeutralHadron",                  "title":"Number of reco neutral hadron",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "NeutralHadron_e":             {"name":"NeutralHadron_e",                   "title":"Neutral hadron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "NeutralHadron_p":             {"name":"NeutralHadron_p",                   "title":"Neutral hadron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "NeutralHadron_pt":            {"name":"NeutralHadron_pt",                  "title":"Neutral hadron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "NeutralHadron_px":            {"name":"NeutralHadron_px",                  "title":"Neutral hadron p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralHadron_py":            {"name":"NeutralHadron_py",                  "title":"Neutral hadron p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralHadron_pz":            {"name":"NeutralHadron_pz",                  "title":"Neutral hadron p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "NeutralHadron_eta":           {"name":"NeutralHadron_eta",                 "title":"Neutral hadron #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "NeutralHadron_theta":         {"name":"NeutralHadron_theta",               "title":"Neutral hadron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "NeutralHadron_phi":           {"name":"NeutralHadron_phi",                 "title":"Neutral hadron #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "NeutralHadron_charge":        {"name":"NeutralHadron_charge",              "title":"Neutral hadron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "NeutralHadron_mass":          {"name":"NeutralHadron_mass",                 "title":"Neutral hadron mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "n_ChargedHadron":            {"name":"n_ChargedHadron",                  "title":"Number of reco Charged hadron",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "ChargedHadron_e":             {"name":"ChargedHadron_e",                   "title":"Charged hadron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "ChargedHadron_p":             {"name":"ChargedHadron_p",                   "title":"Charged hadron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "ChargedHadron_pt":            {"name":"ChargedHadron_pt",                  "title":"Charged hadron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "ChargedHadron_px":            {"name":"ChargedHadron_px",                  "title":"Charged hadron p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedHadron_py":            {"name":"ChargedHadron_py",                  "title":"Charged hadron p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedHadron_pz":            {"name":"ChargedHadron_pz",                  "title":"Charged hadron p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "ChargedHadron_eta":           {"name":"ChargedHadron_eta",                 "title":"Charged hadron #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "ChargedHadron_theta":         {"name":"ChargedHadron_theta",               "title":"Charged hadron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "ChargedHadron_phi":           {"name":"ChargedHadron_phi",                 "title":"Charged hadron #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "ChargedHadron_charge":        {"name":"ChargedHadron_charge",              "title":"Charged hadron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "ChargedHadron_mass":          {"name":"ChargedHadron_mass",                 "title":"Charged hadron mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},


    ###########################

    "RecoZ_px":                 {"name":"RecoZ_px",                 "title":"Reco Z p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_py":                 {"name":"RecoZ_py",                 "title":"Reco Z p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_pz":                 {"name":"RecoZ_pz",                 "title":"Reco Z p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_p":                  {"name":"RecoZ_p",                  "title":"Reco Z p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_pt":                 {"name":"RecoZ_pt",                 "title":"Reco Z p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_e":                  {"name":"RecoZ_e",                  "title":"Reco Z energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_eta":                {"name":"RecoZ_eta",                "title":"Reco Z #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZ_phi":                {"name":"RecoZ_phi",                "title":"Reco Z #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZ_theta":              {"name":"RecoZ_theta",              "title":"Reco Z #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZ_y":                  {"name":"RecoZ_y",                  "title":"Reco Z rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoZ_mass":               {"name":"RecoZ_mass",               "title":"Reco Z mass",                   "bin":100, "xmin":50., "xmax":150},

    "RecoZLead_px":               {"name":"RecoZLead_px",                 "title":"Reco leading Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZLead_py":               {"name":"RecoZLead_py",                 "title":"Reco leading Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZLead_pz":               {"name":"RecoZLead_pz",                 "title":"Reco leading Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZLead_p":                {"name":"RecoZLead_p",                  "title":"Reco leading Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZLead_pt":               {"name":"RecoZLead_pt",                 "title":"Reco leading Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZLead_e":                {"name":"RecoZLead_e",                  "title":"Reco leading Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZLead_eta":              {"name":"RecoZLead_eta",                "title":"Reco leading Z daughter #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZLead_phi":              {"name":"RecoZLead_phi",                "title":"Reco leading Z daughter #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZLead_theta":            {"name":"RecoZLead_theta",              "title":"Reco leading Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZLead_y":                {"name":"RecoZLead_y",                  "title":"Reco leading Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZLead_mass":             {"name":"RecoZLead_mass",               "title":"Reco leading Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},

    "RecoZSub_px":                {"name":"RecoZSub_px",                 "title":"Reco subleading Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZSub_py":                {"name":"RecoZSub_py",                 "title":"Reco subleading Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZSub_pz":                {"name":"RecoZSub_pz",                 "title":"Reco subleading Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZSub_p":                 {"name":"RecoZSub_p",                  "title":"Reco subleading Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZSub_pt":                {"name":"RecoZSub_pt",                 "title":"Reco subleading Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZSub_e":                 {"name":"RecoZSub_e",                  "title":"Reco subleading Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZSub_eta":               {"name":"RecoZSub_eta",                "title":"Reco subleading Z daughter #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZSub_phi":               {"name":"RecoZSub_phi",                "title":"Reco subleading Z daughter #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZSub_theta":             {"name":"RecoZSub_theta",              "title":"Reco subleading Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZSub_y":                 {"name":"RecoZSub_y",                  "title":"Reco subleading Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZSub_mass":              {"name":"RecoZSub_mass",               "title":"Reco subleading Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},

      "Higgs_px":                 {"name":"Higgs_px",                 "title":"Reco H p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "Higgs_py":                 {"name":"Higgs_py",                 "title":"Reco H p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "Higgs_pz":                 {"name":"Higgs_pz",                 "title":"Reco H p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "Higgs_p":                  {"name":"Higgs_p",                  "title":"Reco H p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "Higgs_pt":                 {"name":"Higgs_pt",                 "title":"Reco H p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "Higgs_e":                  {"name":"Higgs_e",                  "title":"Reco H energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "Higgs_eta":                {"name":"Higgs_eta",                "title":"Reco H #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "Higgs_phi":                {"name":"Higgs_phi",                "title":"Reco H #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "Higgs_theta":              {"name":"Higgs_theta",              "title":"Reco H #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "Higgs_y":                  {"name":"Higgs_y",                  "title":"Reco H rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "Higgs_mass":               {"name":"Higgs_mass",               "title":"Reco H mass",                   "bin":100, "xmin":0 ,"xmax":200},

    "TauLead_px":               {"name":"TauLead_px",                 "title":"#tau_{leading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_py":               {"name":"TauLead_py",                 "title":"#tau_{leading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_pz":               {"name":"TauLead_pz",                 "title":"#tau_{leading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_p":                {"name":"TauLead_p",                  "title":"#tau_{leading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_pt":               {"name":"TauLead_pt",                 "title":"#tau_{leading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_e":                {"name":"TauLead_e",                  "title":"#tau_{leading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauLead_eta":              {"name":"TauLead_eta",                "title":"#tau_{leading} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauLead_phi":              {"name":"TauLead_phi",                "title":"#tau_{leading} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauLead_theta":            {"name":"TauLead_theta",              "title":"#tau_{leading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauLead_y":                {"name":"TauLead_y",                  "title":"#tau_{leading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauLead_mass":             {"name":"TauLead_mass",               "title":"#tau_{leading} mass",                   "bin":30, "xmin":0., "xmax":3.},
    #"TauLead_type":             {"name":"TauLead_type",               "title":"#tau_{leading} type",                   "bin":113, "xmin":-0.13, "xmax":1.},
    
    "TauSub_px":                {"name":"TauSub_px",                 "title":"#tau_{subleading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_py":                {"name":"TauSub_py",                 "title":"#tau_{subleading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_pz":                {"name":"TauSub_pz",                 "title":"#tau_{subleading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_p":                 {"name":"TauSub_p",                  "title":"#tau_{subleading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_pt":                {"name":"TauSub_pt",                 "title":"#tau_{subleading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_e":                 {"name":"TauSub_e",                  "title":"#tau_{subleading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauSub_eta":               {"name":"TauSub_eta",                "title":"#tau_{subleading} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauSub_phi":               {"name":"TauSub_phi",                "title":"#tau_{subleading} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauSub_theta":             {"name":"TauSub_theta",              "title":"#tau_{subleading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauSub_y":                 {"name":"TauSub_y",                  "title":"#tau_{subleading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauSub_mass":              {"name":"TauSub_mass",               "title":"#tau_{subleading} mass",                   "bin":30, "xmin":0., "xmax":3.},
    #"TauSub_type":              {"name":"TauSub_type",               "title":"#tau_{subleading} type",                   "bin":113, "xmin":-0.13, "xmax":1.},
    
    "TauP_px":               {"name":"TauP_px",                 "title":"#tau^{+} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauP_py":               {"name":"TauP_py",                 "title":"#tau^{+} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauP_pz":               {"name":"TauP_pz",                 "title":"#tau^{+} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauP_p":                {"name":"TauP_p",                  "title":"#tau^{+} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauP_pt":               {"name":"TauP_pt",                 "title":"#tau^{+} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauP_e":                {"name":"TauP_e",                  "title":"#tau^{+} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauP_eta":              {"name":"TauP_eta",                "title":"#tau^{+} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauP_phi":              {"name":"TauP_phi",                "title":"#tau^{+} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauP_theta":            {"name":"TauP_theta",              "title":"#tau^{+} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauP_y":                {"name":"TauP_y",                  "title":"#tau^{+} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauP_mass":             {"name":"TauP_mass",               "title":"#tau^{+} mass",                   "bin":30, "xmin":0., "xmax":3.},
    
    "TauM_px":                {"name":"TauM_px",                 "title":"#tau^{-} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauM_py":                {"name":"TauM_py",                 "title":"#tau^{-} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauM_pz":                {"name":"TauM_pz",                 "title":"#tau^{-} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauM_p":                 {"name":"TauM_p",                  "title":"#tau^{-} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauM_pt":                {"name":"TauM_pt",                 "title":"#tau^{-} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauM_e":                 {"name":"TauM_e",                  "title":"#tau^{-} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauM_eta":               {"name":"TauM_eta",                "title":"#tau^{-} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauM_phi":               {"name":"TauM_phi",                "title":"#tau^{-} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauM_theta":             {"name":"TauM_theta",              "title":"#tau^{-} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauM_y":                 {"name":"TauM_y",                  "title":"#tau^{-} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauM_mass":              {"name":"TauM_mass",               "title":"#tau^{-} mass",                   "bin":30, "xmin":0., "xmax":3.},
    
    "Tau_DPhi":         {"name":"Tau_DPhi",           "title":"#Delta#phi(#tau#tau)",                                "bin":128, "xmin":-6.4,"xmax":6.4},
    "Tau_DR":                   {"name":"Tau_DR",                     "title":"#Delta R(#tau#tau)",                  "bin":70, "xmin":0,"xmax":7},
    "Tau_cos":                  {"name":"Tau_cos",                    "title":"cos#theta(#tau#tau)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "Tau_DEta":                             {"name":"Tau_DEta",           "title":"Reco di-#tau #Delta#eta",                                  "bin":128, "xmin":-6.4,"xmax":6.4},

    "RecoZDaughter_DPhi":         {"name":"RecoZDaughter_DPhi",           "title":"#Delta#phi(ll)",                                "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoZDaughter_DR":                   {"name":"RecoZDaughter_DR",                     "title":"#Delta R(ll)",                  "bin":70, "xmin":0,"xmax":7},
    "RecoZDaughter_cos":                  {"name":"RecoZDaughter_cos",                    "title":"cos#theta(ll)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "RecoZDaughter_DEta":                   {"name":"RecoZDaughter_DEta",           "title":"Reco Z daughters #Delta#eta",                                  "bin":128, "xmin":-6.4,"xmax":6.4},

    "Recoil":                   {"name":"Recoil",                   "title":"M_{recoil} [GeV]",                     "bin":100, "xmin":0., "xmax":200.},
    "Collinear_mass":           {"name":"Collinear_mass",           "title":"M_{collinear} [GeV]",                  "bin":100, "xmin":0., "xmax":200.},

    #### CP variables

    "Phi_ZMF":                          {"name": "Phi_ZMF", "title": "cos(#Delta#phi_{CP}) CMS", "bin": 50, "xmin": -1, "xmax": 1},
    "O_ZMF":                          {"name": "O_ZMF", "title": "sin(#Delta#phi_{CP}) CMS", "bin": 50, "xmin": -1, "xmax": 1},
    "y_tau":                          {"name": "y_tau", "title": "y^{#tau} CMS", "bin": 50, "xmin": -1, "xmax": 1},
    "PhiCP_CMS":                             {"name":"PhiCP_CMS",           "title":"#Delta#Phi_{CP} CMS",                  "bin":32, "xmin":-3.14,"xmax":3.14},

    "CosDeltaPhiILC":                          {"name": "CosDeltaPhiILC", "title": "cos(#Delta#phi_{CP}) ILC", "bin": 50, "xmin": -1, "xmax": 1},
    "SinDeltaPhiILC":                          {"name": "SinDeltaPhiILC", "title": "sin(#Delta#phi_{CP}) ILC", "bin": 50, "xmin": -1, "xmax": 1},
    "DeltaPhiILC":                             {"name":"DeltaPhiILC",           "title":"#Delta#Phi_{CP} ILC",                  "bin":32, "xmin":-3.14,"xmax":3.14},
    "KinILC_chi2":                             {"name":"KinILC_chi2",           "title":"#chi^{2} ILC",                  "bin":50, "xmin":0,"xmax":20},

    "RecoH_px":                 {"name":"RecoH_px",                 "title":"Reco H p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_py":                 {"name":"RecoH_py",                 "title":"Reco H p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_pz":                 {"name":"RecoH_pz",                 "title":"Reco H p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_p":                  {"name":"RecoH_p",                  "title":"Reco H p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_pt":                 {"name":"RecoH_pt",                 "title":"Reco H p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_e":                  {"name":"RecoH_e",                  "title":"Reco H energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_eta":                {"name":"RecoH_eta",                "title":"Reco H #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoH_phi":                {"name":"RecoH_phi",                "title":"Reco H #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoH_theta":              {"name":"RecoH_theta",              "title":"Reco H #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoH_y":                  {"name":"RecoH_y",                  "title":"Reco H rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoH_mass":               {"name":"RecoH_mass",               "title":"Reco H mass",                   "bin":100, "xmin":0 ,"xmax":200},

    "RecoTauLead_px":               {"name":"RecoTauLead_px",                 "title":"#tau_{leading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoTauLead_py":               {"name":"RecoTauLead_py",                 "title":"#tau_{leading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoTauLead_pz":               {"name":"RecoTauLead_pz",                 "title":"#tau_{leading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoTauLead_p":                {"name":"RecoTauLead_p",                  "title":"#tau_{leading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauLead_pt":               {"name":"RecoTauLead_pt",                 "title":"#tau_{leading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauLead_e":                {"name":"RecoTauLead_e",                  "title":"#tau_{leading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoTauLead_eta":              {"name":"RecoTauLead_eta",                "title":"#tau_{leading} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauLead_phi":              {"name":"RecoTauLead_phi",                "title":"#tau_{leading} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauLead_theta":            {"name":"RecoTauLead_theta",              "title":"#tau_{leading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoTauLead_y":                {"name":"RecoTauLead_y",                  "title":"#tau_{leading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoTauLead_mass":             {"name":"RecoTauLead_mass",               "title":"#tau_{leading} mass",                   "bin":30, "xmin":0., "xmax":3.},
    #"RecoTauLead_type":             {"name":"RecoTauLead_type",               "title":"#tau_{leading} type",                   "bin":113, "xmin":-0.13, "xmax":1.},
    
    "RecoTauSub_px":                {"name":"RecoTauSub_px",                 "title":"#tau_{subleading} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoTauSub_py":                {"name":"RecoTauSub_py",                 "title":"#tau_{subleading} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoTauSub_pz":                {"name":"RecoTauSub_pz",                 "title":"#tau_{subleading} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoTauSub_p":                 {"name":"RecoTauSub_p",                  "title":"#tau_{subleading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauSub_pt":                {"name":"RecoTauSub_pt",                 "title":"#tau_{subleading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauSub_e":                 {"name":"RecoTauSub_e",                  "title":"#tau_{subleading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoTauSub_eta":               {"name":"RecoTauSub_eta",                "title":"#tau_{subleading} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauSub_phi":               {"name":"RecoTauSub_phi",                "title":"#tau_{subleading} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauSub_theta":             {"name":"RecoTauSub_theta",              "title":"#tau_{subleading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoTauSub_y":                 {"name":"RecoTauSub_y",                  "title":"#tau_{subleading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoTauSub_mass":              {"name":"RecoTauSub_mass",               "title":"#tau_{subleading} mass",                   "bin":30, "xmin":0., "xmax":3.},
    #"RecoTauSub_type":              {"name":"RecoTauSub_type",               "title":"#tau_{subleading} type",                   "bin":113, "xmin":-0.13, "xmax":1.},
    
    "RecoTauP_px":               {"name":"RecoTauP_px",                 "title":"#tau^{+} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoTauP_py":               {"name":"RecoTauP_py",                 "title":"#tau^{+} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoTauP_pz":               {"name":"RecoTauP_pz",                 "title":"#tau^{+} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoTauP_p":                {"name":"RecoTauP_p",                  "title":"#tau^{+} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauP_pt":               {"name":"RecoTauP_pt",                 "title":"#tau^{+} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauP_e":                {"name":"RecoTauP_e",                  "title":"#tau^{+} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoTauP_eta":              {"name":"RecoTauP_eta",                "title":"#tau^{+} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauP_phi":              {"name":"RecoTauP_phi",                "title":"#tau^{+} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauP_theta":            {"name":"RecoTauP_theta",              "title":"#tau^{+} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoTauP_y":                {"name":"RecoTauP_y",                  "title":"#tau^{+} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoTauP_mass":             {"name":"RecoTauP_mass",               "title":"#tau^{+} mass",                   "bin":30, "xmin":0., "xmax":3.},
    
    "RecoTauM_px":                {"name":"RecoTauM_px",                 "title":"#tau^{-} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoTauM_py":                {"name":"RecoTauM_py",                 "title":"#tau^{-} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoTauM_pz":                {"name":"RecoTauM_pz",                 "title":"#tau^{-} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoTauM_p":                 {"name":"RecoTauM_p",                  "title":"#tau^{-} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauM_pt":                {"name":"RecoTauM_pt",                 "title":"#tau^{-} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoTauM_e":                 {"name":"RecoTauM_e",                  "title":"#tau^{-} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoTauM_eta":               {"name":"RecoTauM_eta",                "title":"#tau^{-} #eta",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauM_phi":               {"name":"RecoTauM_phi",                "title":"#tau^{-} #phi",                                   "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTauM_theta":             {"name":"RecoTauM_theta",              "title":"#tau^{-} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoTauM_y":                 {"name":"RecoTauM_y",                  "title":"#tau^{-} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoTauM_mass":              {"name":"RecoTauM_mass",               "title":"#tau^{-} mass",                   "bin":30, "xmin":0., "xmax":3.},
    
    "RecoTau_DPhi":         {"name":"RecoTau_DPhi",           "title":"#Delta#phi(#tau#tau)",                                "bin":128, "xmin":-6.4,"xmax":6.4},
    "RecoTau_DR":                   {"name":"RecoTau_DR",                     "title":"#Delta R(#tau#tau)",                  "bin":70, "xmin":0,"xmax":7},
    "RecoTau_cos":                  {"name":"RecoTau_cos",                    "title":"cos#theta(#tau#tau)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "RecoTau_DEta":                             {"name":"RecoTau_DEta",           "title":"Reco di-#tau #Delta#eta",                                  "bin":128, "xmin":-6.4,"xmax":6.4},


}

'''

"TauTag_e":                {"name":"TauTag_e",                   "title":"#tau from tagged jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "TauTag_p":                {"name":"TauTag_p",                   "title":"#tau from tagged jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauTag_pt":               {"name":"TauTag_pt",                  "title":"#tau from tagged jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauTag_px":               {"name":"TauTag_px",                  "title":"#tau from tagged jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauTag_py":               {"name":"TauTag_py",                  "title":"#tau from tagged jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauTag_pz":               {"name":"TauTag_pz",                  "title":"#tau from tagged jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauTag_eta":              {"name":"TauTag_eta",                 "title":"#tau from tagged jet #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauTag_theta":            {"name":"TauTag_theta",               "title":"#tau from tagged jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauTag_phi":              {"name":"TauTag_phi",                 "title":"#tau from tagged jet #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "TauTag_mass":             {"name":"TauTag_mass",                "title":"#tau from tagged jet mass [GeV]",                     "bin":60, "xmin":0., "xmax":30.},
    "n_TauTag":                {"name":"n_TauTag",                   "title":"Number of #tau from tagged jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TauTag_isG":             {"name":"TauTag_isG",                "title":"#tau from tagged jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isU":             {"name":"TauTag_isU",                "title":"#tau from tagged jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isD":             {"name":"TauTag_isD",                "title":"#tau from tagged jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isC":             {"name":"TauTag_isC",                "title":"#tau from tagged jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isS":             {"name":"TauTag_isS",                "title":"#tau from tagged jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isB":             {"name":"TauTag_isB",                "title":"#tau from tagged jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TauTag_isTAU":             {"name":"TauTag_isTAU",                "title":"#tau from tagged jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "QuarkTag_e":                {"name":"QuarkTag_e",                   "title":"Quark jet from tagged jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "QuarkTag_p":                {"name":"QuarkTag_p",                   "title":"Quark jet from tagged jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "QuarkTag_pt":               {"name":"QuarkTag_pt",                  "title":"Quark jet from tagged jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "QuarkTag_px":               {"name":"QuarkTag_px",                  "title":"Quark jet from tagged jet p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "QuarkTag_py":               {"name":"QuarkTag_py",                  "title":"Quark jet from tagged jet p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "QuarkTag_pz":               {"name":"QuarkTag_pz",                  "title":"Quark jet from tagged jet p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "QuarkTag_eta":              {"name":"QuarkTag_eta",                 "title":"Quark jet from tagged jet #eta",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "QuarkTag_theta":            {"name":"QuarkTag_theta",               "title":"Quark jet from tagged jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "QuarkTag_phi":              {"name":"QuarkTag_phi",                 "title":"Quark jet from tagged jet #phi",                                           "bin":128, "xmin":-6.4,"xmax":6.4},
    "QuarkTag_mass":             {"name":"QuarkTag_mass",                "title":"Quark jet from tagged jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_QuarkTag":                {"name":"n_QuarkTag",                   "title":"Number of Quark jet from tagged jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "QuarkTag_isG":             {"name":"QuarkTag_isG",                "title":"Quark jet from tagged jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isU":             {"name":"QuarkTag_isU",                "title":"Quark jet from tagged jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isD":             {"name":"QuarkTag_isD",                "title":"Quark jet from tagged jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isC":             {"name":"QuarkTag_isC",                "title":"Quark jet from tagged jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isS":             {"name":"QuarkTag_isS",                "title":"Quark jet from tagged jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isB":             {"name":"QuarkTag_isB",                "title":"Quark jet from tagged jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "QuarkTag_isTAU":             {"name":"QuarkTag_isTAU",                "title":"Quark jet from tagged jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},


    "CosDeltaPhi":                          {"name": "CosDeltaPhi", "title": "cos(#Delta#phi_{CP}) Belle", "bin": 50, "xmin": -1, "xmax": 1},
    "SinDeltaPhi":                          {"name": "SinDeltaPhi", "title": "sin(#Delta#phi_{CP}) Belle", "bin": 50, "xmin": -1, "xmax": 1},
    "DeltaPhi":                             {"name":"DeltaPhi",           "title":"#Delta#Phi_{CP} Belle",                  "bin":32, "xmin":-3.14,"xmax":3.14},

    
    '''