#Input directory where the files produced at the stage1 level are
inputDir = "/ceph/sgiappic/HiggsCP/CP/stage2_id2"

#Optional: output directory, default is local running directory
outputDir = "/ceph/sgiappic/HiggsCP/CP/final_id2"

#Integrated luminosity for scaling number of events (required only if setting doScale to true)
intLumi = 10.8e6 #pb^-1 #to be checked again for 240 gev

#Scale event yields by intLumi and cross section (optional)
# if scaling, both the number of events in the table and in the histograms will be scaled
doScale = True

#Save event yields in a table (optional)
saveTabular = True

#Number of CPUs to use
nCPUS = 4

#produces ROOT TTrees, default is False
doTree = False

#Mandatory: List of processes
processList = {
    'noISR_e+e-_noCuts_EWonly':{},
    'noISR_e+e-_noCuts_cehim_m1':{},
    'noISR_e+e-_noCuts_cehim_p1':{},
    'noISR_e+e-_noCuts_cehre_m1':{},
    'noISR_e+e-_noCuts_cehre_p1':{},
}
###Dictionary for prettier names of processes (optional)
#change them if you want but they don't do anything
processLabels = {}

#Link to the dictonary that contains all the cross section information etc...
procDict = "FCCee_procDict_winter2023_IDEA.json"

#Add provate samples as it is not an offical process
procDictAdd = {
    'noISR_e+e-_noCuts_EWonly':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051559935862, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehim_m1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051749741618, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehim_p1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00051749741618, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehre_m1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00058001482393, "kfactor": 1.0, "matchingEfficiency": 1.0},
    'noISR_e+e-_noCuts_cehre_p1':{"numberOfEvents": 100000, "sumOfWeights": 100000, "crossSection": 0.00045498699833000005, "kfactor": 1.0, "matchingEfficiency": 1.0},

}

###Dictionnay of the list of cuts. The key is the name of the selection that will be added to the output file
cutList = {
    ### no selection, just builds the histograms, it will not be shown in the latex table
    "selGen": "true",
    #"selReco_Maria": " (Recoil>120 && Recoil<140) && (TauFromJet_type[0]>=0 && TauFromJet_type[1]>=0)",
}

# Dictionary for prettier names of cuts (optional)
### needs to be in the same order as cutList or the table won't be organised well, it's only for the table ###
cutLabels = {}

###Dictionary for the ouput variable/hitograms. The key is the name of the variable in the output files. "name" is the name of the variable in the input file, "title" is the x-axis label of the histogram, "bin" the number of bins of the histogram, "xmin" the minimum x-axis value and "xmax" the maximum x-axis value.
histoList = {
    "n_FSGenElectron":                  {"name":"n_FSGenElectron",                  "title":"Number of final state gen electrons",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenElectron_e":                  {"name":"FSGenElectron_e",                  "title":"Final state gen electrons energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenElectron_p":                  {"name":"FSGenElectron_p",                  "title":"Final state gen electrons p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenElectron_pt":                 {"name":"FSGenElectron_pt",                 "title":"Final state gen electrons p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenElectron_px":                 {"name":"FSGenElectron_px",                 "title":"Final state gen electrons p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenElectron_py":                 {"name":"FSGenElectron_py",                 "title":"Final state gen electrons p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenElectron_pz":                 {"name":"FSGenElectron_pz",                 "title":"Final state gen electrons p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenElectron_y":                  {"name":"FSGenElectron_y",                  "title":"Final state gen electrons rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenElectron_eta":                {"name":"FSGenElectron_eta",                "title":"Final state gen electrons #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenElectron_theta":              {"name":"FSGenElectron_theta",              "title":"Final state gen electrons #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenElectron_phi":                {"name":"FSGenElectron_phi",                "title":"Final state gen electrons #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenElectron_charge":             {"name":"FSGenElectron_charge",             "title":"Final state gen electrons charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
    "FSGenElectron_mass":               {"name":"FSGenElectron_mass",               "title":"Final state gen electrons mass [GeV]",             "bin":20, "xmin":0., "xmax":2.},
    "FSGenElectron_parentPDG":          {"name":"FSGenElectron_parentPDG",          "title":"Final state gen electrons parent PDG",             "bin":30, "xmin":0., "xmax":30.},
    "FSGenElectron_vertex_x":           {"name":"FSGenElectron_vertex_x", "title":"Final state gen e^{#font[122]{\55}} production vertex x [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenElectron_vertex_y":           {"name":"FSGenElectron_vertex_y", "title":"Final state gen e^{#font[122]{\55}} production vertex y [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenElectron_vertex_z":           {"name":"FSGenElectron_vertex_z", "title":"Final state gen e^{#font[122]{\55}} production vertex z [mm]",   "bin":100, "xmin":-2000, "xmax":2000},

    "n_FSGenMuon":                      {"name":"n_FSGenMuon",                  "title":"Number of final state gen muons",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenMuon_e":                      {"name":"FSGenMuon_e",                  "title":"Final state gen muons energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenMuon_p":                      {"name":"FSGenMuon_p",                  "title":"Final state gen muons p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenMuon_pt":                     {"name":"FSGenMuon_pt",                 "title":"Final state gen muons p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenMuon_px":                     {"name":"FSGenMuon_px",                 "title":"Final state gen muons p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenMuon_py":                     {"name":"FSGenMuon_py",                 "title":"Final state gen muons p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenMuon_pz":                     {"name":"FSGenMuon_pz",                 "title":"Final state gen muons p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenMuon_y":                      {"name":"FSGenMuon_y",                  "title":"Final state gen muons rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenMuon_eta":                    {"name":"FSGenMuon_eta",                "title":"Final state gen muons #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenMuon_theta":                  {"name":"FSGenMuon_theta",              "title":"Final state gen muons #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenMuon_phi":                    {"name":"FSGenMuon_phi",                "title":"Final state gen muons #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenMuon_charge":                 {"name":"FSGenMuon_charge",             "title":"Final state gen muons charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
    "FSGenMuon_mass":                   {"name":"FSGenMuon_mass",               "title":"Final state gen muons mass [GeV]",             "bin":20, "xmin":0., "xmax":2.},
    "FSGenMuon_parentPDG":              {"name":"FSGenMuon_parentPDG",          "title":"Final state gen muons parent PDG",             "bin":30, "xmin":0., "xmax":30.},
    "FSGenMuon_vertex_x":               {"name":"FSGenMuon_vertex_x", "title":"Final state gen #mu^{#font[122]{\55}} production vertex x [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenMuon_vertex_y":               {"name":"FSGenMuon_vertex_y", "title":"Final state gen #mu^{#font[122]{\55}} production vertex y [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenMuon_vertex_z":               {"name":"FSGenMuon_vertex_z", "title":"Final state gen #mu^{#font[122]{\55}} production vertex z [mm]",   "bin":100, "xmin":-2000, "xmax":2000},

    "n_FSRGenTau":                      {"name":"n_FSRGenTau",                  "title":"Number of final state gen taus",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSRGenTau_e":                      {"name":"FSRGenTau_e",                  "title":"Final state gen taus energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSRGenTau_p":                      {"name":"FSRGenTau_p",                  "title":"Final state gen taus p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSRGenTau_pt":                     {"name":"FSRGenTau_pt",                 "title":"Final state gen taus p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSRGenTau_px":                     {"name":"FSRGenTau_px",                 "title":"Final state gen taus p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSRGenTau_py":                     {"name":"FSRGenTau_py",                 "title":"Final state gen taus p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSRGenTau_pz":                     {"name":"FSRGenTau_pz",                 "title":"Final state gen taus p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSRGenTau_y":                      {"name":"FSRGenTau_y",                  "title":"Final state gen taus rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSRGenTau_eta":                    {"name":"FSRGenTau_eta",                "title":"Final state gen taus #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSRGenTau_theta":                  {"name":"FSRGenTau_theta",              "title":"Final state gen taus #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSRGenTau_phi":                    {"name":"FSRGenTau_phi",                "title":"Final state gen taus #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSRGenTau_charge":                 {"name":"FSRGenTau_charge",             "title":"Final state gen taus charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
    "FSRGenTau_mass":                   {"name":"FSRGenTau_mass",               "title":"Final state gen taus mass [GeV]",             "bin":20, "xmin":0., "xmax":2.},
    "FSRGenTau_parentPDG":              {"name":"FSRGenTau_parentPDG",          "title":"Final state gen taus parent PDG",             "bin":30, "xmin":0., "xmax":30.},
    "FSRGenTau_vertex_x":               {"name":"FSRGenTau_vertex_x", "title":"Final state gen #tau^{#font[122]{\55}} production vertex x [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSRGenTau_vertex_y":               {"name":"FSRGenTau_vertex_y", "title":"Final state gen #tau^{#font[122]{\55}} production vertex y [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSRGenTau_vertex_z":               {"name":"FSRGenTau_vertex_z", "title":"Final state gen #tau^{#font[122]{\55}} production vertex z [mm]",   "bin":100, "xmin":-2000, "xmax":2000},

    "n_TauNeg_MuNuNu":                  {"name":"n_TauNeg_MuNuNu",          "title":"Number of #tau^{-} decays into #mu #nu #nu per events",            "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_MuNuNu_Phot":             {"name":"n_TauNeg_MuNuNu_Phot",     "title":"Number of #tau^{-} decays into #mu #nu #nu #gamma per events",     "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_ENuNu":                   {"name":"n_TauNeg_ENuNu",           "title":"Number of #tau^{-} decays into e #nu #nu per events",              "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_ENuNu_Phot":              {"name":"n_TauNeg_ENuNu_Phot",      "title":"Number of #tau^{-} decays into e #nu #nu #gamma per events",       "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_PiNu":                    {"name":"n_TauNeg_PiNu",            "title":"Number of #tau^{-} decays into #pi #nu per events",                "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_PiNu_Phot":               {"name":"n_TauNeg_PiNu_Phot",       "title":"Number of #tau^{-} decays into #pi #nu #gamma per events",         "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_KNu":                     {"name":"n_TauNeg_KNu",             "title":"Number of #tau^{-} decays into K #nu per events",                  "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_KNu_Phot":                {"name":"n_TauNeg_KNu_Phot",        "title":"Number of #tau^{-} decays into K #nu #gamma per events",           "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_PiK0Nu":                  {"name":"n_TauNeg_PiK0Nu",          "title":"Number of #tau^{-} decays into #pi K^{0} #nu per events",          "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_PiK0Nu_Phot":             {"name":"n_TauNeg_PiK0Nu_Phot",     "title":"Number of #tau^{-} decays into #pi K^{0} #nu #gamma per events",   "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_KK0Nu":                   {"name":"n_TauNeg_KK0Nu",           "title":"Number of #tau^{-} decays into K K^{0} #nu per events",            "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_KK0Nu_Phot":              {"name":"n_TauNeg_KK0Nu_Phot",      "title":"Number of #tau^{-} decays into K K^{0} #nu #gamma per events",     "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_3PiNu":                   {"name":"n_TauNeg_3PiNu",           "title":"Number of #tau^{-} decays into 3 #pi #nu per events",              "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauNeg_3PiNu_Phot":              {"name":"n_TauNeg_3PiNu_Phot",      "title":"Number of #tau^{-} decays into 3 #pi #nu #gamma per events",       "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_PiKKNu":                  {"name":"n_TauNeg_PiKKNu",          "title":"Number of #tau^{-} decays into #pi K K #nu per events",            "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauNeg_PiKKNu_Phot":             {"name":"n_TauNeg_PiKKNu_Phot",     "title":"Number of #tau^{-} decays into #pi K K #nu #gamma per events",     "bin":2, "xmin":-0.5, "xmax":1.5},

    "n_TauPos_MuNuNu":                  {"name":"n_TauPos_MuNuNu",          "title":"Number of #tau^{+} decays into #mu #nu #nu per events",            "bin":2, "xmin":-0.5, "xmax":1.5}, 
    "n_TauPos_MuNuNu_Phot":             {"name":"n_TauPos_MuNuNu_Phot",     "title":"Number of #tau^{+} decays into #mu #nu #nu #gamma per events",     "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_ENuNu":                   {"name":"n_TauPos_ENuNu",           "title":"Number of #tau^{+} decays into e #nu #nu per events",              "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_ENuNu_Phot":              {"name":"n_TauPos_ENuNu_Phot",      "title":"Number of #tau^{+} decays into e #nu #nu #gamma per events",       "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_PiNu":                    {"name":"n_TauPos_PiNu",            "title":"Number of #tau^{+} decays into #pi #nu per events",                "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_PiNu_Phot":               {"name":"n_TauPos_PiNu_Phot",       "title":"Number of #tau^{+} decays into #pi #nu #gamma per events",         "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_KNu":                     {"name":"n_TauPos_KNu",             "title":"Number of #tau^{+} decays into K #nu per events",                  "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_KNu_Phot":                {"name":"n_TauPos_KNu_Phot",        "title":"Number of #tau^{+} decays into K #nu #gamma per events",           "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_PiK0Nu":                  {"name":"n_TauPos_PiK0Nu",          "title":"Number of #tau^{+} decays into #pi K^{0} #nu per events",          "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_PiK0Nu_Phot":             {"name":"n_TauPos_PiK0Nu_Phot",     "title":"Number of #tau^{+} decays into #pi K^{0} #nu #gamma per events",   "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_KK0Nu":                   {"name":"n_TauPos_KK0Nu",           "title":"Number of #tau^{+} decays into K K^{0} #nu per events",            "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_KK0Nu_Phot":              {"name":"n_TauPos_KK0Nu_Phot",      "title":"Number of #tau^{+} decays into K K^{0} #nu #gamma per events",     "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_3PiNu":                   {"name":"n_TauPos_3PiNu",           "title":"Number of #tau^{+} decays into 3 #pi #nu per events",              "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_3PiNu_Phot":              {"name":"n_TauPos_3PiNu_Phot",      "title":"Number of #tau^{+} decays into 3 #pi #nu #gamma per events",       "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_PiKKNu":                  {"name":"n_TauPos_PiKKNu",          "title":"Number of #tau^{+} decays into #pi K K #nu per events",            "bin":2, "xmin":-0.5, "xmax":1.5},
    "n_TauPos_PiKKNu_Phot":             {"name":"n_TauPos_PiKKNu_Phot",     "title":"Number of #tau^{+} decays into #pi K K #nu #gamma per events",     "bin":2, "xmin":-0.5, "xmax":1.5},

    "n_FSGenNeutrino":                  {"name":"n_FSGenNeutrino",                  "title":"Number of final state gen neutrinos",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenNeutrino_e":                  {"name":"FSGenNeutrino_e",                  "title":"Final state gen neutrinos energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenNeutrino_p":                  {"name":"FSGenNeutrino_p",                  "title":"Final state gen neutrinos p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenNeutrino_pt":                 {"name":"FSGenNeutrino_pt",                 "title":"Final state gen neutrinos p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenNeutrino_px":                 {"name":"FSGenNeutrino_px",                 "title":"Final state gen neutrinos p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenNeutrino_py":                 {"name":"FSGenNeutrino_py",                 "title":"Final state gen neutrinos p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenNeutrino_pz":                 {"name":"FSGenNeutrino_pz",                 "title":"Final state gen neutrinos p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenNeutrino_y":                  {"name":"FSGenNeutrino_y",                  "title":"Final state gen neutrinos rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenNeutrino_eta":                {"name":"FSGenNeutrino_eta",                "title":"Final state gen neutrinos #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenNeutrino_theta":              {"name":"FSGenNeutrino_theta",              "title":"Final state gen neutrinos #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenNeutrino_phi":                {"name":"FSGenNeutrino_phi",                "title":"Final state gen neutrinos #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenNeutrino_charge":             {"name":"FSGenNeutrino_charge",             "title":"Final state gen neutrinos charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
                                        
    "n_FSGenPhoton":                    {"name":"n_FSGenPhoton",                  "title":"Number of final state gen photons",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenPhoton_e":                    {"name":"FSGenPhoton_e",                  "title":"Final state gen photons energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenPhoton_p":                    {"name":"FSGenPhoton_p",                  "title":"Final state gen photons p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenPhoton_pt":                   {"name":"FSGenPhoton_pt",                 "title":"Final state gen photons p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenPhoton_px":                   {"name":"FSGenPhoton_px",                 "title":"Final state gen photons p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenPhoton_py":                   {"name":"FSGenPhoton_py",                 "title":"Final state gen photons p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenPhoton_pz":                   {"name":"FSGenPhoton_pz",                 "title":"Final state gen photons p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "FSGenPhoton_y":                    {"name":"FSGenPhoton_y",                  "title":"Final state gen photons rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenPhoton_eta":                  {"name":"FSGenPhoton_eta",                "title":"Final state gen photons #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenPhoton_theta":                {"name":"FSGenPhoton_theta",              "title":"Final state gen photons #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenPhoton_phi":                  {"name":"FSGenPhoton_phi",                "title":"Final state gen photons #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenPhoton_charge":               {"name":"FSGenPhoton_charge",             "title":"Final state gen photons charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},

    "n_GenHiggs":                       {"name":"n_GenHiggs",                  "title":"Number of gen Higgs",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "GenHiggs_e":                       {"name":"GenHiggs_e",                  "title":"Gen Higgs energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "GenHiggs_p":                       {"name":"GenHiggs_p",                  "title":"Gen Higgs p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "GenHiggs_pt":                      {"name":"GenHiggs_pt",                 "title":"Gen Higgs p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "GenHiggs_px":                      {"name":"GenHiggs_px",                 "title":"Gen Higgs p_{x} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenHiggs_py":                      {"name":"GenHiggs_py",                 "title":"Gen Higgs p_{y} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenHiggs_pz":                      {"name":"GenHiggs_pz",                 "title":"Gen Higgs p_{z} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenHiggs_y":                       {"name":"GenHiggs_y",                  "title":"Gen Higgs rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "GenHiggs_mass":                    {"name":"GenHiggs_y",                  "title":"Gen Higgs M [GeV]",                "bin":50, "xmin":90, "xmax":140},
    "GenHiggs_eta":                     {"name":"GenHiggs_eta",                "title":"Gen Higgs #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenHiggs_theta":                   {"name":"GenHiggs_theta",              "title":"Gen Higgs #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "GenHiggs_phi":                     {"name":"GenHiggs_phi",                "title":"Gen Higgs #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenHiggs_charge":                  {"name":"GenHiggs_charge",             "title":"Gen Higgs charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},

    ######## Reconstructed particles #######

    "n_RecoElectrons":                  {"name":"n_RecoElectrons",                  "title":"Number of reco electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_e":                   {"name":"RecoElectron_e",                   "title":"Reco electron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_p":                   {"name":"RecoElectron_p",                   "title":"Reco electron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_pt":                  {"name":"RecoElectron_pt",                  "title":"Reco electron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_px":                  {"name":"RecoElectron_px",                  "title":"Reco electron p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_py":                  {"name":"RecoElectron_py",                  "title":"Reco electron p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_pz":                  {"name":"RecoElectron_pz",                  "title":"Reco electron p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_y":                   {"name":"RecoElectron_y",                   "title":"Reco electron rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_eta":                 {"name":"RecoElectron_eta",                 "title":"Reco electron #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_theta":               {"name":"RecoElectron_theta",               "title":"Reco electron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_phi":                 {"name":"RecoElectron_phi",                 "title":"Reco electron #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_charge":              {"name":"RecoElectron_charge",              "title":"Reco electron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_mass":                {"name":"RecoElectron_mass",                "title":"Reco electron mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_absD0":          {"name":"RecoElectronTrack_absD0",          "title":"Reco electron tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absZ0":          {"name":"RecoElectronTrack_absZ0",          "title":"Reco electron tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absD0sig":       {"name":"RecoElectronTrack_absD0sig",       "title":"Reco electron tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_absZ0sig":       {"name":"RecoElectronTrack_absZ0sig",       "title":"Reco electron tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_D0cov":          {"name":"RecoElectronTrack_D0cov",          "title":"Reco electron tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_Z0cov":          {"name":"RecoElectronTrack_Z0cov",          "title":"Reco electron tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoElectrons_sel":                  {"name":"n_RecoElectrons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_sel_e":                   {"name":"RecoElectron_sel_e",                   "title":"Reco electron isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_p":                   {"name":"RecoElectron_sel_p",                   "title":"Reco electron isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_pt":                  {"name":"RecoElectron_sel_pt",                  "title":"Reco electron isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoElectron_sel_px":                  {"name":"RecoElectron_sel_px",                  "title":"Reco electron isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_py":                  {"name":"RecoElectron_sel_py",                  "title":"Reco electron isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_pz":                  {"name":"RecoElectron_sel_pz",                  "title":"Reco electron isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoElectron_sel_y":                   {"name":"RecoElectron_sel_y",                   "title":"Reco electron isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_sel_eta":                 {"name":"RecoElectron_sel_eta",                 "title":"Reco electron isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_theta":               {"name":"RecoElectron_sel_theta",               "title":"Reco electron isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_sel_phi":                 {"name":"RecoElectron_sel_phi",                 "title":"Reco electron isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_charge":              {"name":"RecoElectron_sel_charge",              "title":"Reco electron isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_sel_mass":                {"name":"RecoElectron_sel_mass",                "title":"Reco electron isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_sel_absD0":          {"name":"RecoElectronTrack_sel_absD0",          "title":"Reco electron isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absZ0":          {"name":"RecoElectronTrack_sel_absZ0",          "title":"Reco electron isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absD0sig":       {"name":"RecoElectronTrack_sel_absD0sig",       "title":"Reco electron isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_absZ0sig":       {"name":"RecoElectronTrack_sel_absZ0sig",       "title":"Reco electron isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_D0cov":          {"name":"RecoElectronTrack_sel_D0cov",          "title":"Reco electron isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_sel_Z0cov":          {"name":"RecoElectronTrack_sel_Z0cov",          "title":"Reco electron isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons":                  {"name":"n_RecoMuons",                  "title":"Number of reco muons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_e":                   {"name":"RecoMuon_e",                   "title":"Reco muon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_p":                   {"name":"RecoMuon_p",                   "title":"Reco muon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_pt":                  {"name":"RecoMuon_pt",                  "title":"Reco muon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_px":                  {"name":"RecoMuon_px",                  "title":"Reco muon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_py":                  {"name":"RecoMuon_py",                  "title":"Reco muon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_pz":                  {"name":"RecoMuon_pz",                  "title":"Reco muon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_y":                   {"name":"RecoMuon_y",                   "title":"Reco muon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_eta":                 {"name":"RecoMuon_eta",                 "title":"Reco muon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_theta":               {"name":"RecoMuon_theta",               "title":"Reco muon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_phi":                 {"name":"RecoMuon_phi",                 "title":"Reco muon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_charge":              {"name":"RecoMuon_charge",              "title":"Reco muon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_mass":                {"name":"RecoMuon_mass",                "title":"Reco muon mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_absD0":          {"name":"RecoMuonTrack_absD0",          "title":"Reco muon tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absZ0":          {"name":"RecoMuonTrack_absZ0",          "title":"Reco muon tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absD0sig":       {"name":"RecoMuonTrack_absD0sig",       "title":"Reco muon tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_absZ0sig":       {"name":"RecoMuonTrack_absZ0sig",       "title":"Reco muon tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_D0cov":          {"name":"RecoMuonTrack_D0cov",          "title":"Reco muon tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_Z0cov":          {"name":"RecoMuonTrack_Z0cov",          "title":"Reco muon tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons_sel":                  {"name":"n_RecoMuons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_sel_e":                   {"name":"RecoMuon_sel_e",                   "title":"Reco muon isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_p":                   {"name":"RecoMuon_sel_p",                   "title":"Reco muon isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_pt":                  {"name":"RecoMuon_sel_pt",                  "title":"Reco muon isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoMuon_sel_px":                  {"name":"RecoMuon_sel_px",                  "title":"Reco muon isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_py":                  {"name":"RecoMuon_sel_py",                  "title":"Reco muon isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_pz":                  {"name":"RecoMuon_sel_pz",                  "title":"Reco muon isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoMuon_sel_y":                   {"name":"RecoMuon_sel_y",                   "title":"Reco muon isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_sel_eta":                 {"name":"RecoMuon_sel_eta",                 "title":"Reco muon isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_theta":               {"name":"RecoMuon_sel_theta",               "title":"Reco muon isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_sel_phi":                 {"name":"RecoMuon_sel_phi",                 "title":"Reco muon isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_charge":              {"name":"RecoMuon_sel_charge",              "title":"Reco muon isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_sel_mass":                {"name":"RecoMuon_sel_mass",                "title":"Reco muon isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_sel_absD0":          {"name":"RecoMuonTrack_sel_absD0",          "title":"Reco muon isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absZ0":          {"name":"RecoMuonTrack_sel_absZ0",          "title":"Reco muon isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absD0sig":       {"name":"RecoMuonTrack_sel_absD0sig",       "title":"Reco muon isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_absZ0sig":       {"name":"RecoMuonTrack_sel_absZ0sig",       "title":"Reco muon isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_D0cov":          {"name":"RecoMuonTrack_sel_D0cov",          "title":"Reco muon isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_sel_Z0cov":          {"name":"RecoMuonTrack_sel_Z0cov",          "title":"Reco muon isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons":                {"name":"n_RecoLeptons",                  "title":"Number of reco leptons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoLepton_e":                 {"name":"RecoLepton_e",                   "title":"Reco lepton energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_p":                 {"name":"RecoLepton_p",                   "title":"Reco lepton p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_pt":                {"name":"RecoLepton_pt",                  "title":"Reco lepton p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_px":                {"name":"RecoLepton_px",                  "title":"Reco lepton p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_py":                {"name":"RecoLepton_py",                  "title":"Reco lepton p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_pz":                {"name":"RecoLepton_pz",                  "title":"Reco lepton p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_y":                 {"name":"RecoLepton_y",                   "title":"Reco lepton rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_eta":               {"name":"RecoLepton_eta",                 "title":"Reco lepton #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_theta":             {"name":"RecoLepton_theta",               "title":"Reco lepton #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_phi":               {"name":"RecoLepton_phi",                 "title":"Reco lepton #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_charge":            {"name":"RecoLepton_charge",              "title":"Reco lepton charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_mass":              {"name":"RecoLepton_mass",                "title":"Reco lepton mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_absD0":        {"name":"RecoLeptonTrack_absD0",          "title":"Reco lepton tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absZ0":        {"name":"RecoLeptonTrack_absZ0",          "title":"Reco lepton tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absD0sig":     {"name":"RecoLeptonTrack_absD0sig",       "title":"Reco lepton tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_absZ0sig":     {"name":"RecoLeptonTrack_absZ0sig",       "title":"Reco lepton tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_D0cov":        {"name":"RecoLeptonTrack_D0cov",          "title":"Reco lepton tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_Z0cov":        {"name":"RecoLeptonTrack_Z0cov",          "title":"Reco lepton tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons_sel":                {"name":"n_RecoLeptons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.},
    "RecoLepton_sel_e":                 {"name":"RecoLepton_sel_e",                   "title":"Reco lepton isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_p":                 {"name":"RecoLepton_sel_p",                   "title":"Reco lepton isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_pt":                {"name":"RecoLepton_sel_pt",                  "title":"Reco lepton isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoLepton_sel_px":                {"name":"RecoLepton_sel_px",                  "title":"Reco lepton isolated p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_py":                {"name":"RecoLepton_sel_py",                  "title":"Reco lepton isolated p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_pz":                {"name":"RecoLepton_sel_pz",                  "title":"Reco lepton isolated p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoLepton_sel_y":                 {"name":"RecoLepton_sel_y",                   "title":"Reco lepton isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_sel_eta":               {"name":"RecoLepton_sel_eta",                 "title":"Reco lepton isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_theta":             {"name":"RecoLepton_sel_theta",               "title":"Reco lepton isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_sel_phi":               {"name":"RecoLepton_sel_phi",                 "title":"Reco lepton isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_charge":            {"name":"RecoLepton_sel_charge",              "title":"Reco lepton isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_sel_mass":              {"name":"RecoLepton_sel_mass",                "title":"Reco lepton isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_sel_absD0":        {"name":"RecoLeptonTrack_sel_absD0",          "title":"Reco lepton isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absZ0":        {"name":"RecoLeptonTrack_sel_absZ0",          "title":"Reco lepton isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absD0sig":     {"name":"RecoLeptonTrack_sel_absD0sig",       "title":"Reco lepton isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_absZ0sig":     {"name":"RecoLeptonTrack_sel_absZ0sig",       "title":"Reco lepton isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_D0cov":        {"name":"RecoLeptonTrack_sel_D0cov",          "title":"Reco lepton isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_sel_Z0cov":        {"name":"RecoLeptonTrack_sel_Z0cov",          "title":"Reco lepton isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoPhotons":            {"name":"n_RecoPhotons",                  "title":"Number of reco photons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoPhoton_e":             {"name":"RecoPhoton_e",                   "title":"Reco photon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_p":             {"name":"RecoPhoton_p",                   "title":"Reco photon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_pt":            {"name":"RecoPhoton_pt",                  "title":"Reco photon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "RecoPhoton_px":            {"name":"RecoPhoton_px",                  "title":"Reco photon p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_py":            {"name":"RecoPhoton_py",                  "title":"Reco photon p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_pz":            {"name":"RecoPhoton_pz",                  "title":"Reco photon p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoPhoton_y":             {"name":"RecoPhoton_y",                   "title":"Reco photon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoPhoton_eta":           {"name":"RecoPhoton_eta",                 "title":"Reco photon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_theta":         {"name":"RecoPhoton_theta",               "title":"Reco photon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoPhoton_phi":           {"name":"RecoPhoton_phi",                 "title":"Reco photon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_charge":        {"name":"RecoPhoton_charge",              "title":"Reco photon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},

    "RecoEmiss_px":             {"name":"RecoEmiss_px",                  "title":"Reco missing energy p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_py":             {"name":"RecoEmiss_py",                  "title":"Reco missing energy p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pz":             {"name":"RecoEmiss_pz",                  "title":"Reco missing energy p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "RecoEmiss_pt":             {"name":"RecoEmiss_pt",                  "title":"Reco missing energy p_{T} [GeV]",                    "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_p":              {"name":"RecoEmiss_p",                   "title":"Reco missing energy p [GeV]",                        "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_e":              {"name":"RecoEmiss_e",                   "title":"Reco missing energy energy [GeV]",                   "bin":60,"xmin":0 ,"xmax":240},
    "RecoEmiss_eta":            {"name":"RecoEmiss_eta",                 "title":"Reco missing energy #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_phi":            {"name":"RecoEmiss_phi",                 "title":"Reco missing energy #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_theta":          {"name":"RecoEmiss_theta",               "title":"Reco missing energy #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoEmiss_y":              {"name":"RecoEmiss_y",                   "title":"Reco missing energy rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoEmiss_costheta":       {"name":"RecoEmiss_costheta",               "title":"Reco missing energy |cos(#theta)|",                 "bin":50, "xmin":0,"xmax":1.},

    "Jets_R5_e":                {"name":"Jets_R5_e",                   "title":"Jets_{R5} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},   
    "Jets_R5_p":                {"name":"Jets_R5_p",                   "title":"Jets_{R5} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_pt":               {"name":"Jets_R5_pt",                  "title":"Jets_{R5} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_px":               {"name":"Jets_R5_px",                  "title":"Jets_{R5} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_py":               {"name":"Jets_R5_py",                  "title":"Jets_{R5} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_pz":               {"name":"Jets_R5_pz",                  "title":"Jets_{R5} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_eta":              {"name":"Jets_R5_eta",                 "title":"Jets_{R5} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_theta":            {"name":"Jets_R5_theta",               "title":"Jets_{R5} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "Jets_R5_phi":              {"name":"Jets_R5_phi",                 "title":"Jets_{R5} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_mass":             {"name":"Jets_R5_mass",                "title":"Jets_{R5} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_Jets_R5":                {"name":"n_Jets_R5",                   "title":"Number of Jets_{R5}",                     "bin":5, "xmin":-0.5, "xmax":4.5},
                                
    "Jets_R5_sel_e":            {"name":"Jets_R5_sel_e",                   "title":"not hadronic #tau Jets_{R5} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},    
    "Jets_R5_sel_p":            {"name":"Jets_R5_sel_p",                   "title":"not hadronic #tau Jets_{R5} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_sel_pt":           {"name":"Jets_R5_sel_pt",                  "title":"not hadronic #tau Jets_{R5} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "Jets_R5_sel_px":           {"name":"Jets_R5_sel_px",                  "title":"not hadronic #tau Jets_{R5} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_sel_py":           {"name":"Jets_R5_sel_py",                  "title":"not hadronic #tau Jets_{R5} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_sel_pz":           {"name":"Jets_R5_sel_pz",                  "title":"not hadronic #tau Jets_{R5} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_R5_sel_eta":          {"name":"Jets_R5_sel_eta",                 "title":"not hadronic #tau Jets_{R5} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_sel_theta":        {"name":"Jets_R5_sel_theta",               "title":"not hadronic #tau Jets_{R5} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "Jets_R5_sel_phi":          {"name":"Jets_R5_sel_phi",                 "title":"not hadronic #tau Jets_{R5} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_R5_sel_mass":         {"name":"Jets_R5_sel_mass",                "title":"not hadronic #tau Jets_{R5} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_Jets_R5_sel":            {"name":"n_Jets_R5_sel",                   "title":"Number of not hadronic #tau Jets_{R5}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "Jets_excl4_e":             {"name":"Jets_excl4_e",                   "title":"Jets_{kt} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},    
    "Jets_excl4_p":             {"name":"Jets_excl4_p",                   "title":"Jets_{kt} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "Jets_excl4_pt":            {"name":"Jets_excl4_pt",                  "title":"Jets_{kt} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "Jets_excl4_px":            {"name":"Jets_excl4_px",                  "title":"Jets_{kt} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_excl4_py":            {"name":"Jets_excl4_py",                  "title":"Jets_{kt} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_excl4_pz":            {"name":"Jets_excl4_pz",                  "title":"Jets_{kt} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "Jets_excl4_eta":           {"name":"Jets_excl4_eta",                 "title":"Jets_{kt} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_excl4_theta":         {"name":"Jets_excl4_theta",               "title":"Jets_{kt} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "Jets_excl4_phi":           {"name":"Jets_excl4_phi",                 "title":"Jets_{kt} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "Jets_excl4_mass":          {"name":"Jets_excl4_mass",                "title":"Jets_{kt} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_Jets_excl4":             {"name":"n_Jets_excl4",                   "title":"Number of Jets_{kt}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TauFromJet_R5_p":          {"name":"TauFromJet_R5_p",                   "title":"#tau from jet_{R5} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_pt":         {"name":"TauFromJet_R5_pt",                  "title":"#tau from jet_{R5} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_px":         {"name":"TauFromJet_R5_px",                  "title":"#tau from jet_{R5} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_py":         {"name":"TauFromJet_R5_py",                  "title":"#tau from jet_{R5} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_pz":         {"name":"TauFromJet_R5_pz",                  "title":"#tau from jet_{R5} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_R5_theta":      {"name":"TauFromJet_R5_theta",               "title":"#tau from jet_{R5} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_R5_phi":        {"name":"TauFromJet_R5_phi",                 "title":"#tau from jet_{R5} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_e":          {"name":"TauFromJet_R5_e",                   "title":"#tau from jet_{R5} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_R5_eta":        {"name":"TauFromJet_R5_eta",                 "title":"#tau from jet_{R5} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_y":          {"name":"TauFromJet_R5_y",                   "title":"#tau from jet_{R5} rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_R5_charge":     {"name":"TauFromJet_R5_charge",              "title":"#tau from jet_{R5} charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_R5_type":       {"name":"TauFromJet_R5_type",                "title":"#tau from jet_{R5} decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_R5_mass":       {"name":"TauFromJet_R5_mass",                "title":"#tau from jet_{R5} mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_R5":          {"name":"n_TauFromJet_R5",                   "title":"Number of #tau from Jets_{R5}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TauFromJet_p":             {"name":"TauFromJet_p",                   "title":"#tau from jet_{kt} p [GeV]",                        "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_pt":            {"name":"TauFromJet_pt",                  "title":"#tau from jet_{kt} p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_px":            {"name":"TauFromJet_px",                  "title":"#tau from jet_{kt} p_{x} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_py":            {"name":"TauFromJet_py",                  "title":"#tau from jet_{kt} p_{y} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_pz":            {"name":"TauFromJet_pz",                  "title":"#tau from jet_{kt} p_{z} [GeV]",                    "bin":50,"xmin":-100 ,"xmax":100},
    "TauFromJet_theta":         {"name":"TauFromJet_theta",               "title":"#tau from jet_{kt} #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_phi":           {"name":"TauFromJet_phi",                 "title":"#tau from jet_{kt} #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_eta":           {"name":"TauFromJet_eta",                 "title":"#tau from jet_{kt} #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_y":             {"name":"TauFromJet_y",                   "title":"#tau from jet_{kt} rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_e":             {"name":"TauFromJet_e",                   "title":"#tau from jet_{kt} energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":100},
    "TauFromJet_charge":        {"name":"TauFromJet_charge",              "title":"#tau from jet_{kt} charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_type":          {"name":"TauFromJet_type",                "title":"#tau from jet_{kt} decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_mass":          {"name":"TauFromJet_mass",                "title":"#tau from jet_{kt} mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TauFromJet":             {"name":"n_TauFromJet",                   "title":"Number of #tau from Jets_{kt}",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "RecoZ_px":                 {"name":"RecoZ_px",                 "title":"Reco Z p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_py":                 {"name":"RecoZ_py",                 "title":"Reco Z p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_pz":                 {"name":"RecoZ_pz",                 "title":"Reco Z p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoZ_p":                  {"name":"RecoZ_p",                  "title":"Reco Z p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_pt":                 {"name":"RecoZ_pt",                 "title":"Reco Z p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_e":                  {"name":"RecoZ_e",                  "title":"Reco Z energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoZ_eta":                {"name":"RecoZ_eta",                "title":"Reco Z #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ_phi":                {"name":"RecoZ_phi",                "title":"Reco Z #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ_theta":              {"name":"RecoZ_theta",              "title":"Reco Z #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZ_y":                  {"name":"RecoZ_y",                  "title":"Reco Z rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoZ_mass":               {"name":"RecoZ_mass",               "title":"Reco Z mass",                   "bin":100, "xmin":50., "xmax":150},

    "RecoZ1_px":               {"name":"RecoZ1_px",                 "title":"Reco first Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZ1_py":               {"name":"RecoZ1_py",                 "title":"Reco first Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZ1_pz":               {"name":"RecoZ1_pz",                 "title":"Reco first Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "RecoZ1_p":                {"name":"RecoZ1_p",                  "title":"Reco first Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZ1_pt":               {"name":"RecoZ1_pt",                 "title":"Reco first Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZ1_e":                {"name":"RecoZ1_e",                  "title":"Reco first Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZ1_eta":              {"name":"RecoZ1_eta",                "title":"Reco first Z daughter #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ1_phi":              {"name":"RecoZ1_phi",                "title":"Reco first Z daughter #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ1_theta":            {"name":"RecoZ1_theta",              "title":"Reco first Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZ1_y":                {"name":"RecoZ1_y",                  "title":"Reco first Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZ1_mass":             {"name":"RecoZ1_mass",               "title":"Reco first Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},

    "RecoZ2_px":                {"name":"RecoZ2_px",                 "title":"Reco second Z daughter p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZ2_py":                {"name":"RecoZ2_py",                 "title":"Reco second Z daughter p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZ2_pz":                {"name":"RecoZ2_pz",                 "title":"Reco second Z daughter p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "RecoZ2_p":                 {"name":"RecoZ2_p",                  "title":"Reco second Z daughter p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "RecoZ2_pt":                {"name":"RecoZ2_pt",                 "title":"Reco second Z daughter p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "RecoZ2_e":                 {"name":"RecoZ2_e",                  "title":"Reco second Z daughter energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "RecoZ2_eta":               {"name":"RecoZ2_eta",                "title":"Reco second Z daughter #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ2_phi":               {"name":"RecoZ2_phi",                "title":"Reco second Z daughter #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZ2_theta":             {"name":"RecoZ2_theta",              "title":"Reco second Z daughter #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoZ2_y":                 {"name":"RecoZ2_y",                  "title":"Reco second Z daughter rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "RecoZ2_mass":              {"name":"RecoZ2_mass",               "title":"Reco second Z daughter mass",                   "bin":30, "xmin":0., "xmax":3.},
                                
    "RecoH_px":                 {"name":"RecoH_px",                 "title":"Reco H p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_py":                 {"name":"RecoH_py",                 "title":"Reco H p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_pz":                 {"name":"RecoH_pz",                 "title":"Reco H p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},
    "RecoH_p":                  {"name":"RecoH_p",                  "title":"Reco H p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_pt":                 {"name":"RecoH_pt",                 "title":"Reco H p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_e":                  {"name":"RecoH_e",                  "title":"Reco H energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "RecoH_eta":                {"name":"RecoH_eta",                "title":"Reco H #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_phi":                {"name":"RecoH_phi",                "title":"Reco H #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_theta":              {"name":"RecoH_theta",              "title":"Reco H #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoH_y":                  {"name":"RecoH_y",                  "title":"Reco H rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoH_mass":               {"name":"RecoH_mass",               "title":"Reco H mass",                   "bin":75, "xmin":0 ,"xmax":150},

    "TauLead_px":               {"name":"TauLead_px",                 "title":"#tau_{lead} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_py":               {"name":"TauLead_py",                 "title":"#tau_{lead} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_pz":               {"name":"TauLead_pz",                 "title":"#tau_{lead} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100},   
    "TauLead_p":                {"name":"TauLead_p",                  "title":"#tau_{lead} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_pt":               {"name":"TauLead_pt",                 "title":"#tau_{lead} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauLead_e":                {"name":"TauLead_e",                  "title":"#tau_{lead} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauLead_eta":              {"name":"TauLead_eta",                "title":"#tau_{lead} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_phi":              {"name":"TauLead_phi",                "title":"#tau_{lead} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_theta":            {"name":"TauLead_theta",              "title":"#tau_{lead} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauLead_y":                {"name":"TauLead_y",                  "title":"#tau_{lead} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauLead_mass":             {"name":"TauLead_mass",               "title":"#tau_{lead} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauSub_px":                {"name":"TauSub_px",                 "title":"#tau_{sublead} p_{x} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_py":                {"name":"TauSub_py",                 "title":"#tau_{sublead} p_{y} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_pz":                {"name":"TauSub_pz",                 "title":"#tau_{sublead} p_{z} [GeV]",            "bin":50,"xmin":-100 ,"xmax":100}, 
    "TauSub_p":                 {"name":"TauSub_p",                  "title":"#tau_{sublead} p [GeV]",                "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_pt":                {"name":"TauSub_pt",                 "title":"#tau_{sublead} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":100},
    "TauSub_e":                 {"name":"TauSub_e",                  "title":"#tau_{sublead} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauSub_eta":               {"name":"TauSub_eta",                "title":"#tau_{sublead} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_phi":               {"name":"TauSub_phi",                "title":"#tau_{sublead} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_theta":             {"name":"TauSub_theta",              "title":"#tau_{sublead} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauSub_y":                 {"name":"TauSub_y",                  "title":"#tau_{sublead} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauSub_mass":              {"name":"TauSub_mass",               "title":"#tau_{sublead} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "Tau_Acoplanarity":         {"name":"Tau_Acoplanarity",           "title":"#Delta#phi(#tau#tau)",                "bin":32, "xmin":-3.2,"xmax":3.2},
    "Tau_DR":                   {"name":"Tau_DR",                     "title":"#Delta R(#tau#tau)",                  "bin":70, "xmin":0,"xmax":7},
    "Tau_cos":                  {"name":"Tau_cos",                    "title":"cos#theta(#tau#tau)",                 "bin":100, "xmin":-1.,"xmax":1.},

    "Recoil":                   {"name":"Recoil",                   "title":"M_{recoil} [GeV]",                     "bin":80, "xmin":80., "xmax":160.},
    "Collinear_mass":           {"name":"Collinear_mass",           "title":"M_{collinear} [GeV]",                  "bin":150, "xmin":50., "xmax":200.},

    #### CP variables

    "GenZ_e":                       {"name":"GenZ_e",                  "title":"Gen Z energy [GeV]",           "bin":75, "xmin":0 ,"xmax":150},
    "GenZ_p":                       {"name":"GenZ_p",                  "title":"Gen Z p [GeV]",                "bin":75, "xmin":0 ,"xmax":150},
    "GenZ_pt":                      {"name":"GenZ_pt",                 "title":"Gen Z p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":150},
    "GenZ_px":                      {"name":"GenZ_px",                 "title":"Gen Z p_{x} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenZ_py":                      {"name":"GenZ_py",                 "title":"Gen Z p_{y} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenZ_pz":                      {"name":"GenZ_pz",                 "title":"Gen Z p_{z} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenZ_y":                       {"name":"GenZ_y",                  "title":"Gen Z rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "GenZ_mass":                    {"name":"GenZ_y",                  "title":"Gen Z M [GeV]",                "bin":50, "xmin":90, "xmax":140},
    "GenZ_eta":                     {"name":"GenZ_eta",                "title":"Gen Z #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenZ_theta":                   {"name":"GenZ_theta",              "title":"Gen Z #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "GenZ_phi":                     {"name":"GenZ_phi",                "title":"Gen Z #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},

    "GenTau_DEta":              {"name":"GenTau_DEta",              "title":"Gen di-#tau #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenTau_Acoplanarity":              {"name":"GenTau_Acoplanarity",              "title":"Gen di-#tau #Delta#phi",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenTau_cos":               {"name":"GenTau_cos",               "title":"Gen di-#tau cos#theta",                   "bin":100, "xmin":-1.,"xmax":1.},
    "GenTau_DR":                {"name":"GenTau_DR",                "title":"Gen di-#tau #Delta R",                    "bin":70, "xmin":0,"xmax":7.},

    "GenTau_DEta":           {"name":"GenTau_DEta",           "title":"Gen di-#tau #Delta#eta in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenTau_Acoplanarity":           {"name":"GenTau_Acoplanarity",           "title":"Gen di-#tau #Delta#phi in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "HRF_GenTau_px":                 {"name":"HRF_GenTau_px",                 "title":"Gen #tau p_{x} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_GenTau_py":                 {"name":"HRF_GenTau_py",                 "title":"Gen #tau p_{y} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_GenTau_pz":                 {"name":"HRF_GenTau_pz",                 "title":"Gen #tau p_{z} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_GenTau_p":                  {"name":"HRF_GenTau_p",                  "title":"Gen #tau p [GeV] in H rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "HRF_GenTau_pt":                 {"name":"HRF_GenTau_pt",                 "title":"Gen #tau p_{T} [GeV] in H rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "HRF_GenTau_e":                  {"name":"HRF_GenTau_e",                  "title":"Gen #tau energy [GeV] in H rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "HRF_GenTau_eta":                {"name":"HRF_GenTau_eta",                "title":"Gen #tau #eta in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_GenTau_phi":                {"name":"HRF_GenTau_phi",                "title":"Gen #tau #phi in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_GenTau_theta":              {"name":"HRF_GenTau_theta",              "title":"Gen #tau #theta in H rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "HRF_GenTau_y":                  {"name":"HRF_GenTau_y",                  "title":"Gen #tau rapidity in H rest frame",               "bin":40, "xmin":-4., "xmax":4.},

    "ZRF_GenZDaughter_px":                 {"name":"ZRF_GenZDaughter_px",                 "title":"Gen electron p_{x} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_GenZDaughter_py":                 {"name":"ZRF_GenZDaughter_py",                 "title":"Gen electron p_{y} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_GenZDaughter_pz":                 {"name":"ZRF_GenZDaughter_pz",                 "title":"Gen electron p_{z} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_GenZDaughter_p":                  {"name":"ZRF_GenZDaughter_p",                  "title":"Gen electron p [GeV] in Z rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_GenZDaughter_pt":                 {"name":"ZRF_GenZDaughter_pt",                 "title":"Gen electron p_{T} [GeV] in Z rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_GenZDaughter_e":                  {"name":"ZRF_GenZDaughter_e",                  "title":"Gen electron energy [GeV] in Z rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_GenZDaughter_eta":                {"name":"ZRF_GenZDaughter_eta",                "title":"Gen electron #eta in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_GenZDaughter_phi":                {"name":"ZRF_GenZDaughter_phi",                "title":"Gen electron #phi in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_GenZDaughter_theta":              {"name":"ZRF_GenZDaughter_theta",              "title":"Gen electron #theta in Z rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "ZRF_GenZDaughter_y":                  {"name":"ZRF_GenZDaughter_y",                  "title":"Gen electron rapidity in Z rest frame",               "bin":40, "xmin":-4., "xmax":4.},
    
        
    "HRF_GenTau_DEta":                   {"name":"HRF_GenTau_DEta",           "title":"Gen di-#tau #Delta#eta in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_GenTau_Acoplanarity":           {"name":"HRF_GenTau_Acoplanarity",           "title":"Gen di-#tau #Delta#phi in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "GenThetastar":           {"name":"GenThetastar",         "title":"Gen #theta^{*}",                  "bin":32, "xmin":0,"xmax":3.2},
    "GenTheta2":              {"name":"GenTheta2",            "title":"Gen #theta_{2}",                  "bin":32, "xmin":0,"xmax":3.2},
    "GenPhi1":                {"name":"GenPhi1",              "title":"Gen #phi_{1}",                    "bin":32, "xmin":0,"xmax":3.2},
    "GenPhi":                 {"name":"GenPhi",               "title":"Gen #phi",                        "bin":32, "xmin":0,"xmax":3.2},
    "GenTheta1":              {"name":"GenTheta1",            "title":"Gen #theta_{1}",                  "bin":32, "xmin":0,"xmax":3.2},

    "GenThetastar_cos":           {"name":"GenThetastar_cos",         "title":"Gen cos#theta^{*}",                  "bin":50, "xmin":-1.,"xmax":1.},
    "GenTheta2_cos":              {"name":"GenTheta2_cos",            "title":"Gen cos#theta_{2}",                  "bin":50, "xmin":-1.,"xmax":1.},
    "GenPhi1_cos":                {"name":"GenPhi1_cos",              "title":"Gen cos#phi_{1}",                    "bin":50, "xmin":-1.,"xmax":1.},
    "GenPhi_cos":                 {"name":"GenPhi_cos",               "title":"Gen cos#phi",                        "bin":50, "xmin":-1.,"xmax":1.},
    "GenTheta1_cos":              {"name":"GenTheta1_cos",            "title":"Gen cos#theta_{1}",                  "bin":50, "xmin":-1.,"xmax":1.},

    "Tau_DEta":                             {"name":"Tau_DEta",           "title":"Reco di-#tau #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZDaughter_DEta":                   {"name":"RecoZDaughter_DEta",           "title":"Reco di-electron #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoZDaughter_Acoplanarity":           {"name":"RecoZDaughter_Acoplanarity",           "title":"Reco di-electron #Delta#phi",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "HRF_Tau_px":                 {"name":"HRF_Tau_px",                 "title":"Reco #tau p_{x} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_Tau_py":                 {"name":"HRF_Tau_py",                 "title":"Reco #tau p_{y} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_Tau_pz":                 {"name":"HRF_Tau_pz",                 "title":"Reco #tau p_{z} [GeV] in H rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "HRF_Tau_p":                  {"name":"HRF_Tau_p",                  "title":"Reco #tau p [GeV] in H rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "HRF_Tau_pt":                 {"name":"HRF_Tau_pt",                 "title":"Reco #tau p_{T} [GeV] in H rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "HRF_Tau_e":                  {"name":"HRF_Tau_e",                  "title":"Reco #tau energy [GeV] in H rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "HRF_Tau_eta":                {"name":"HRF_Tau_eta",                "title":"Reco #tau #eta in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_Tau_phi":                {"name":"HRF_Tau_phi",                "title":"Reco #tau #phi in H rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_Tau_theta":              {"name":"HRF_Tau_theta",              "title":"Reco #tau #theta in H rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "HRF_Tau_y":                  {"name":"HRF_Tau_y",                  "title":"Reco #tau rapidity in H rest frame",               "bin":40, "xmin":-4., "xmax":4.},
        
    "HRF_Tau_DEta":                   {"name":"HRF_Tau_DEta",           "title":"Reco di-#tau #Delta#eta in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "HRF_Tau_Acoplanarity":           {"name":"HRF_Tau_Acoplanarity",           "title":"Reco di-#tau #Delta#phi in H rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},

    "ZRF_RecoZDaughter_px":                 {"name":"ZRF_RecoZDaughter_px",                 "title":"Reco electron p_{x} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZDaughter_py":                 {"name":"ZRF_RecoZDaughter_py",                 "title":"Reco electron p_{y} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZDaughter_pz":                 {"name":"ZRF_RecoZDaughter_pz",                 "title":"Reco electron p_{z} [GeV] in Z rest frame",            "bin":50,"xmin":-100 ,"xmax":100},
    "ZRF_RecoZDaughter_p":                  {"name":"ZRF_RecoZDaughter_p",                  "title":"Reco electron p [GeV] in Z rest frame",                "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZDaughter_pt":                 {"name":"ZRF_RecoZDaughter_pt",                 "title":"Reco electron p_{T} [GeV] in Z rest frame",            "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZDaughter_e":                  {"name":"ZRF_RecoZDaughter_e",                  "title":"Reco electron energy [GeV] in Z rest frame",           "bin":75, "xmin":0 ,"xmax":150},
    "ZRF_RecoZDaughter_eta":                {"name":"ZRF_RecoZDaughter_eta",                "title":"Reco electron #eta in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZDaughter_phi":                {"name":"ZRF_RecoZDaughter_phi",                "title":"Reco electron #phi in Z rest frame",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZDaughter_theta":              {"name":"ZRF_RecoZDaughter_theta",              "title":"Reco electron #theta in Z rest frame",                 "bin":16, "xmin":0,"xmax":3.2},
    "ZRF_RecoZDaughter_y":                  {"name":"ZRF_RecoZDaughter_y",                  "title":"Reco electron rapidity in Z rest frame",               "bin":40, "xmin":-4., "xmax":4.},
        
    "ZRF_RecoZDaughter_DEta":                   {"name":"ZRF_RecoZDaughter_DEta",           "title":"Reco di-electron #Delta#eta in Z rest frame",                  "bin":32, "xmin":-3.2,"xmax":3.2},
    "ZRF_RecoZDaughter_Acoplanarity":           {"name":"ZRF_RecoZDaughter_Acoplanarity",           "title":"Reco di-electron #Delta#phi in Z rest frame",          "bin":32, "xmin":-3.2,"xmax":3.2},

    "RecoThetastar":           {"name":"RecoThetastar",         "title":"Reco #theta^{*}",                  "bin":32, "xmin":0,"xmax":3.2},
    "RecoTheta2":              {"name":"RecoTheta2",            "title":"Reco #theta_{2}",                  "bin":32, "xmin":0,"xmax":3.2},
    "RecoPhi1":                {"name":"RecoPhi1",              "title":"Reco #phi_{1}",                    "bin":32, "xmin":0,"xmax":3.2},
    "RecoPhi":                 {"name":"RecoPhi",               "title":"Reco #phi",                        "bin":32, "xmin":0,"xmax":3.2},
    "RecoTheta1":              {"name":"RecoTheta1",            "title":"Reco #theta_{1}",                  "bin":32, "xmin":0,"xmax":3.2},

    "RecoThetastar_cos":           {"name":"RecoThetastar_cos",         "title":"Reco cos#theta^{*}",                  "bin":50, "xmin":-1.,"xmax":1.},
    "RecoTheta2_cos":              {"name":"RecoTheta2_cos",            "title":"Reco cos#theta_{2}",                  "bin":50, "xmin":-1.,"xmax":1.},
    "RecoPhi1_cos":                {"name":"RecoPhi1_cos",              "title":"Reco cos#phi_{1}",                    "bin":50, "xmin":-1.,"xmax":1.},
    "RecoPhi_cos":                 {"name":"RecoPhi_cos",               "title":"Reco cos#phi",                        "bin":50, "xmin":-1.,"xmax":1.},
    "RecoTheta1_cos":              {"name":"RecoTheta1_cos",            "title":"Reco cos#theta_{1}",                  "bin":50, "xmin":-1.,"xmax":1.},

}
