#Input directory where the files produced at the stage1 level are
inputDir = "/ceph/awiedl/FCCee/HiggsCP/ecm365/ktN-explicit/stage2_280125/NuNu/LL"

outputDir = "/ceph/sgiappic/HiggsCP/ecm365/ktN-explicit/final_280125/NuNu/LL"

#Integrated luminosity for scaling number of events (required only if setting doScale to true)
intLumi = 2.65e6 #pb^-1 #to be checked again for 240 gev

#Scale event yields by intLumi and cross section (optional)
# if scaling, both the number of events in the table and in the histograms will be scaled
doScale = True

#Save event yields in a table (optional)
saveTabular = False

#Number of CPUs to use
#nCPUs = 6

#produces ROOT TTrees, default is False
doTree = False

processList = {

    'p8_ee_WW_ecm365':{},
    'p8_ee_Zqq_ecm365':{},
    'p8_ee_ZZ_ecm365':{},
    'p8_ee_Zbb_ecm365':{},
    'p8_ee_Zcc_ecm365':{},
    'p8_ee_Zss_ecm365':{},
    'p8_ee_tt_ecm365':{},
    
    'wzp6_ee_tautau_ecm365':{},
    'wzp6_ee_mumu_ecm365':{},
    'wzp6_ee_ee_Mee_30_150_ecm365':{},

    'wzp6_ee_tautauH_Htautau_ecm365': {},
    'wzp6_ee_tautauH_Hbb_ecm365': {},
    'wzp6_ee_tautauH_Hcc_ecm365': {},
    'wzp6_ee_tautauH_Hss_ecm365': {},
    'wzp6_ee_tautauH_Hgg_ecm365': {},
    'wzp6_ee_tautauH_HWW_ecm365': {},
    'wzp6_ee_tautauH_HZZ_ecm365': {},

    'wzp6_egamma_eZ_Zmumu_ecm365': {},
    'wzp6_egamma_eZ_Zee_ecm365': {},
    'wzp6_gammae_eZ_Zmumu_ecm365': {},
    'wzp6_gammae_eZ_Zee_ecm365': {},

    'wzp6_gaga_tautau_60_ecm365': {},
    'wzp6_gaga_mumu_60_ecm365': {},
    'wzp6_gaga_ee_60_ecm365': {},

    'wzp6_ee_nuenueZ_ecm365': {},
    'wzp6_ee_nunuH_Htautau_ecm365': {},
    'wzp6_ee_nunuH_Hbb_ecm365': {},
    'wzp6_ee_nunuH_Hcc_ecm365': {},
    'wzp6_ee_nunuH_Hss_ecm365': {},
    'wzp6_ee_nunuH_Hgg_ecm365': {},
    'wzp6_ee_nunuH_HWW_ecm365': {},
    'wzp6_ee_nunuH_HZZ_ecm365': {},

    'wzp6_ee_eeH_Htautau_ecm365': {},
    'wzp6_ee_eeH_Hbb_ecm365': {},
    'wzp6_ee_eeH_Hcc_ecm365': {},
    'wzp6_ee_eeH_Hss_ecm365': {},
    'wzp6_ee_eeH_Hgg_ecm365': {},
    'wzp6_ee_eeH_HWW_ecm365': {},
    'wzp6_ee_eeH_HZZ_ecm365': {},

    'wzp6_ee_mumuH_Htautau_ecm365': {},
    'wzp6_ee_mumuH_Hbb_ecm365': {},
    'wzp6_ee_mumuH_Hcc_ecm365': {},
    'wzp6_ee_mumuH_Hss_ecm365': {},
    'wzp6_ee_mumuH_Hgg_ecm365': {},
    'wzp6_ee_mumuH_HWW_ecm365': {},
    'wzp6_ee_mumuH_HZZ_ecm365': {},

    'wzp6_ee_bbH_Htautau_ecm365': {},
    'wzp6_ee_bbH_Hbb_ecm365': {},
    'wzp6_ee_bbH_Hcc_ecm365': {},
    'wzp6_ee_bbH_Hss_ecm365': {},
    'wzp6_ee_bbH_Hgg_ecm365': {},
    'wzp6_ee_bbH_HWW_ecm365': {},
    'wzp6_ee_bbH_HZZ_ecm365': {},

    'wzp6_ee_ccH_Htautau_ecm365': {},
    'wzp6_ee_ccH_Hbb_ecm365': {},
    'wzp6_ee_ccH_Hcc_ecm365': {},
    'wzp6_ee_ccH_Hss_ecm365': {},
    'wzp6_ee_ccH_Hgg_ecm365': {},
    'wzp6_ee_ccH_HWW_ecm365': {},
    'wzp6_ee_ccH_HZZ_ecm365': {},

    'wzp6_ee_ssH_Htautau_ecm365': {},
    'wzp6_ee_ssH_Hbb_ecm365': {},
    'wzp6_ee_ssH_Hcc_ecm365': {},
    'wzp6_ee_ssH_Hss_ecm365': {},
    'wzp6_ee_ssH_Hgg_ecm365': {},
    'wzp6_ee_ssH_HWW_ecm365': {},
    'wzp6_ee_ssH_HZZ_ecm365': {},

    'wzp6_ee_qqH_Htautau_ecm365': {},
    'wzp6_ee_qqH_Hbb_ecm365': {},
    'wzp6_ee_qqH_Hcc_ecm365': {},
    'wzp6_ee_qqH_Hss_ecm365': {},
    'wzp6_ee_qqH_Hgg_ecm365': {},
    'wzp6_ee_qqH_HWW_ecm365': {},
    'wzp6_ee_qqH_HZZ_ecm365': {},

    'wzp6_ee_nuenueH_Htautau_ecm365': {},
    'wzp6_ee_nuenueH_Hbb_ecm365': {},
    'wzp6_ee_nuenueH_Hcc_ecm365': {},
    'wzp6_ee_nuenueH_Hss_ecm365': {},
    'wzp6_ee_nuenueH_Hgg_ecm365': {},
    'wzp6_ee_nuenueH_HWW_ecm365': {},
    'wzp6_ee_nuenueH_HZZ_ecm365': {},  

    'wzp6_ee_numunumuH_Htautau_ecm365': {},
    'wzp6_ee_numunumuH_Hbb_ecm365': {},
    'wzp6_ee_numunumuH_Hcc_ecm365': {},
    'wzp6_ee_numunumuH_Hss_ecm365': {},
    'wzp6_ee_numunumuH_Hgg_ecm365': {},
    'wzp6_ee_numunumuH_HWW_ecm365': {},
    'wzp6_ee_numunumuH_HZZ_ecm365': {},
}

###Dictionary for prettier names of processes (optional)
#change them if you want but they don't do anything
processLabels = {}

#Link to the dictonary that contains all the cross section information etc...
procDict = "FCCee_procDict_winter2023_IDEA.json"

#Add provate samples as it is not an offical process
procDictAdd = {}

###Dictionnay of the list of cuts. The key is the name of the selection that will be added to the output file
cutList = {
    ### no selection, just builds the histograms, it will not be shown in the latex table
    "selReco": "true",
    #"selReco_100Me": "RecoEmiss_e>100",
    #"selReco_100Me_TauDPhi3": "RecoEmiss_e>100 && abs(Tau_DPhi)<3",
    #"selReco_100Me_TauDPhi3_2DR": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2",
    #"selReco_100Me_TauDPhi3_2DR_cos0.4": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4",
    #"selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4 && RecoEmiss_costheta<0.98",
    #"selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98_missy1": "RecoEmiss_e>100 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4 && RecoEmiss_costheta<0.98 && abs(RecoEmiss_y)<1",
    #"selReco_152Me_TauDPhi3_2DR_cos0.4_misscos0.98_missy1": "RecoEmiss_e>152 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4 && RecoEmiss_costheta<0.98 && abs(RecoEmiss_y)<1",
    #"selReco_152Me_TauDPhi3_2DR_cos0.4_misscos0.92_missy1": "RecoEmiss_e>152 && abs(Tau_DPhi)<3 && Tau_DR>2 && Tau_cos<-0.4 && RecoEmiss_costheta<0.92 && abs(RecoEmiss_y)<1",
    
}

# Dictionary for prettier names of cuts (optional)
### needs to be in the same order as cutList or the table won't be organised well, it's only for the table ###
cutLabels = {
    "selReco": "No additional selection",
    "selReco_100Me": "E_{miss}>100 GeV",
    "selReco_100Me_TauDPhi3": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3",
    "selReco_100Me_TauDPhi3_2DR": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2",
    "selReco_100Me_TauDPhi3_2DR_cos0": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2, cos#theta_{#tau}<0}",
    "selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2, cos#theta_{#tau}<0}, |cos#theta_{miss}|<0.98}",
    "selReco_100Me_TauDPhi3_2DR_cos0.4_misscos0.98_missy1": "E_{miss}>100 GeV, |#Delta#phi_{#tau}|<3, #Delta R_{#tau}>2, cos#theta_{#tau}<0}, |cos#theta_{miss}|<0.98} && |y_{miss}|<1",
}

###Dictionary for the ouput variable/hitograms. The key is the name of the variable in the output files. "name" is the name of the variable in the input file, "title" is the x-axis label of the histogram, "bin" the number of bins of the histogram, "xmin" the minimum x-axis value and "xmax" the maximum x-axis value.
histoList = {
    ######## Monte-Carlo particles #######
    "n_FSGenElectron":                  {"name":"n_FSGenElectron",                  "title":"Number of final state gen electrons",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenElectron_e":                  {"name":"FSGenElectron_e",                  "title":"Final state gen electrons energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenElectron_p":                  {"name":"FSGenElectron_p",                  "title":"Final state gen electrons p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenElectron_pt":                 {"name":"FSGenElectron_pt",                 "title":"Final state gen electrons p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenElectron_px":                 {"name":"FSGenElectron_px",                 "title":"Final state gen electrons p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenElectron_py":                 {"name":"FSGenElectron_py",                 "title":"Final state gen electrons p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenElectron_pz":                 {"name":"FSGenElectron_pz",                 "title":"Final state gen electrons p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenElectron_y":                  {"name":"FSGenElectron_y",                  "title":"Final state gen electrons rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenElectron_eta":                {"name":"FSGenElectron_eta",                "title":"Final state gen electrons #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenElectron_theta":              {"name":"FSGenElectron_theta",              "title":"Final state gen electrons #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenElectron_phi":                {"name":"FSGenElectron_phi",                "title":"Final state gen electrons #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenElectron_charge":             {"name":"FSGenElectron_charge",             "title":"Final state gen electrons charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
    "FSGenElectron_mass":               {"name":"FSGenElectron_mass",               "title":"Final state gen electrons mass [GeV]",             "bin":20, "xmin":0., "xmax":2.},
    "FSGenElectron_parentPDG":          {"name":"FSGenElectron_parentPDG",          "title":"Final state gen electrons parent PDG",             "bin":30, "xmin":0., "xmax":30.},
    "FSGenElectron_vertex_x":           {"name":"FSGenElectron_vertex_x", "title":"Final state gen e^{#font[122]{\55}} production vertex x [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenElectron_vertex_y":           {"name":"FSGenElectron_vertex_y", "title":"Final state gen e^{#font[122]{\55}} production vertex y [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenElectron_vertex_z":           {"name":"FSGenElectron_vertex_z", "title":"Final state gen e^{#font[122]{\55}} production vertex z [mm]",   "bin":100, "xmin":-2000, "xmax":2000},

    "n_FSGenMuon":                      {"name":"n_FSGenMuon",                  "title":"Number of final state gen muons",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenMuon_e":                      {"name":"FSGenMuon_e",                  "title":"Final state gen muons energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenMuon_p":                      {"name":"FSGenMuon_p",                  "title":"Final state gen muons p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenMuon_pt":                     {"name":"FSGenMuon_pt",                 "title":"Final state gen muons p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenMuon_px":                     {"name":"FSGenMuon_px",                 "title":"Final state gen muons p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenMuon_py":                     {"name":"FSGenMuon_py",                 "title":"Final state gen muons p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenMuon_pz":                     {"name":"FSGenMuon_pz",                 "title":"Final state gen muons p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenMuon_y":                      {"name":"FSGenMuon_y",                  "title":"Final state gen muons rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenMuon_eta":                    {"name":"FSGenMuon_eta",                "title":"Final state gen muons #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenMuon_theta":                  {"name":"FSGenMuon_theta",              "title":"Final state gen muons #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenMuon_phi":                    {"name":"FSGenMuon_phi",                "title":"Final state gen muons #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenMuon_charge":                 {"name":"FSGenMuon_charge",             "title":"Final state gen muons charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
    "FSGenMuon_mass":                   {"name":"FSGenMuon_mass",               "title":"Final state gen muons mass [GeV]",             "bin":20, "xmin":0., "xmax":2.},
    "FSGenMuon_parentPDG":              {"name":"FSGenMuon_parentPDG",          "title":"Final state gen muons parent PDG",             "bin":30, "xmin":0., "xmax":30.},
    "FSGenMuon_vertex_x":               {"name":"FSGenMuon_vertex_x", "title":"Final state gen #mu^{#font[122]{\55}} production vertex x [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenMuon_vertex_y":               {"name":"FSGenMuon_vertex_y", "title":"Final state gen #mu^{#font[122]{\55}} production vertex y [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "FSGenMuon_vertex_z":               {"name":"FSGenMuon_vertex_z", "title":"Final state gen #mu^{#font[122]{\55}} production vertex z [mm]",   "bin":100, "xmin":-2000, "xmax":2000},

    "n_HiggsGenTau":                      {"name":"n_HiggsGenTau",                  "title":"Number of final state gen taus",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "HiggsGenTau_e":                      {"name":"HiggsGenTau_e",                  "title":"Final state gen taus energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "HiggsGenTau_p":                      {"name":"HiggsGenTau_p",                  "title":"Final state gen taus p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "HiggsGenTau_pt":                     {"name":"HiggsGenTau_pt",                 "title":"Final state gen taus p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "HiggsGenTau_px":                     {"name":"HiggsGenTau_px",                 "title":"Final state gen taus p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "HiggsGenTau_py":                     {"name":"HiggsGenTau_py",                 "title":"Final state gen taus p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "HiggsGenTau_pz":                     {"name":"HiggsGenTau_pz",                 "title":"Final state gen taus p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "HiggsGenTau_y":                      {"name":"HiggsGenTau_y",                  "title":"Final state gen taus rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "HiggsGenTau_eta":                    {"name":"HiggsGenTau_eta",                "title":"Final state gen taus #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HiggsGenTau_theta":                  {"name":"HiggsGenTau_theta",              "title":"Final state gen taus #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "HiggsGenTau_phi":                    {"name":"HiggsGenTau_phi",                "title":"Final state gen taus #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "HiggsGenTau_charge":                 {"name":"HiggsGenTau_charge",             "title":"Final state gen taus charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
    "HiggsGenTau_mass":                   {"name":"HiggsGenTau_mass",               "title":"Final state gen taus mass [GeV]",             "bin":20, "xmin":0., "xmax":2.},
    "HiggsGenTau_parentPDG":              {"name":"HiggsGenTau_parentPDG",          "title":"Final state gen taus parent PDG",             "bin":30, "xmin":0., "xmax":30.},
    "HiggsGenTau_vertex_x":               {"name":"HiggsGenTau_vertex_x", "title":"Final state gen #tau^{#font[122]{\55}} production vertex x [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "HiggsGenTau_vertex_y":               {"name":"HiggsGenTau_vertex_y", "title":"Final state gen #tau^{#font[122]{\55}} production vertex y [mm]",   "bin":100, "xmin":-2000, "xmax":2000},
    "HiggsGenTau_vertex_z":               {"name":"HiggsGenTau_vertex_z", "title":"Final state gen #tau^{#font[122]{\55}} production vertex z [mm]",   "bin":100, "xmin":-2000, "xmax":2000},

    "n_FSGenNeutrino":                  {"name":"n_FSGenNeutrino",                  "title":"Number of final state gen neutrinos",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenNeutrino_e":                  {"name":"FSGenNeutrino_e",                  "title":"Final state gen neutrinos energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenNeutrino_p":                  {"name":"FSGenNeutrino_p",                  "title":"Final state gen neutrinos p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenNeutrino_pt":                 {"name":"FSGenNeutrino_pt",                 "title":"Final state gen neutrinos p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenNeutrino_px":                 {"name":"FSGenNeutrino_px",                 "title":"Final state gen neutrinos p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenNeutrino_py":                 {"name":"FSGenNeutrino_py",                 "title":"Final state gen neutrinos p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenNeutrino_pz":                 {"name":"FSGenNeutrino_pz",                 "title":"Final state gen neutrinos p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenNeutrino_y":                  {"name":"FSGenNeutrino_y",                  "title":"Final state gen neutrinos rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenNeutrino_eta":                {"name":"FSGenNeutrino_eta",                "title":"Final state gen neutrinos #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenNeutrino_theta":              {"name":"FSGenNeutrino_theta",              "title":"Final state gen neutrinos #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenNeutrino_phi":                {"name":"FSGenNeutrino_phi",                "title":"Final state gen neutrinos #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenNeutrino_charge":             {"name":"FSGenNeutrino_charge",             "title":"Final state gen neutrinos charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},
                                        
    "n_FSGenPhoton":                    {"name":"n_FSGenPhoton",                  "title":"Number of final state gen photons",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "FSGenPhoton_e":                    {"name":"FSGenPhoton_e",                  "title":"Final state gen photons energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "FSGenPhoton_p":                    {"name":"FSGenPhoton_p",                  "title":"Final state gen photons p [GeV]",                "bin":50, "xmin":0, "xmax":100},
    "FSGenPhoton_pt":                   {"name":"FSGenPhoton_pt",                 "title":"Final state gen photons p_{T} [GeV]",            "bin":50, "xmin":0, "xmax":100},
    "FSGenPhoton_px":                   {"name":"FSGenPhoton_px",                 "title":"Final state gen photons p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenPhoton_py":                   {"name":"FSGenPhoton_py",                 "title":"Final state gen photons p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenPhoton_pz":                   {"name":"FSGenPhoton_pz",                 "title":"Final state gen photons p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "FSGenPhoton_y":                    {"name":"FSGenPhoton_y",                  "title":"Final state gen photons rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "FSGenPhoton_eta":                  {"name":"FSGenPhoton_eta",                "title":"Final state gen photons #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenPhoton_theta":                {"name":"FSGenPhoton_theta",              "title":"Final state gen photons #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "FSGenPhoton_phi":                  {"name":"FSGenPhoton_phi",                "title":"Final state gen photons #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "FSGenPhoton_charge":               {"name":"FSGenPhoton_charge",             "title":"Final state gen photons charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},

    "n_GenHiggs":                       {"name":"n_GenHiggs",                  "title":"Number of gen Higgs",              "bin":5, "xmin":-0.5, "xmax":4.5},
    "GenHiggs_e":                       {"name":"GenHiggs_e",                  "title":"Gen Higgs energy [GeV]",           "bin":75, "xmin":0 ,"xmax":200},
    "GenHiggs_p":                       {"name":"GenHiggs_p",                  "title":"Gen Higgs p [GeV]",                "bin":75, "xmin":0 ,"xmax":200},
    "GenHiggs_pt":                      {"name":"GenHiggs_pt",                 "title":"Gen Higgs p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":200},
    "GenHiggs_px":                      {"name":"GenHiggs_px",                 "title":"Gen Higgs p_{x} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenHiggs_py":                      {"name":"GenHiggs_py",                 "title":"Gen Higgs p_{y} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenHiggs_pz":                      {"name":"GenHiggs_pz",                 "title":"Gen Higgs p_{z} [GeV]",            "bin":300, "xmin":-150 ,"xmax":150},
    "GenHiggs_y":                       {"name":"GenHiggs_y",                  "title":"Gen Higgs rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "GenHiggs_mass":                    {"name":"GenHiggs_y",                  "title":"Gen Higgs M [GeV]",                "bin":50, "xmin":90, "xmax":140},
    "GenHiggs_eta":                     {"name":"GenHiggs_eta",                "title":"Gen Higgs #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenHiggs_theta":                   {"name":"GenHiggs_theta",              "title":"Gen Higgs #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "GenHiggs_phi":                     {"name":"GenHiggs_phi",                "title":"Gen Higgs #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "GenHiggs_charge":                  {"name":"GenHiggs_charge",             "title":"Gen Higgs charge",                 "bin":3, "xmin":-1.5,"xmax":1.5},

    ######## Reconstructed particles #######

    "n_RecoElectrons":                  {"name":"n_RecoElectrons",                  "title":"Number of reco electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_e":                   {"name":"RecoElectron_e",                   "title":"Reco electron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoElectron_p":                   {"name":"RecoElectron_p",                   "title":"Reco electron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoElectron_pt":                  {"name":"RecoElectron_pt",                  "title":"Reco electron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoElectron_px":                  {"name":"RecoElectron_px",                  "title":"Reco electron p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoElectron_py":                  {"name":"RecoElectron_py",                  "title":"Reco electron p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoElectron_pz":                  {"name":"RecoElectron_pz",                  "title":"Reco electron p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoElectron_y":                   {"name":"RecoElectron_y",                   "title":"Reco electron rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_eta":                 {"name":"RecoElectron_eta",                 "title":"Reco electron #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_theta":               {"name":"RecoElectron_theta",               "title":"Reco electron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_phi":                 {"name":"RecoElectron_phi",                 "title":"Reco electron #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_charge":              {"name":"RecoElectron_charge",              "title":"Reco electron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_mass":                {"name":"RecoElectron_mass",                "title":"Reco electron mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_absD0":          {"name":"RecoElectronTrack_absD0",          "title":"Reco electron tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absZ0":          {"name":"RecoElectronTrack_absZ0",          "title":"Reco electron tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_absD0sig":       {"name":"RecoElectronTrack_absD0sig",       "title":"Reco electron tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_absZ0sig":       {"name":"RecoElectronTrack_absZ0sig",       "title":"Reco electron tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_D0cov":          {"name":"RecoElectronTrack_D0cov",          "title":"Reco electron tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_Z0cov":          {"name":"RecoElectronTrack_Z0cov",          "title":"Reco electron tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoElectrons_sel":                  {"name":"n_RecoElectrons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoElectron_sel_e":                   {"name":"RecoElectron_sel_e",                   "title":"Reco electron isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoElectron_sel_p":                   {"name":"RecoElectron_sel_p",                   "title":"Reco electron isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoElectron_sel_pt":                  {"name":"RecoElectron_sel_pt",                  "title":"Reco electron isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoElectron_sel_px":                  {"name":"RecoElectron_sel_px",                  "title":"Reco electron isolated p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoElectron_sel_py":                  {"name":"RecoElectron_sel_py",                  "title":"Reco electron isolated p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoElectron_sel_pz":                  {"name":"RecoElectron_sel_pz",                  "title":"Reco electron isolated p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoElectron_sel_y":                   {"name":"RecoElectron_sel_y",                   "title":"Reco electron isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoElectron_sel_eta":                 {"name":"RecoElectron_sel_eta",                 "title":"Reco electron isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_theta":               {"name":"RecoElectron_sel_theta",               "title":"Reco electron isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoElectron_sel_phi":                 {"name":"RecoElectron_sel_phi",                 "title":"Reco electron isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoElectron_sel_charge":              {"name":"RecoElectron_sel_charge",              "title":"Reco electron isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoElectron_sel_mass":                {"name":"RecoElectron_sel_mass",                "title":"Reco electron isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoElectronTrack_sel_absD0":          {"name":"RecoElectronTrack_sel_absD0",          "title":"Reco electron isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absZ0":          {"name":"RecoElectronTrack_sel_absZ0",          "title":"Reco electron isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoElectronTrack_sel_absD0sig":       {"name":"RecoElectronTrack_sel_absD0sig",       "title":"Reco electron isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_absZ0sig":       {"name":"RecoElectronTrack_sel_absZ0sig",       "title":"Reco electron isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoElectronTrack_sel_D0cov":          {"name":"RecoElectronTrack_sel_D0cov",          "title":"Reco electron isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoElectronTrack_sel_Z0cov":          {"name":"RecoElectronTrack_sel_Z0cov",          "title":"Reco electron isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons":                  {"name":"n_RecoMuons",                  "title":"Number of reco muons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_e":                   {"name":"RecoMuon_e",                   "title":"Reco muon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoMuon_p":                   {"name":"RecoMuon_p",                   "title":"Reco muon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoMuon_pt":                  {"name":"RecoMuon_pt",                  "title":"Reco muon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoMuon_px":                  {"name":"RecoMuon_px",                  "title":"Reco muon p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoMuon_py":                  {"name":"RecoMuon_py",                  "title":"Reco muon p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoMuon_pz":                  {"name":"RecoMuon_pz",                  "title":"Reco muon p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoMuon_y":                   {"name":"RecoMuon_y",                   "title":"Reco muon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_eta":                 {"name":"RecoMuon_eta",                 "title":"Reco muon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_theta":               {"name":"RecoMuon_theta",               "title":"Reco muon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_phi":                 {"name":"RecoMuon_phi",                 "title":"Reco muon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_charge":              {"name":"RecoMuon_charge",              "title":"Reco muon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_mass":                {"name":"RecoMuon_mass",                "title":"Reco muon mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_absD0":          {"name":"RecoMuonTrack_absD0",          "title":"Reco muon tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absZ0":          {"name":"RecoMuonTrack_absZ0",          "title":"Reco muon tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_absD0sig":       {"name":"RecoMuonTrack_absD0sig",       "title":"Reco muon tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_absZ0sig":       {"name":"RecoMuonTrack_absZ0sig",       "title":"Reco muon tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_D0cov":          {"name":"RecoMuonTrack_D0cov",          "title":"Reco muon tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_Z0cov":          {"name":"RecoMuonTrack_Z0cov",          "title":"Reco muon tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoMuons_sel":                  {"name":"n_RecoMuons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoMuon_sel_e":                   {"name":"RecoMuon_sel_e",                   "title":"Reco muon isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoMuon_sel_p":                   {"name":"RecoMuon_sel_p",                   "title":"Reco muon isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoMuon_sel_pt":                  {"name":"RecoMuon_sel_pt",                  "title":"Reco muon isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoMuon_sel_px":                  {"name":"RecoMuon_sel_px",                  "title":"Reco muon isolated p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoMuon_sel_py":                  {"name":"RecoMuon_sel_py",                  "title":"Reco muon isolated p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoMuon_sel_pz":                  {"name":"RecoMuon_sel_pz",                  "title":"Reco muon isolated p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoMuon_sel_y":                   {"name":"RecoMuon_sel_y",                   "title":"Reco muon isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoMuon_sel_eta":                 {"name":"RecoMuon_sel_eta",                 "title":"Reco muon isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_theta":               {"name":"RecoMuon_sel_theta",               "title":"Reco muon isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoMuon_sel_phi":                 {"name":"RecoMuon_sel_phi",                 "title":"Reco muon isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoMuon_sel_charge":              {"name":"RecoMuon_sel_charge",              "title":"Reco muon isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoMuon_sel_mass":                {"name":"RecoMuon_sel_mass",                "title":"Reco muon isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoMuonTrack_sel_absD0":          {"name":"RecoMuonTrack_sel_absD0",          "title":"Reco muon isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absZ0":          {"name":"RecoMuonTrack_sel_absZ0",          "title":"Reco muon isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoMuonTrack_sel_absD0sig":       {"name":"RecoMuonTrack_sel_absD0sig",       "title":"Reco muon isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_absZ0sig":       {"name":"RecoMuonTrack_sel_absZ0sig",       "title":"Reco muon isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoMuonTrack_sel_D0cov":          {"name":"RecoMuonTrack_sel_D0cov",          "title":"Reco muon isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoMuonTrack_sel_Z0cov":          {"name":"RecoMuonTrack_sel_Z0cov",          "title":"Reco muon isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons":                {"name":"n_RecoLeptons",                  "title":"Number of reco leptons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoLepton_e":                 {"name":"RecoLepton_e",                   "title":"Reco lepton energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoLepton_p":                 {"name":"RecoLepton_p",                   "title":"Reco lepton p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoLepton_pt":                {"name":"RecoLepton_pt",                  "title":"Reco lepton p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoLepton_px":                {"name":"RecoLepton_px",                  "title":"Reco lepton p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoLepton_py":                {"name":"RecoLepton_py",                  "title":"Reco lepton p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoLepton_pz":                {"name":"RecoLepton_pz",                  "title":"Reco lepton p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoLepton_y":                 {"name":"RecoLepton_y",                   "title":"Reco lepton rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_eta":               {"name":"RecoLepton_eta",                 "title":"Reco lepton #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_theta":             {"name":"RecoLepton_theta",               "title":"Reco lepton #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_phi":               {"name":"RecoLepton_phi",                 "title":"Reco lepton #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_charge":            {"name":"RecoLepton_charge",              "title":"Reco lepton charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_mass":              {"name":"RecoLepton_mass",                "title":"Reco lepton mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_absD0":        {"name":"RecoLeptonTrack_absD0",          "title":"Reco lepton tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absZ0":        {"name":"RecoLeptonTrack_absZ0",          "title":"Reco lepton tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_absD0sig":     {"name":"RecoLeptonTrack_absD0sig",       "title":"Reco lepton tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_absZ0sig":     {"name":"RecoLeptonTrack_absZ0sig",       "title":"Reco lepton tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_D0cov":        {"name":"RecoLeptonTrack_D0cov",          "title":"Reco lepton tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_Z0cov":        {"name":"RecoLeptonTrack_Z0cov",          "title":"Reco lepton tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoLeptons_sel":                {"name":"n_RecoLeptons_sel",                  "title":"Number of reco isolated electrons",                     "bin":5, "xmin":-0.5, "xmax":4.},
    "RecoLepton_sel_e":                 {"name":"RecoLepton_sel_e",                   "title":"Reco lepton isolated energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoLepton_sel_p":                 {"name":"RecoLepton_sel_p",                   "title":"Reco lepton isolated p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoLepton_sel_pt":                {"name":"RecoLepton_sel_pt",                  "title":"Reco lepton isolated p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoLepton_sel_px":                {"name":"RecoLepton_sel_px",                  "title":"Reco lepton isolated p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoLepton_sel_py":                {"name":"RecoLepton_sel_py",                  "title":"Reco lepton isolated p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoLepton_sel_pz":                {"name":"RecoLepton_sel_pz",                  "title":"Reco lepton isolated p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoLepton_sel_y":                 {"name":"RecoLepton_sel_y",                   "title":"Reco lepton isolated rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoLepton_sel_eta":               {"name":"RecoLepton_sel_eta",                 "title":"Reco lepton isolated #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_theta":             {"name":"RecoLepton_sel_theta",               "title":"Reco lepton isolated #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoLepton_sel_phi":               {"name":"RecoLepton_sel_phi",                 "title":"Reco lepton isolated #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoLepton_sel_charge":            {"name":"RecoLepton_sel_charge",              "title":"Reco lepton isolated charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoLepton_sel_mass":              {"name":"RecoLepton_sel_mass",                "title":"Reco lepton isolated mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "RecoLeptonTrack_sel_absD0":        {"name":"RecoLeptonTrack_sel_absD0",          "title":"Reco lepton isolated tracks |d_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absZ0":        {"name":"RecoLeptonTrack_sel_absZ0",          "title":"Reco lepton isolated tracks |z_{0}| [mm]",            "bin":100,"xmin":0, "xmax":2000},
    "RecoLeptonTrack_sel_absD0sig":     {"name":"RecoLeptonTrack_sel_absD0sig",       "title":"Reco lepton isolated tracks |d_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_absZ0sig":     {"name":"RecoLeptonTrack_sel_absZ0sig",       "title":"Reco lepton isolated tracks |z_{0} significance|",    "bin":100,"xmin":0, "xmax":600000},
    "RecoLeptonTrack_sel_D0cov":        {"name":"RecoLeptonTrack_sel_D0cov",          "title":"Reco lepton isolated tracks d_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},
    "RecoLeptonTrack_sel_Z0cov":        {"name":"RecoLeptonTrack_sel_Z0cov",          "title":"Reco lepton isolated tracks z_{0} #sigma^{2}",        "bin":100,"xmin":0, "xmax":0.5},

    "n_RecoPhotons":            {"name":"n_RecoPhotons",                  "title":"Number of reco photons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "RecoPhoton_e":             {"name":"RecoPhoton_e",                   "title":"Reco photon energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "RecoPhoton_p":             {"name":"RecoPhoton_p",                   "title":"Reco photon p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "RecoPhoton_pt":            {"name":"RecoPhoton_pt",                  "title":"Reco photon p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "RecoPhoton_px":            {"name":"RecoPhoton_px",                  "title":"Reco photon p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoPhoton_py":            {"name":"RecoPhoton_py",                  "title":"Reco photon p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoPhoton_pz":            {"name":"RecoPhoton_pz",                  "title":"Reco photon p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoPhoton_y":             {"name":"RecoPhoton_y",                   "title":"Reco photon rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoPhoton_eta":           {"name":"RecoPhoton_eta",                 "title":"Reco photon #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_theta":         {"name":"RecoPhoton_theta",               "title":"Reco photon #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoPhoton_phi":           {"name":"RecoPhoton_phi",                 "title":"Reco photon #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoPhoton_charge":        {"name":"RecoPhoton_charge",              "title":"Reco photon charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "RecoPhoton_mass":          {"name":"RecoPhoton_mass",                 "title":"Reco photon mass [GeV]",                         "bin":50, "xmin":-0.05,"xmax":0.05},

    "n_NeutralHadrons":            {"name":"n_NeutralHadrons",                  "title":"Number of reco neutral hadrons",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "NeutralHadrons_e":             {"name":"NeutralHadrons_e",                   "title":"Neutral hadron energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "NeutralHadrons_p":             {"name":"NeutralHadrons_p",                   "title":"Neutral hadron p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "NeutralHadrons_pt":            {"name":"NeutralHadrons_pt",                  "title":"Neutral hadron p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "NeutralHadrons_px":            {"name":"NeutralHadrons_px",                  "title":"Neutral hadron p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "NeutralHadrons_py":            {"name":"NeutralHadrons_py",                  "title":"Neutral hadron p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "NeutralHadrons_pz":            {"name":"NeutralHadrons_pz",                  "title":"Neutral hadron p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},

    "NeutralHadrons_eta":           {"name":"NeutralHadrons_eta",                 "title":"Neutral hadron #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "NeutralHadrons_theta":         {"name":"NeutralHadrons_theta",               "title":"Neutral hadron #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "NeutralHadrons_phi":           {"name":"NeutralHadrons_phi",                 "title":"Neutral hadron #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "NeutralHadrons_charge":        {"name":"NeutralHadrons_charge",              "title":"Neutral hadron charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "NeutralHadrons_mass":          {"name":"NeutralHadrons_mass",                 "title":"Neutral hadron mass [GeV]",                         "bin":50, "xmin":0,"xmax":10},

    "RecoEmiss_px":             {"name":"RecoEmiss_px",                  "title":"Reco missing energy p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoEmiss_py":             {"name":"RecoEmiss_py",                  "title":"Reco missing energy p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoEmiss_pz":             {"name":"RecoEmiss_pz",                  "title":"Reco missing energy p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "RecoEmiss_pt":             {"name":"RecoEmiss_pt",                  "title":"Reco missing energy p_{T} [GeV]",                    "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_p":              {"name":"RecoEmiss_p",                   "title":"Reco missing energy p [GeV]",                        "bin":60,"xmin":0 ,"xmax":120},
    "RecoEmiss_e":              {"name":"RecoEmiss_e",                   "title":"Reco missing energy energy [GeV]",                   "bin":60,"xmin":0 ,"xmax":240},
    "RecoEmiss_eta":            {"name":"RecoEmiss_eta",                 "title":"Reco missing energy #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_phi":            {"name":"RecoEmiss_phi",                 "title":"Reco missing energy #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoEmiss_theta":          {"name":"RecoEmiss_theta",               "title":"Reco missing energy #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "RecoEmiss_y":              {"name":"RecoEmiss_y",                   "title":"Reco missing energy rapidity",                       "bin":40, "xmin":-4., "xmax":4.},
    "RecoEmiss_costheta":       {"name":"RecoEmiss_costheta",               "title":"Reco missing energy |cos(#theta)|",                 "bin":50, "xmin":0,"xmax":1.},

    "TagJet_R5_e":                {"name":"TagJet_R5_e",                   "title":"R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},   
    "TagJet_R5_p":                {"name":"TagJet_R5_p",                   "title":"R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_R5_pt":               {"name":"TagJet_R5_pt",                  "title":"R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_R5_px":               {"name":"TagJet_R5_px",                  "title":"R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_R5_py":               {"name":"TagJet_R5_py",                  "title":"R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_R5_pz":               {"name":"TagJet_R5_pz",                  "title":"R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_R5_eta":              {"name":"TagJet_R5_eta",                 "title":"R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_theta":            {"name":"TagJet_R5_theta",               "title":"R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_R5_phi":              {"name":"TagJet_R5_phi",                 "title":"R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_mass":             {"name":"TagJet_R5_mass",                "title":"R5 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_R5_charge":             {"name":"TagJet_R5_charge",                "title":"R5 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_R5":                {"name":"n_TagJet_R5",                   "title":"Number of R5 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_R5_constituents":             {"name":"n_TagJet_R5_constituents",               "title":"R5 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_R5_charged_constituents":             {"name":"n_TagJet_R5_charged_constituents",               "title":"R5 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_R5_neutral_constituents":             {"name":"n_TagJet_R5_neutral_constituents",               "title":"R5 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_R5_isG":             {"name":"TagJet_R5_isG",                "title":"R5 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isU":             {"name":"TagJet_R5_isU",                "title":"R5 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isD":             {"name":"TagJet_R5_isD",                "title":"R5 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isS":             {"name":"TagJet_R5_isS",                "title":"R5 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isC":             {"name":"TagJet_R5_isC",                "title":"R5 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isB":             {"name":"TagJet_R5_isB",                "title":"R5 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_R5_isTAU":             {"name":"TagJet_R5_isTAU",                "title":"R5 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_R5_p":          {"name":"TauFromJet_R5_p",                   "title":"#tau from R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_R5_pt":         {"name":"TauFromJet_R5_pt",                  "title":"#tau from R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_R5_px":         {"name":"TauFromJet_R5_px",                  "title":"#tau from R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_R5_py":         {"name":"TauFromJet_R5_py",                  "title":"#tau from R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_R5_pz":         {"name":"TauFromJet_R5_pz",                  "title":"#tau from R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_R5_theta":      {"name":"TauFromJet_R5_theta",               "title":"#tau from R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_R5_phi":        {"name":"TauFromJet_R5_phi",                 "title":"#tau from R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_e":          {"name":"TauFromJet_R5_e",                   "title":"#tau from R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_R5_eta":        {"name":"TauFromJet_R5_eta",                 "title":"#tau from R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_R5_y":          {"name":"TauFromJet_R5_y",                   "title":"#tau from R5 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_R5_charge":     {"name":"TauFromJet_R5_charge",              "title":"#tau from R5 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_R5_type":       {"name":"TauFromJet_R5_type",                "title":"#tau from R5 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_R5_mass":       {"name":"TauFromJet_R5_mass",                "title":"#tau from R5 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_R5":          {"name":"n_TauFromJet_R5",                   "title":"Number of #tau from R5 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_R5_sel_e":            {"name":"TagJet_R5_sel_e",                   "title":"Quark/gluon R5 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},    
    "TagJet_R5_sel_p":            {"name":"TagJet_R5_sel_p",                   "title":"Quark/gluon R5 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_R5_sel_pt":           {"name":"TagJet_R5_sel_pt",                  "title":"Quark/gluon R5 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_R5_sel_px":           {"name":"TagJet_R5_sel_px",                  "title":"Quark/gluon R5 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_R5_sel_py":           {"name":"TagJet_R5_sel_py",                  "title":"Quark/gluon R5 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_R5_sel_pz":           {"name":"TagJet_R5_sel_pz",                  "title":"Quark/gluon R5 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_R5_sel_eta":          {"name":"TagJet_R5_sel_eta",                 "title":"Quark/gluon R5 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_sel_theta":        {"name":"TagJet_R5_sel_theta",               "title":"Quark/gluon R5 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_R5_sel_phi":          {"name":"TagJet_R5_sel_phi",                 "title":"Quark/gluon R5 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_R5_sel_mass":         {"name":"TagJet_R5_sel_mass",                "title":"Quark/gluon R5 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_R5_sel":            {"name":"n_TagJet_R5_sel",                   "title":"Number of Quark/gluon R5 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    "TagJet_kt4_e":                {"name":"TagJet_kt4_e",                   "title":"kt4 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},   
    "TagJet_kt4_p":                {"name":"TagJet_kt4_p",                   "title":"kt4 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt4_pt":               {"name":"TagJet_kt4_pt",                  "title":"kt4 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt4_px":               {"name":"TagJet_kt4_px",                  "title":"kt4 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt4_py":               {"name":"TagJet_kt4_py",                  "title":"kt4 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt4_pz":               {"name":"TagJet_kt4_pz",                  "title":"kt4 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt4_eta":              {"name":"TagJet_kt4_eta",                 "title":"kt4 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt4_theta":            {"name":"TagJet_kt4_theta",               "title":"kt4 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt4_phi":              {"name":"TagJet_kt4_phi",                 "title":"kt4 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt4_mass":             {"name":"TagJet_kt4_mass",                "title":"kt4 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_kt4_charge":             {"name":"TagJet_kt4_charge",                "title":"kt4 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_kt4":                {"name":"n_TagJet_kt4",                   "title":"Number of kt4 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_kt4_constituents":             {"name":"n_TagJet_kt4_constituents",               "title":"kt4 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt4_charged_constituents":             {"name":"n_TagJet_kt4_charged_constituents",               "title":"kt4 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt4_neutral_constituents":             {"name":"n_TagJet_kt4_neutral_constituents",               "title":"kt4 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_kt4_isG":             {"name":"TagJet_kt4_isG",                "title":"kt4 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt4_isU":             {"name":"TagJet_kt4_isU",                "title":"kt4 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt4_isD":             {"name":"TagJet_kt4_isD",                "title":"kt4 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt4_isS":             {"name":"TagJet_kt4_isS",                "title":"kt4 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt4_isC":             {"name":"TagJet_kt4_isC",                "title":"kt4 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt4_isB":             {"name":"TagJet_kt4_isB",                "title":"kt4 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt4_isTAU":             {"name":"TagJet_kt4_isTAU",                "title":"kt4 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_kt4_p":          {"name":"TauFromJet_kt4_p",                   "title":"#tau from kt4 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt4_pt":         {"name":"TauFromJet_kt4_pt",                  "title":"#tau from kt4 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt4_px":         {"name":"TauFromJet_kt4_px",                  "title":"#tau from kt4 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt4_py":         {"name":"TauFromJet_kt4_py",                  "title":"#tau from kt4 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt4_pz":         {"name":"TauFromJet_kt4_pz",                  "title":"#tau from kt4 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt4_theta":      {"name":"TauFromJet_kt4_theta",               "title":"#tau from kt4 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_kt4_phi":        {"name":"TauFromJet_kt4_phi",                 "title":"#tau from kt4 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt4_e":          {"name":"TauFromJet_kt4_e",                   "title":"#tau from kt4 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt4_eta":        {"name":"TauFromJet_kt4_eta",                 "title":"#tau from kt4 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt4_y":          {"name":"TauFromJet_kt4_y",                   "title":"#tau from kt4 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_kt4_charge":     {"name":"TauFromJet_kt4_charge",              "title":"#tau from kt4 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_kt4_type":       {"name":"TauFromJet_kt4_type",                "title":"#tau from kt4 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_kt4_mass":       {"name":"TauFromJet_kt4_mass",                "title":"#tau from kt4 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_kt4":          {"name":"n_TauFromJet_kt4",                   "title":"Number of #tau from kt4 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_kt4_sel_e":            {"name":"TagJet_kt4_sel_e",                   "title":"Quark/gluon kt4 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},    
    "TagJet_kt4_sel_p":            {"name":"TagJet_kt4_sel_p",                   "title":"Quark/gluon kt4 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt4_sel_pt":           {"name":"TagJet_kt4_sel_pt",                  "title":"Quark/gluon kt4 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt4_sel_px":           {"name":"TagJet_kt4_sel_px",                  "title":"Quark/gluon kt4 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt4_sel_py":           {"name":"TagJet_kt4_sel_py",                  "title":"Quark/gluon kt4 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt4_sel_pz":           {"name":"TagJet_kt4_sel_pz",                  "title":"Quark/gluon kt4 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt4_sel_eta":          {"name":"TagJet_kt4_sel_eta",                 "title":"Quark/gluon kt4 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt4_sel_theta":        {"name":"TagJet_kt4_sel_theta",               "title":"Quark/gluon kt4 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt4_sel_phi":          {"name":"TagJet_kt4_sel_phi",                 "title":"Quark/gluon kt4 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt4_sel_mass":         {"name":"TagJet_kt4_sel_mass",                "title":"Quark/gluon kt4 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_kt4_sel":            {"name":"n_TagJet_kt4_sel",                   "title":"Number of Quark/gluon kt4 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    "TagJet_kt3_e":                {"name":"TagJet_kt3_e",                   "title":"kt3 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},   
    "TagJet_kt3_p":                {"name":"TagJet_kt3_p",                   "title":"kt3 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt3_pt":               {"name":"TagJet_kt3_pt",                  "title":"kt3 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt3_px":               {"name":"TagJet_kt3_px",                  "title":"kt3 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt3_py":               {"name":"TagJet_kt3_py",                  "title":"kt3 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt3_pz":               {"name":"TagJet_kt3_pz",                  "title":"kt3 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt3_eta":              {"name":"TagJet_kt3_eta",                 "title":"kt3 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt3_theta":            {"name":"TagJet_kt3_theta",               "title":"kt3 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt3_phi":              {"name":"TagJet_kt3_phi",                 "title":"kt3 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt3_mass":             {"name":"TagJet_kt3_mass",                "title":"kt3 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_kt3_charge":             {"name":"TagJet_kt3_charge",                "title":"kt3 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_kt3":                {"name":"n_TagJet_kt3",                   "title":"Number of kt3 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_kt3_constituents":             {"name":"n_TagJet_kt3_constituents",               "title":"kt3 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt3_charged_constituents":             {"name":"n_TagJet_kt3_charged_constituents",               "title":"kt3 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt3_neutral_constituents":             {"name":"n_TagJet_kt3_neutral_constituents",               "title":"kt3 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_kt3_isG":             {"name":"TagJet_kt3_isG",                "title":"kt3 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt3_isU":             {"name":"TagJet_kt3_isU",                "title":"kt3 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt3_isD":             {"name":"TagJet_kt3_isD",                "title":"kt3 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt3_isS":             {"name":"TagJet_kt3_isS",                "title":"kt3 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt3_isC":             {"name":"TagJet_kt3_isC",                "title":"kt3 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt3_isB":             {"name":"TagJet_kt3_isB",                "title":"kt3 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt3_isTAU":             {"name":"TagJet_kt3_isTAU",                "title":"kt3 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_kt3_p":          {"name":"TauFromJet_kt3_p",                   "title":"#tau from kt3 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt3_pt":         {"name":"TauFromJet_kt3_pt",                  "title":"#tau from kt3 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt3_px":         {"name":"TauFromJet_kt3_px",                  "title":"#tau from kt3 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt3_py":         {"name":"TauFromJet_kt3_py",                  "title":"#tau from kt3 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt3_pz":         {"name":"TauFromJet_kt3_pz",                  "title":"#tau from kt3 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt3_theta":      {"name":"TauFromJet_kt3_theta",               "title":"#tau from kt3 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_kt3_phi":        {"name":"TauFromJet_kt3_phi",                 "title":"#tau from kt3 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt3_e":          {"name":"TauFromJet_kt3_e",                   "title":"#tau from kt3 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt3_eta":        {"name":"TauFromJet_kt3_eta",                 "title":"#tau from kt3 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt3_y":          {"name":"TauFromJet_kt3_y",                   "title":"#tau from kt3 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_kt3_charge":     {"name":"TauFromJet_kt3_charge",              "title":"#tau from kt3 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_kt3_type":       {"name":"TauFromJet_kt3_type",                "title":"#tau from kt3 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_kt3_mass":       {"name":"TauFromJet_kt3_mass",                "title":"#tau from kt3 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_kt3":          {"name":"n_TauFromJet_kt3",                   "title":"Number of #tau from kt3 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_kt3_sel_e":            {"name":"TagJet_kt3_sel_e",                   "title":"Quark/gluon kt3 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},    
    "TagJet_kt3_sel_p":            {"name":"TagJet_kt3_sel_p",                   "title":"Quark/gluon kt3 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt3_sel_pt":           {"name":"TagJet_kt3_sel_pt",                  "title":"Quark/gluon kt3 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt3_sel_px":           {"name":"TagJet_kt3_sel_px",                  "title":"Quark/gluon kt3 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt3_sel_py":           {"name":"TagJet_kt3_sel_py",                  "title":"Quark/gluon kt3 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt3_sel_pz":           {"name":"TagJet_kt3_sel_pz",                  "title":"Quark/gluon kt3 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt3_sel_eta":          {"name":"TagJet_kt3_sel_eta",                 "title":"Quark/gluon kt3 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt3_sel_theta":        {"name":"TagJet_kt3_sel_theta",               "title":"Quark/gluon kt3 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt3_sel_phi":          {"name":"TagJet_kt3_sel_phi",                 "title":"Quark/gluon kt3 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt3_sel_mass":         {"name":"TagJet_kt3_sel_mass",                "title":"Quark/gluon kt3 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_kt3_sel":            {"name":"n_TagJet_kt3_sel",                   "title":"Number of Quark/gluon kt3 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    "TagJet_kt2_e":                {"name":"TagJet_kt2_e",                   "title":"kt2 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},   
    "TagJet_kt2_p":                {"name":"TagJet_kt2_p",                   "title":"kt2 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt2_pt":               {"name":"TagJet_kt2_pt",                  "title":"kt2 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt2_px":               {"name":"TagJet_kt2_px",                  "title":"kt2 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt2_py":               {"name":"TagJet_kt2_py",                  "title":"kt2 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt2_pz":               {"name":"TagJet_kt2_pz",                  "title":"kt2 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt2_eta":              {"name":"TagJet_kt2_eta",                 "title":"kt2 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt2_theta":            {"name":"TagJet_kt2_theta",               "title":"kt2 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt2_phi":              {"name":"TagJet_kt2_phi",                 "title":"kt2 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt2_mass":             {"name":"TagJet_kt2_mass",                "title":"kt2 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_kt2_charge":             {"name":"TagJet_kt2_charge",                "title":"kt2 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_kt2":                {"name":"n_TagJet_kt2",                   "title":"Number of kt2 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_kt2_constituents":             {"name":"n_TagJet_kt2_constituents",               "title":"kt2 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt2_charged_constituents":             {"name":"n_TagJet_kt2_charged_constituents",               "title":"kt2 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt2_neutral_constituents":             {"name":"n_TagJet_kt2_neutral_constituents",               "title":"kt2 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_kt2_isG":             {"name":"TagJet_kt2_isG",                "title":"kt2 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt2_isU":             {"name":"TagJet_kt2_isU",                "title":"kt2 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt2_isD":             {"name":"TagJet_kt2_isD",                "title":"kt2 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt2_isS":             {"name":"TagJet_kt2_isS",                "title":"kt2 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt2_isC":             {"name":"TagJet_kt2_isC",                "title":"kt2 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt2_isB":             {"name":"TagJet_kt2_isB",                "title":"kt2 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt2_isTAU":             {"name":"TagJet_kt2_isTAU",                "title":"kt2 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_kt2_p":          {"name":"TauFromJet_kt2_p",                   "title":"#tau from kt2 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt2_pt":         {"name":"TauFromJet_kt2_pt",                  "title":"#tau from kt2 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt2_px":         {"name":"TauFromJet_kt2_px",                  "title":"#tau from kt2 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt2_py":         {"name":"TauFromJet_kt2_py",                  "title":"#tau from kt2 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt2_pz":         {"name":"TauFromJet_kt2_pz",                  "title":"#tau from kt2 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt2_theta":      {"name":"TauFromJet_kt2_theta",               "title":"#tau from kt2 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_kt2_phi":        {"name":"TauFromJet_kt2_phi",                 "title":"#tau from kt2 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt2_e":          {"name":"TauFromJet_kt2_e",                   "title":"#tau from kt2 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt2_eta":        {"name":"TauFromJet_kt2_eta",                 "title":"#tau from kt2 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt2_y":          {"name":"TauFromJet_kt2_y",                   "title":"#tau from kt2 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_kt2_charge":     {"name":"TauFromJet_kt2_charge",              "title":"#tau from kt2 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_kt2_type":       {"name":"TauFromJet_kt2_type",                "title":"#tau from kt2 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_kt2_mass":       {"name":"TauFromJet_kt2_mass",                "title":"#tau from kt2 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_kt2":          {"name":"n_TauFromJet_kt2",                   "title":"Number of #tau from kt2 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_kt2_sel_e":            {"name":"TagJet_kt2_sel_e",                   "title":"Quark/gluon kt2 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},    
    "TagJet_kt2_sel_p":            {"name":"TagJet_kt2_sel_p",                   "title":"Quark/gluon kt2 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt2_sel_pt":           {"name":"TagJet_kt2_sel_pt",                  "title":"Quark/gluon kt2 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt2_sel_px":           {"name":"TagJet_kt2_sel_px",                  "title":"Quark/gluon kt2 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt2_sel_py":           {"name":"TagJet_kt2_sel_py",                  "title":"Quark/gluon kt2 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt2_sel_pz":           {"name":"TagJet_kt2_sel_pz",                  "title":"Quark/gluon kt2 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt2_sel_eta":          {"name":"TagJet_kt2_sel_eta",                 "title":"Quark/gluon kt2 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt2_sel_theta":        {"name":"TagJet_kt2_sel_theta",               "title":"Quark/gluon kt2 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt2_sel_phi":          {"name":"TagJet_kt2_sel_phi",                 "title":"Quark/gluon kt2 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt2_sel_mass":         {"name":"TagJet_kt2_sel_mass",                "title":"Quark/gluon kt2 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_kt2_sel":            {"name":"n_TagJet_kt2_sel",                   "title":"Number of Quark/gluon kt2 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    "TagJet_kt1_e":                {"name":"TagJet_kt1_e",                   "title":"kt1 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},   
    "TagJet_kt1_p":                {"name":"TagJet_kt1_p",                   "title":"kt1 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt1_pt":               {"name":"TagJet_kt1_pt",                  "title":"kt1 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt1_px":               {"name":"TagJet_kt1_px",                  "title":"kt1 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt1_py":               {"name":"TagJet_kt1_py",                  "title":"kt1 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt1_pz":               {"name":"TagJet_kt1_pz",                  "title":"kt1 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt1_eta":              {"name":"TagJet_kt1_eta",                 "title":"kt1 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt1_theta":            {"name":"TagJet_kt1_theta",               "title":"kt1 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt1_phi":              {"name":"TagJet_kt1_phi",                 "title":"kt1 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt1_mass":             {"name":"TagJet_kt1_mass",                "title":"kt1 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "TagJet_kt1_charge":             {"name":"TagJet_kt1_charge",                "title":"kt1 jet charge",                     "bin":10, "xmin":-5., "xmax":5.},
    "n_TagJet_kt1":                {"name":"n_TagJet_kt1",                   "title":"Number of kt1 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},
    "n_TagJet_kt1_constituents":             {"name":"n_TagJet_kt1_constituents",               "title":"kt1 jet constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt1_charged_constituents":             {"name":"n_TagJet_kt1_charged_constituents",               "title":"kt1 jet charged constituents",                   "bin":20, "xmin":0., "xmax":20.},
    "n_TagJet_kt1_neutral_constituents":             {"name":"n_TagJet_kt1_neutral_constituents",               "title":"kt1 jet neutral constituents",                   "bin":20, "xmin":0., "xmax":20.},

    "TagJet_kt1_isG":             {"name":"TagJet_kt1_isG",                "title":"kt1 jet G score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt1_isU":             {"name":"TagJet_kt1_isU",                "title":"kt1 jet U score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt1_isD":             {"name":"TagJet_kt1_isD",                "title":"kt1 jet D score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt1_isS":             {"name":"TagJet_kt1_isS",                "title":"kt1 jet S score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt1_isC":             {"name":"TagJet_kt1_isC",                "title":"kt1 jet C score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt1_isB":             {"name":"TagJet_kt1_isB",                "title":"kt1 jet B score",                     "bin":100, "xmin":0., "xmax":1.},
    "TagJet_kt1_isTAU":             {"name":"TagJet_kt1_isTAU",                "title":"kt1 jet TAU score",                     "bin":100, "xmin":0., "xmax":1.},

    "TauFromJet_kt1_p":          {"name":"TauFromJet_kt1_p",                   "title":"#tau from kt1 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt1_pt":         {"name":"TauFromJet_kt1_pt",                  "title":"#tau from kt1 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt1_px":         {"name":"TauFromJet_kt1_px",                  "title":"#tau from kt1 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt1_py":         {"name":"TauFromJet_kt1_py",                  "title":"#tau from kt1 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt1_pz":         {"name":"TauFromJet_kt1_pz",                  "title":"#tau from kt1 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TauFromJet_kt1_theta":      {"name":"TauFromJet_kt1_theta",               "title":"#tau from kt1 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TauFromJet_kt1_phi":        {"name":"TauFromJet_kt1_phi",                 "title":"#tau from kt1 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt1_e":          {"name":"TauFromJet_kt1_e",                   "title":"#tau from kt1 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},
    "TauFromJet_kt1_eta":        {"name":"TauFromJet_kt1_eta",                 "title":"#tau from kt1 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauFromJet_kt1_y":          {"name":"TauFromJet_kt1_y",                   "title":"#tau from kt1 jet rapidity",                       "bin":80,"xmin":-4. ,"xmax":4.},
    "TauFromJet_kt1_charge":     {"name":"TauFromJet_kt1_charge",              "title":"#tau from kt1 jet charge",                         "bin":3, "xmin":-1.5,"xmax":1.5},
    "TauFromJet_kt1_type":       {"name":"TauFromJet_kt1_type",                "title":"#tau from kt1 jet decay type",                     "bin":100, "xmin":-20, "xmax":80},
    "TauFromJet_kt1_mass":       {"name":"TauFromJet_kt1_mass",                "title":"#tau from kt1 jet mass [GeV]",                     "bin":15, "xmin":0., "xmax":3.},
    "n_TauFromJet_kt1":          {"name":"n_TauFromJet_kt1",                   "title":"Number of #tau from kt1 jet",                     "bin":5, "xmin":-0.5, "xmax":4.5},

    "TagJet_kt1_sel_e":            {"name":"TagJet_kt1_sel_e",                   "title":"Quark/gluon kt1 jet energy [GeV]",                   "bin":50,"xmin":0 ,"xmax":200},    
    "TagJet_kt1_sel_p":            {"name":"TagJet_kt1_sel_p",                   "title":"Quark/gluon kt1 jet p [GeV]",                        "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt1_sel_pt":           {"name":"TagJet_kt1_sel_pt",                  "title":"Quark/gluon kt1 jet p_{T} [GeV]",                    "bin":50,"xmin":0 ,"xmax":200},
    "TagJet_kt1_sel_px":           {"name":"TagJet_kt1_sel_px",                  "title":"Quark/gluon kt1 jet p_{x} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt1_sel_py":           {"name":"TagJet_kt1_sel_py",                  "title":"Quark/gluon kt1 jet p_{y} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt1_sel_pz":           {"name":"TagJet_kt1_sel_pz",                  "title":"Quark/gluon kt1 jet p_{z} [GeV]",                    "bin":50,"xmin":-200 ,"xmax":200},
    "TagJet_kt1_sel_eta":          {"name":"TagJet_kt1_sel_eta",                 "title":"Quark/gluon kt1 jet #eta",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt1_sel_theta":        {"name":"TagJet_kt1_sel_theta",               "title":"Quark/gluon kt1 jet #theta",                         "bin":16, "xmin":0,"xmax":3.2},
    "TagJet_kt1_sel_phi":          {"name":"TagJet_kt1_sel_phi",                 "title":"Quark/gluon kt1 jet #phi",                           "bin":32, "xmin":-3.2,"xmax":3.2},
    "TagJet_kt1_sel_mass":         {"name":"TagJet_kt1_sel_mass",                "title":"Quark/gluon kt1 jet mass [GeV]",                     "bin":20, "xmin":0., "xmax":2.},
    "n_TagJet_kt1_sel":            {"name":"n_TagJet_kt1_sel",                   "title":"Number of Quark/gluon kt1 jet",                     "bin":7, "xmin":-0.5, "xmax":6.5},

    ########################

    "RecoH_px":                 {"name":"RecoH_px",                 "title":"Reco H p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "RecoH_py":                 {"name":"RecoH_py",                 "title":"Reco H p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "RecoH_pz":                 {"name":"RecoH_pz",                 "title":"Reco H p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},
    "RecoH_p":                  {"name":"RecoH_p",                  "title":"Reco H p [GeV]",                "bin":75, "xmin":0 ,"xmax":200},
    "RecoH_pt":                 {"name":"RecoH_pt",                 "title":"Reco H p_{T} [GeV]",            "bin":75, "xmin":0 ,"xmax":200},
    "RecoH_e":                  {"name":"RecoH_e",                  "title":"Reco H energy [GeV]",           "bin":75, "xmin":0 ,"xmax":200},
    "RecoH_eta":                {"name":"RecoH_eta",                "title":"Reco H #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_phi":                {"name":"RecoH_phi",                "title":"Reco H #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "RecoH_theta":              {"name":"RecoH_theta",              "title":"Reco H #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "RecoH_y":                  {"name":"RecoH_y",                  "title":"Reco H rapidity",               "bin":40, "xmin":-4., "xmax":4.},
    "RecoH_mass":               {"name":"RecoH_mass",               "title":"Reco H mass",                   "bin":75, "xmin":0 ,"xmax":200},

    "TauLead_px":               {"name":"TauLead_px",                 "title":"#tau_{leading} p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},   
    "TauLead_py":               {"name":"TauLead_py",                 "title":"#tau_{leading} p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},   
    "TauLead_pz":               {"name":"TauLead_pz",                 "title":"#tau_{leading} p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},   
    "TauLead_p":                {"name":"TauLead_p",                  "title":"#tau_{leading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":200},
    "TauLead_pt":               {"name":"TauLead_pt",                 "title":"#tau_{leading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":200},
    "TauLead_e":                {"name":"TauLead_e",                  "title":"#tau_{leading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauLead_eta":              {"name":"TauLead_eta",                "title":"#tau_{leading} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_phi":              {"name":"TauLead_phi",                "title":"#tau_{leading} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauLead_theta":            {"name":"TauLead_theta",              "title":"#tau_{leading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauLead_y":                {"name":"TauLead_y",                  "title":"#tau_{leading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauLead_mass":             {"name":"TauLead_mass",               "title":"#tau_{leading} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauSub_px":                {"name":"TauSub_px",                 "title":"#tau_{subleading} p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200}, 
    "TauSub_py":                {"name":"TauSub_py",                 "title":"#tau_{subleading} p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200}, 
    "TauSub_pz":                {"name":"TauSub_pz",                 "title":"#tau_{subleading} p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200}, 
    "TauSub_p":                 {"name":"TauSub_p",                  "title":"#tau_{subleading} p [GeV]",                "bin":50,"xmin":0 ,"xmax":200},
    "TauSub_pt":                {"name":"TauSub_pt",                 "title":"#tau_{subleading} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":200},
    "TauSub_e":                 {"name":"TauSub_e",                  "title":"#tau_{subleading} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauSub_eta":               {"name":"TauSub_eta",                "title":"#tau_{subleading} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_phi":               {"name":"TauSub_phi",                "title":"#tau_{subleading} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauSub_theta":             {"name":"TauSub_theta",              "title":"#tau_{subleading} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauSub_y":                 {"name":"TauSub_y",                  "title":"#tau_{subleading} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauSub_mass":              {"name":"TauSub_mass",               "title":"#tau_{subleading} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauP_px":               {"name":"TauP_px",                 "title":"#tau^{+} p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},   
    "TauP_py":               {"name":"TauP_py",                 "title":"#tau^{+} p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},   
    "TauP_pz":               {"name":"TauP_pz",                 "title":"#tau^{+} p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200},   
    "TauP_p":                {"name":"TauP_p",                  "title":"#tau^{+} p [GeV]",                "bin":50,"xmin":0 ,"xmax":200},
    "TauP_pt":               {"name":"TauP_pt",                 "title":"#tau^{+} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":200},
    "TauP_e":                {"name":"TauP_e",                  "title":"#tau^{+} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauP_eta":              {"name":"TauP_eta",                "title":"#tau^{+} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauP_phi":              {"name":"TauP_phi",                "title":"#tau^{+} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauP_theta":            {"name":"TauP_theta",              "title":"#tau^{+} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauP_y":                {"name":"TauP_y",                  "title":"#tau^{+} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauP_mass":             {"name":"TauP_mass",               "title":"#tau^{+} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "TauM_px":                {"name":"TauM_px",                 "title":"#tau^{-} p_{x} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200}, 
    "TauM_py":                {"name":"TauM_py",                 "title":"#tau^{-} p_{y} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200}, 
    "TauM_pz":                {"name":"TauM_pz",                 "title":"#tau^{-} p_{z} [GeV]",            "bin":50,"xmin":-200 ,"xmax":200}, 
    "TauM_p":                 {"name":"TauM_p",                  "title":"#tau^{-} p [GeV]",                "bin":50,"xmin":0 ,"xmax":200},
    "TauM_pt":                {"name":"TauM_pt",                 "title":"#tau^{-} p_{T} [GeV]",            "bin":50,"xmin":0 ,"xmax":200},
    "TauM_e":                 {"name":"TauM_e",                  "title":"#tau^{-} energy [GeV]",           "bin":50, "xmin":0, "xmax":100},
    "TauM_eta":               {"name":"TauM_eta",                "title":"#tau^{-} #eta",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauM_phi":               {"name":"TauM_phi",                "title":"#tau^{-} #phi",                   "bin":32, "xmin":-3.2,"xmax":3.2},
    "TauM_theta":             {"name":"TauM_theta",              "title":"#tau^{-} #theta",                 "bin":16, "xmin":0,"xmax":3.2},
    "TauM_y":                 {"name":"TauM_y",                  "title":"#tau^{-} rapidity",               "bin":80, "xmin":-4., "xmax":4.},
    "TauM_mass":              {"name":"TauM_mass",               "title":"#tau^{-} mass",                   "bin":30, "xmin":0., "xmax":3.},

    "Tau_DPhi":         {"name":"Tau_DPhi",           "title":"#Delta#phi(#tau#tau)",                "bin":32, "xmin":-3.2,"xmax":3.2},
    "Tau_DR":                   {"name":"Tau_DR",                     "title":"#Delta R(#tau#tau)",                  "bin":70, "xmin":0,"xmax":7},
    "Tau_cos":                  {"name":"Tau_cos",                    "title":"cos#theta(#tau#tau)",                 "bin":100, "xmin":-1.,"xmax":1.},
    "Tau_DEta":                             {"name":"Tau_DEta",           "title":"Reco di-#tau #Delta#eta",                  "bin":32, "xmin":-3.2,"xmax":3.2},
}